'use strict';
/**
 * "mosse" macro, that translates move names
 */

(function(utils) {

const macros = utils.macros;

macros.mosse = function(str) {
    return str
        .replace(/\bAbsorb\b/g, 'Assorbimento')
        .replace(/\bAcid Spray\b/g, 'Acidobomba')
        .replace(/\bAcid Armor\b/g, 'Scudo Acido')
        .replace(/\bGastro Acid\b/g, 'Gastroacido')
        .replace(/\bAcid\b/g, 'Acido')
        .replace(/\bAcupressure\b/g, 'Acupressione')
        .replace(/\bAerial Ace\b/g, 'Aeroassalto')
        .replace(/\bAeroblast\b/g, 'Aerocolpo')
        .replace(/\bAgility\b/g, 'Agilit&agrave;')
        .replace(/\bAir Cutter\b/g, 'Aerasoio')
        .replace(/\bAir Slash\b/g, 'Eterelama')
        .replace(/\bAmnesia\b/g, 'Amnesia')
        .replace(/\bAncient Power\b/g, 'Forzantica').replace(/\bAncient[Pp]ower\b/g, 'Forzantica')
        .replace(/\bAqua Jet\b/g, 'Acquagetto')
        .replace(/\bAqua Ring\b/g, 'Acquanello')
        .replace(/\bAqua Tail\b/g, 'Idrondata')
        .replace(/\bArm Thrust\b/g, 'Sberletese')
        .replace(/\bAromatherapy\b/g, 'Aromaterapia')
        .replace(/\bAssist\b/g, 'Assistente')
        .replace(/\bAssurance\b/g, 'Garanzia')
        .replace(/\bAstonish\b/g, 'Sgomento')
        .replace(/\bAttack Order\b/g, 'Comandourto')
        .replace(/\bAttract\b/g, 'Attrazione')
        .replace(/\bAura Sphere\b/g, 'Sferapulsar')
        .replace(/\bAurora Beam\b/g, 'Raggiaurora')
        .replace(/\bAvalanche\b/g, 'Slavina')
        .replace(/\bBarrage\b/g, 'Sferattacco')
        .replace(/\bBarrier\b/g, 'Barriera')
        .replace(/\bBaton Pass\b/g, 'Staffetta')
        .replace(/\bBeat Up\b/g, 'Picchiaduro')
        .replace(/\bBelly Drum\b/g, 'Panciamburo')
        .replace(/\bBide\b/g, 'Pazienza')
        .replace(/\bBind\b/g, 'Legatutto')
        .replace(/\bBug Bite\b/g, 'Coleomorso')
        .replace(/\bBite\b/g, 'Morso')
        .replace(/\bBlast Burn\b/g, 'Incendio')
        .replace(/\bBlaze Kick\b/g, 'Calciardente')
        .replace(/\bPetal Blizzard\b/g, 'Fiortempesta')
        .replace(/\bBlizzard\b/g, 'Bora')
        .replace(/\bHeal Block\b/g, 'Anticura')
        .replace(/\bMat Block\b/g, 'Ribaltappeto')
        .replace(/\bBlock\b/g, 'Blocco')
        .replace(/\bBody Slam\b/g, 'Corposcontro')
        .replace(/\bBone Club\b/g, 'Ossoclava')
        .replace(/\bBone Rush\b/g, 'Ossoraffica')
        .replace(/\bBonemerang\b/g, 'Ossomerang')
        .replace(/\bBounce\b/g, 'Rimbalzo')
        .replace(/\bBrave Bird\b/g, 'Baldeali')
        .replace(/\bBrick Break\b/g, 'Breccia')
        .replace(/\bBrine\b/g, 'Acquadisale')
        .replace(/\bBubble Beam\b/g, 'Bollaraggio').replace(/\bBubble[Bb]eam\b/g, 'Bollaraggio')
        .replace(/\bBubble\b/g, 'Bolla')
        .replace(/\bBug Buzz\b/g, 'Ronzio')
        .replace(/\bBulk Up\b/g, 'Granfisico')
        .replace(/\bBullet Punch\b/g, 'Pugnoscarica')
        .replace(/\bBullet Seed\b/g, 'Semitraglia')
        .replace(/\bCalm Mind\b/g, 'Calmamente')
        .replace(/\bCamouflage\b/g, 'Camuffamento')
        .replace(/\bCaptivate\b/g, 'Incanto')
        .replace(/\bCharge Beam\b/g, 'Raggioscossa')
        .replace(/\bDischarge\b/g, 'Scarica')
        .replace(/\bFlame Charge\b/g, 'Nitrocarica')
        .replace(/\bHead Charge\b/g, 'Ricciolata')
        .replace(/\bParabolic Charge\b/g, 'Caricaparabola')
        .replace(/\bWild Charge\b/g, 'Sprizzalampo')
        .replace(/\bCharge\b/g, 'Sottocarica')
        .replace(/\bCharm\b/g, 'Fascino')
        .replace(/\bChatter\b/g, 'Schiamazzo')
        .replace(/\bClamp\b/g, 'Tenaglia')
        .replace(/\bClose Combat\b/g, 'Zuffa')
        .replace(/\bComet Punch\b/g, 'Cometapugno')
        .replace(/\bConfuse Ray\b/g, 'Stordiraggio')
        .replace(/\bConfusion\b/g, 'Confusione')
        .replace(/\bConstrict\b/g, 'Limitazione')
        .replace(/\bConversion\b/g, 'Conversione')
        .replace(/\bConversione 2\b/g, 'Conversione2')
        .replace(/\bCopycat\b/g, 'Copione')
        .replace(/\bCosmic Power\b/g, 'Cosmoforza')
        .replace(/\bCotton Spore\b/g, 'Cotonspora')
        .replace(/\bCounter\b/g, 'Contrattacco')
        .replace(/\bCovet\b/g, 'Supplica')
        .replace(/\bCrabhammer\b/g, 'Martellata')
        .replace(/\bCross Chop\b/g, 'Incrocolpo')
        .replace(/\bCross Poison\b/g, 'Velenocroce')
        .replace(/\bCrunch\b/g, 'Sgranocchio')
        .replace(/\bCrush Claw\b/g, 'Tritartigli')
        .replace(/\bCrush Grip\b/g, 'Sbriciolmano')
        .replace(/\bForest['’]s Curse\b/g, 'Boscomalocchio')
        // .replace(/\bFoRiposo['’]s Curse\b/g, 'Boscomalocchio')
        // .replace(/\bFoRiposo['’]s Maledizione\b/g, 'Boscomalocchio')
        .replace(/\bCurse\b/g, 'Maledizione')
        .replace(/\bFury Cutter\b/g, 'Tagliofuria')
        .replace(/\bPsycho Cut\b/g, 'Psicotaglio')
        .replace(/\bSky Uppercut\b/g, 'Stramontante')
        .replace(/\bCut\b/g, 'Taglio')
        .replace(/\bDark Pulse\b/g, 'Neropulsar')
        .replace(/\bDark Void\b/g, 'Vuototetro')
        .replace(/\bDefense Curl\b/g, 'Ricciolscudo')
        .replace(/\bDefend Order\b/g, 'Comandoscudo')
        .replace(/\bDefog\b/g, 'Scacciabruma')
        .replace(/\bDestiny Bond\b/g, 'Destinobbligato')
        .replace(/\bDetect\b/g, 'Individua')
        .replace(/\bDig\b/g, 'Fossa')
        .replace(/\bDisable\b/g, 'Inibitore')
        .replace(/\bDive\b/g, 'Sub')
        .replace(/\bDizzy Punch\b/g, 'Stordipugno')
        .replace(/\bDoom Desire\b/g, 'Desiderio Fatale')
        .replace(/\bDouble Hit\b/g, 'Doppiosmash')
        .replace(/\bDouble Kick\b/g, 'Doppiocalcio')
        .replace(/\bDouble Team\b/g, 'Doppioteam')
        .replace(/\bDouble\-[Ee]dge\b/g, 'Sdoppiatore')
        .replace(/\bDouble Slap\b/g, 'Doppiasberla').replace(/\bDouble[Ss]lap\b/g, 'Doppiasberla')
        .replace(/\bDraco Meteor\b/g, 'Dragobolide')
        .replace(/\bDragon Claw\b/g, 'Dragartigli')
        .replace(/\bDragon Dance\b/g, 'Dragodanza')
        .replace(/\bDragon Pulse\b/g, 'Dragopulsar')
        .replace(/\bDragon Rage\b/g, 'Ira di Drago')
        .replace(/\bDragon Rush\b/g, 'Dragofuria')
        .replace(/\bDragon Breath\b/g, 'Dragospiro').replace(/\bDragon[Bb]reath\b/g, 'Dragospiro')
        .replace(/\bDrain Punch\b/g, 'Assorbipugno')
        .replace(/\bDream Eater\b/g, 'Mangiasogni')
        .replace(/\bDrill Peck\b/g, 'Perforbecco')
        .replace(/\bDynamic Punch\b/g, 'Dinamipugno').replace(/\bDynamic[Pp]unch\b/g, 'Dinamipugno')
        .replace(/\bEarth Power\b/g, 'Geoforza')
        .replace(/\bEarthquake\b/g, 'Terremoto')
        .replace(/\bEgg Bomb\b/g, 'Uovobomba')
        .replace(/\bEmbargo\b/g, 'Divieto')
        .replace(/\bEmber\b/g, 'Braciere')
        .replace(/\bEncore\b/g, 'Ripeti')
        .replace(/\bEndeavor\b/g, 'Rimonta')
        .replace(/\bEndure\b/g, 'Resistenza')
        .replace(/\bEnergy Ball\b/g, 'Energipalla')
        .replace(/\bSteam Eruption\b/g, 'Vaporscoppio')
        .replace(/\bEruption\b/g, 'Eruzione')
        .replace(/\bExplosion\b/g, 'Esplosione')
        .replace(/\bExtrasensory\b/g, 'Extrasenso')
        .replace(/\bExtreme Speed\b/g, 'Extrarapido').replace(/\bExtreme[Ss]peed\b/g, 'Extrarapido')
        .replace(/\bFacade\b/g, 'Facciata')
        .replace(/\bF[ae]int Attack\b/g, 'Finta')
        .replace(/\bFake Out\b/g, 'Bruciapelo')
        .replace(/\bFake Tears\b/g, 'Falselacrime')
        .replace(/\bFalse Swipe\b/g, 'Falsofinale')
        .replace(/\bFeather Dance\b/g, 'Danzadipiume').replace(/\bFeather[Dd]ance\b/g, 'Danzadipiume')
        .replace(/\bFeint\b/g, 'Fintoattacco')
        .replace(/\bFire Blast\b/g, 'Fuocobomba')
        .replace(/\bFire Fang\b/g, 'Rogodenti')
        .replace(/\bFire Punch\b/g, 'Fuocopugno')
        .replace(/\bFire Spin\b/g, 'Turbofuoco')
        .replace(/\bFissure\b/g, 'Abisso')
        .replace(/\bFlail\b/g, 'Flagello')
        .replace(/\bFlame Wheel\b/g, 'Ruotafuoco')
        .replace(/\bFlamethrower\b/g, 'Lanciafiamme')
        .replace(/\bFlare Blitz\b/g, 'Fuococarica')
        .replace(/\bFlash\b/g, 'Flash')
        .replace(/\bFlash Cannon\b/g, 'Cannonflash')
        .replace(/\bFlatter\b/g, 'Adulazione')
        .replace(/\bFling\b/g, 'Lancio')
        .replace(/\bFlying Press\b/g, 'Schiacciatuffo')
        .replace(/\bFly\b/g, 'Volo')
        .replace(/\bFocus Blast\b/g, 'Focalcolpo')
        .replace(/\bFocus Energy\b/g, 'Focalenergia')
        .replace(/\bFocus Punch\b/g, 'Centripugno')
        .replace(/\bFollow Me\b/g, 'Sonoqui')
        .replace(/\bForce Palm\b/g, 'Palmoforza')
        .replace(/\bForesight\b/g, 'Preveggenza')
        .replace(/\bFrenzy Plant\b/g, 'Radicalbero')
        .replace(/\bFrustration\b/g, 'Frustrazione')
        .replace(/\bFury Attack\b/g, 'Furia')
        .replace(/\bFury Swipes\b/g, 'Sfuriate')
        .replace(/\bFuture Sight\b/g, 'Divinazione')
        .replace(/\bGiga Drain\b/g, 'Gigassorbimento')
        .replace(/\bGiga Impact\b/g, 'Gigaimpatto')
        .replace(/\bGlare\b/g, 'Sguardo Feroce')
        .replace(/\bGrass Knot\b/g, 'Laccioerboso')
        .replace(/\bGrass Whistle\b/g, 'Meloderba').replace(/\bGrass[Ww]histle\b/g, 'Meloderba')
        .replace(/\bGravity\b/g, 'Gravit&agrave;')
        .replace(/\bGrowl\b/g, 'Ruggito')
        .replace(/\bGrowth\b/g, 'Crescita')
        .replace(/\bGrudge\b/g, 'Rancore')
        .replace(/\bGuard Swap\b/g, 'Barattoscudo')
        .replace(/\bGuillotine\b/g, 'Ghigliottina')
        .replace(/\bGunk Shot\b/g, 'Sporcolancio')
        .replace(/\bGust\b/g, 'Raffica')
        .replace(/\bGyro Ball\b/g, 'Vortexpalla')
        .replace(/\bHail\b/g, 'Grandine')
        .replace(/\bHammer Arm\b/g, 'Martelpugno')
        .replace(/\bHarden\b/g, 'Rafforzatore')
        .replace(/\bHaze\b/g, 'Nube')
        .replace(/\bHead Smash\b/g, 'Zuccata')
        .replace(/\bZen Headbutt\b/g, 'Cozzata Zen')
        .replace(/\bHeadbutt\b/g, 'Bottintesta')
        .replace(/\bHeal Bell\b/g, 'Rintoccasana')
        .replace(/\bHeal Order\b/g, 'Comandocura')
        .replace(/\bHealing Wish\b/g, 'Curardore')
        .replace(/\bHeart Swap\b/g, 'Cuorbaratto')
        .replace(/\bHeat Wave\b/g, 'Ondacalda')
        .replace(/\bHeavy Slam\b/g, 'Pesobomba')
        .replace(/\bHelping Hand\b/g, 'Altruismo')
        .replace(/\b(?:Hi|High) Jump Kick\b/g, 'Calcinvolo')
        .replace(/\bHidden Power\b/g, 'Introforza')
        .replace(/\bHone Claws\b/g, 'Unghiaguzze')
        .replace(/\bHorn Attack\b/g, 'Incornata')
        .replace(/\bHorn Drill\b/g, 'Perforcorno')
        .replace(/\bHowl\b/g, 'Gridodilotta')
        .replace(/\bHydro Cannon\b/g, 'Idrocannone')
        .replace(/\bHydro Pump\b/g, 'Idropompa')
        .replace(/\bHyper Beam\b/g, 'Iper Raggio')
        .replace(/\bHyper Fang\b/g, 'Iperzanna')
        .replace(/\bHyper Voice\b/g, 'Granvoce')
        .replace(/\bHypnosis\b/g, 'Ipnosi')
        .replace(/\bIce Ball\b/g, 'Palla Gelo')
        .replace(/\bIce Beam\b/g, 'Geloraggio')
        .replace(/\bIce Fang\b/g, 'Gelodenti')
        .replace(/\bIce Punch\b/g, 'Gelopugno')
        .replace(/\bIce Shard\b/g, 'Geloscheggia')
        .replace(/\bIcicle Spear\b/g, 'Gelolancia')
        .replace(/\bIcy Wind\b/g, 'Ventogelato')
        .replace(/\bImprison\b/g, 'Esclusiva')
        .replace(/\bIngrain\b/g, 'Radicamento')
        .replace(/\bIon Deluge\b/g, 'Pioggiaplasma')
        .replace(/\bIron Defense\b/g, 'Ferroscudo')
        .replace(/\bIron Head\b/g, 'Metaltestata')
        .replace(/\bIron Tail\b/g, 'Codacciaio')
        .replace(/\bJudgment\b/g, 'Giudizio')
        .replace(/\bJump Kick\b/g, 'Calciosalto')
        .replace(/\bKarate Chop\b/g, 'Colpokarate')
        .replace(/\bTelekinesis\b/g, 'Telecinesi')
        .replace(/\bKinesis\b/g, 'Cin&egrave;si')
        .replace(/\bKnock Off\b/g, 'Privazione')
        .replace(/\bLast Resort\b/g, 'Ultimascelta')
        .replace(/\bLava Plume\b/g, 'Lavasbuffo')
        .replace(/\bLeaf Blade\b/g, 'Fendifoglia')
        .replace(/\bLeaf Storm\b/g, 'Verdebufera')
        .replace(/\bLeech Life\b/g, 'Sanguisuga')
        .replace(/\bLeech Seed\b/g, 'Parassiseme')
        .replace(/\bLeer\b/g, 'Fulmisguardo')
        .replace(/\bLick\b/g, 'Leccata')
        .replace(/\bLight Screen\b/g, 'Schermoluce')
        .replace(/\bLock\-[Oo]n\b/g, 'Localizza')
        .replace(/\bLovely Kiss\b/g, 'Demonbacio')
        .replace(/\bLow Kick\b/g, 'Colpo Basso')
        .replace(/\bLucky Chant\b/g, 'Fortuncanto')
        .replace(/\bLunar Dance\b/g, 'Lunardanza')
        .replace(/\bLuster Purge\b/g, 'Abbagliante')
        .replace(/\bMach Punch\b/g, 'Pugnorapido')
        .replace(/\bMagic Coat\b/g, 'Magivelo')
        .replace(/\bMagical Leaf\b/g, 'Fogliamagica')
        .replace(/\bMagma Storm\b/g, 'Magmaclisma')
        .replace(/\bMagnet Bomb\b/g, 'Bombagnete')
        .replace(/\bMagnet Rise\b/g, 'Magnetascesa')
        .replace(/\bMagnitude\b/g, 'Magnitudo')
        .replace(/\bMe First\b/g, 'Precedenza')
        .replace(/\bMean Look\b/g, 'Malosguardo')
        .replace(/\bMeditate\b/g, 'Meditazione')
        .replace(/\bMega Drain\b/g, 'Megassorbimento')
        .replace(/\bMega Kick\b/g, 'Megacalcio')
        .replace(/\bMega Punch\b/g, 'Megapugno')
        .replace(/\bMegahorn\b/g, 'Megacorno')
        .replace(/\bMemento\b/g, 'Memento')
        .replace(/\bMetal Burst\b/g, 'Metalscoppio')
        .replace(/\bMetal Claw\b/g, 'Ferrartigli')
        .replace(/\bMetal Sound\b/g, 'Ferrostrido')
        .replace(/\bMeteor Mash\b/g, 'Meteorpugno')
        .replace(/\bMetronome\b/g, 'Metronomo')
        .replace(/\bMilk Drink\b/g, 'Buonlatte')
        .replace(/\bMimic\b/g, 'Mimica')
        .replace(/\bMind Reader\b/g, 'Leggimente')
        .replace(/\bMinimize\b/g, 'Minimizzato')
        .replace(/\bMiracle Eye\b/g, 'Miracolvista')
        .replace(/\bMirror Coat\b/g, 'Specchiovelo')
        .replace(/\bMirror Move\b/g, 'Speculmossa')
        .replace(/\bMirror Shot\b/g, 'Cristalcolpo')
        .replace(/\bMist Ball\b/g, 'Foschisfera')
        .replace(/\bMisty Terrain\b/g, 'Campo Nebbioso')
        .replace(/\bAromatic Mist\b/g, 'Nebularoma')
        .replace(/\bMist\b/g, 'Nebbia')
        .replace(/\bMoonlight\b/g, 'Lucelunare')
        .replace(/\bMorning Sun\b/g, 'Mattindoro')
        .replace(/\bMud Bomb\b/g, 'Pantanobomba')
        .replace(/\bMud Shot\b/g, 'Colpodifango')
        .replace(/\bMud Sport\b/g, 'Fangata')
        .replace(/\bMud\-[Ss]lap\b/g, 'Fangosberla')
        .replace(/\bMuddy Water\b/g, 'Fanghiglia')
        .replace(/\bNasty Plot\b/g, 'Congiura')
        .replace(/\bNatural Gift\b/g, 'Dononaturale')
        .replace(/\bNature Power\b/g, 'Naturforza')
        .replace(/\bNeedle Arm\b/g, 'Pugnospine')
        .replace(/\bNight Shade\b/g, 'Ombra Notturna')
        .replace(/\bNight Slash\b/g, 'Nottesferza')
        .replace(/\bNightmare\b/g, 'Incubo')
        .replace(/\bOctazooka\b/g, 'Octazooka')
        .replace(/\bOdor Sleuth\b/g, 'Segugio')
        .replace(/\bOminous Wind\b/g, 'Funestovento')
        .replace(/\bOutrage\b/g, 'Oltraggio')
        .replace(/\bOverheat\b/g, 'Vampata')
        .replace(/\bPain Split\b/g, 'Malcomune')
        .replace(/\bPay Day\b/g, 'Giornopaga')
        .replace(/\bPayback\b/g, 'Rivincita')
        .replace(/\bPeck\b/g, 'Beccata')
        .replace(/\bPerish Song\b/g, 'Ultimocanto')
        .replace(/\bPetal Dance\b/g, 'Petalodanza')
        .replace(/\bPin Missile\b/g, 'Missilspillo')
        .replace(/\bPluck\b/g, 'Spennata')
        .replace(/\bPoison Fang\b/g, 'Velenodenti')
        .replace(/\bPoison Gas\b/g, 'Velenogas')
        .replace(/\bPoison Jab\b/g, 'Velenpuntura')
        .replace(/\bPoison Sting\b/g, 'Velenospina')
        .replace(/\bPoison Tail\b/g, 'Velenocoda')
        .replace(/\bPoison Powder\b/g, 'Velenpolvere').replace(/\bPoison[Pp]owder\b/g, 'Velenpolvere')
        .replace(/\bPound\b/g, 'Botta')
        .replace(/\bPowder Snow\b/g, 'Polneve')
        .replace(/\bPower Gem\b/g, 'Gemmoforza')
        .replace(/\bPower Swap\b/g, 'Barattoforza')
        .replace(/\bPower Whip\b/g, 'Vigorcolpo')
        .replace(/\bPresent\b/g, 'Regalino')
        .replace(/\bProtect\b/g, 'Protezione')
        .replace(/\bPsybeam\b/g, 'Psicoraggio')
        .replace(/\bPsych Up\b/g, 'Psicamis&ugrave;')
        .replace(/\bPsychic\b/g, 'Psichico')
        .replace(/\bPsycho Boost\b/g, 'Psicoslancio')
        .replace(/\bPsycho Shift\b/g, 'Psicotrasfer')
        .replace(/\bPsyshock\b/g, 'Psicoshock')
        .replace(/\bPsywave\b/g, 'Psiconda')
        .replace(/\bPunishment\b/g, 'Punizione')
        .replace(/\bPursuit\b/g, 'Inseguimento')
        .replace(/\bQuick Attack\b/g, 'Attacco Rapido')
        .replace(/\bRage Powder\b/g, 'Polverabbia')
        .replace(/\bRage\b/g, 'Ira')
        .replace(/\bRain Dance\b/g, 'Pioggiadanza')
        .replace(/\bRapid Spin\b/g, 'Rapigiro')
        .replace(/\bRazor Leaf\b/g, 'Foglielama')
        .replace(/\bRazor Wind\b/g, 'Ventagliente')
        .replace(/\bRecover\b/g, 'Ripresa')
        .replace(/\bRecycle\b/g, 'Riciclo')
        .replace(/\bReflect Type\b/g, 'Riflettipo')
        .replace(/\bReflect\b/g, 'Riflesso')
        .replace(/\bRefresh\b/g, 'Rinfrescata')
        .replace(/\bRest\b/g, 'Riposo')
        .replace(/\bHeart Stamp\b/g, 'Cuorestampo')
        .replace(/\bReturn\b/g, 'Ritorno')
        .replace(/\bRevenge\b/g, 'Vendetta')
        .replace(/\bReversal\b/g, 'Contropiede')
        .replace(/\bRoar [Oo]f Time\b/g, 'Fragortempo')
        .replace(/\bBoato [Oo]f Time\b/g, 'Fragortempo')
        .replace(/\bUproar\b/g, 'Baraonda')
        .replace(/\bNoble Roar\b/g, 'Urlo')
        .replace(/\bRoar\b/g, 'Boato')
        .replace(/\bRock Blast\b/g, 'Cadutamassi')
        .replace(/\bRock Climb\b/g, 'Scalaroccia')
        .replace(/\bRock Polish\b/g, 'Lucidatura')
        .replace(/\bRock Slide\b/g, 'Frana')
        .replace(/\bRock Smash\b/g, 'Spaccaroccia')
        .replace(/\bRock Throw\b/g, 'Sassata')
        .replace(/\bRock Tomb\b/g, 'Rocciotomba')
        .replace(/\bRock Wrecker\b/g, 'Devastomasso')
        .replace(/\bRole Play\b/g, 'Giocodiruolo')
        .replace(/\bRolling Kick\b/g, 'Calciorullo')
        .replace(/\bRollout\b/g, 'Rotolamento')
        .replace(/\bRoost\b/g, 'Trespolo')
        .replace(/\bSacred Fire\b/g, 'Magifuoco')
        .replace(/\bSafeguard\b/g, 'Salvaguardia')
        .replace(/\bSand Tomb\b/g, 'Sabbiotomba')
        .replace(/\bSand[\- ]Attack\b/g, 'Turbosabbia')
        .replace(/\bSandstorm\b/g, 'Terrempesta')
        .replace(/\bScary Face\b/g, 'Visotruce')
        .replace(/\bScratch\b/g, 'Graffio')
        .replace(/\bScreech\b/g, 'Stridio')
        .replace(/\bSecret Power\b/g, 'Forzasegreta')
        .replace(/\bSeed Bomb\b/g, 'Semebomba')
        .replace(/\bSeed Flare\b/g, 'Infuriaseme')
        .replace(/\bSeismic Toss\b/g, 'Movimento Sismico')
        .replace(/\bSelf\-Destruct\b/g, 'Autodistruzione').replace(/\bSelf[Dd]estruct\b/g, 'Autodistruzione')
        .replace(/\bShadow Ball\b/g, 'Palla Ombra')
        .replace(/\bShadow Claw\b/g, 'Ombrartigli')
        .replace(/\bShadow Force\b/g, 'Oscurotuffo')
        .replace(/\bShadow Punch\b/g, 'Pugnodombra')
        .replace(/\bShadow Sneak\b/g, 'Furtivombra')
        .replace(/\bSharpen\b/g, 'Affilatore')
        .replace(/\bSheer Cold\b/g, 'Purogelo')
        .replace(/\bShock Wave\b/g, 'Ondashock')
        .replace(/\bSignal Beam\b/g, 'Segnoraggio')
        .replace(/\bSilver Wind\b/g, 'Ventargenteo')
        .replace(/\bSing\b/g, 'Canto')
        .replace(/\bSketch\b/g, 'Schizzo')
        .replace(/\bSkill Swap\b/g, 'Baratto')
        .replace(/\bSkull Bash\b/g, 'Capocciata')
        .replace(/\bSky Attack\b/g, 'Aeroattacco')
        .replace(/\bSlack Off\b/g, 'Pigro')
        .replace(/\bSlam\b/g, 'Schianto')
        .replace(/\bSlash\b/g, 'Lacerazione')
        .replace(/\bSleep Powder\b/g, 'Sonnifero')
        .replace(/\bSleep Talk\b/g, 'Sonnolalia')
        .replace(/\bSludge Bomb\b/g, 'Fangobomba')
        .replace(/\bSludge Wave\b/g, 'Fangonda')
        .replace(/\bSludge\b/g, 'Fango')
        .replace(/\bSmelling Salts\b/g, 'Maniereforti').replace(/\bSmelling[Ss]alt\b/g, 'Maniereforti')
        .replace(/\bSmokescreen\b/g, 'Muro di Fumo')
        .replace(/\bSnatch\b/g, 'Scippo')
        .replace(/\bSnore\b/g, 'Russare')
        .replace(/\bSoft\-Boiled\b/g, 'Covauova').replace(/\bSoftboiled\b/g, 'Covauova')
        .replace(/\bSolar Beam\b/g, 'Solarraggio').replace(/\bSolar[Bb]eam\b/g, 'Solarraggio')
        .replace(/\bSonic Boom\b/g, 'Sonicboom').replace(/\bSonic[Bb]oom\b/g, 'Sonicboom')
        .replace(/\bSpacial Rend\b/g, 'Fendispazio')
        .replace(/\bSpark\b/g, 'Scintilla')
        .replace(/\bSpider Web\b/g, 'Ragnatela')
        .replace(/\bSpike Cannon\b/g, 'Sparalance')
        .replace(/\bToxic Spikes\b/g, 'Fielepunte')
        .replace(/\bSpikes\b/g, 'Punte')
        .replace(/\bSpit Up\b/g, 'Sfoghenergia')
        .replace(/\bSpite\b/g, 'Dispetto')
        .replace(/\bStun Spore\b/g, 'Paralizzante')
        .replace(/\bSpore\b/g, 'Spora')
        .replace(/\bStealth Rock\b/g, 'Levitoroccia')
        .replace(/\bSteel Wing\b/g, 'Alacciaio')
        .replace(/\bStockpile\b/g, 'Accumulo')
        .replace(/\bStomp\b/g, 'Pestone')
        .replace(/\bStone Edge\b/g, 'Pietrataglio')
        .replace(/\bStrength\b/g, 'Forza')
        .replace(/\bString Shot\b/g, 'Millebave')
        .replace(/\bStruggle Bug\b/g, 'Entomoblocco')
        .replace(/\bStruggle\b/g, 'Scontro')
        .replace(/\bSubmission\b/g, 'Sottomissione')
        .replace(/\bSubstitute\b/g, 'Sostituto')
        .replace(/\bSucker Punch\b/g, 'Sbigoattacco')
        .replace(/\bSunny Day\b/g, 'Giornodisole')
        .replace(/\bSuper Fang\b/g, 'Superzanna')
        .replace(/\bSuperpower\b/g, 'Troppoforte')
        .replace(/\bSupersonic\b/g, 'Supersuono')
        .replace(/\bSurf\b/g, 'Surf')
        .replace(/\bSwagger\b/g, 'Bullo')
        .replace(/\bSwallow\b/g, 'Introenergia')
        .replace(/\bSweet Kiss\b/g, 'Dolcebacio')
        .replace(/\bSweet Scent\b/g, 'Profumino')
        .replace(/\bSwift\b/g, 'Comete')
        .replace(/\bSwitcheroo\b/g, 'Rapidscambio')
        .replace(/\bSwords Dance\b/g, 'Danzaspada')
        .replace(/\bSynthesis\b/g, 'Sintesi')
        .replace(/\bVolt Tackle\b/g, 'Locomovolt')
        .replace(/\bTackle\b/g, 'Azione')
        .replace(/\bTail Glow\b/g, 'Codadiluce')
        .replace(/\bTail Whip\b/g, 'Colpocoda')
        .replace(/\bTailwind\b/g, 'Ventoincoda')
        .replace(/\bTake Down\b/g, 'Riduttore')
        .replace(/\bTaunt\b/g, 'Provocazione')
        .replace(/\bTeeter Dance\b/g, 'Strampadanza')
        .replace(/\bTeleport\b/g, 'Teletrasporto')
        .replace(/\bThief\b/g, 'Furto')
        .replace(/\bThrash\b/g, 'Colpo')
        .replace(/\bThunder Fang\b/g, 'Fulmindenti')
        .replace(/\bThunder Wave\b/g, 'Tuononda')
        .replace(/\bThunderbolt\b/g, 'Fulmine')
        .replace(/\bThunder Punch\b/g, 'Tuonopugno').replace(/\bThunder[Pp]unch\b/g, 'Tuonopugno')
        .replace(/\bThunder Shock\b/g, 'Tuonoshock').replace(/\bThunder[Ss]hock\b/g, 'Tuonoshock')
        .replace(/\bThunder\b/g, 'Tuono')
        .replace(/\bTickle\b/g, 'Solletico')
        .replace(/\bTorment\b/g, 'Attaccalite')
        .replace(/\bToxic\b/g, 'Tossina')
        .replace(/\bTransform\b/g, 'Trasformazione')
        .replace(/\bTri Attack\b/g, 'Tripletta')
        .replace(/\bPower Trick\b/g, 'Ingannoforza')
        .replace(/\bTrick Room\b/g, 'Distortozona')
        .replace(/\bTrick\-or\-Treat\b/g, 'Halloween')
        .replace(/\bTrick\b/g, 'Raggiro')
        .replace(/\bTriple Kick\b/g, 'Triplocalcio')
        .replace(/\bTrump Card\b/g, 'Asso')
        .replace(/\bTwineedle\b/g, 'Doppio Ago')
        .replace(/\bTwister\b/g, 'Tornado')
        .replace(/\bU\-[Tt]urn\b/g, 'Retromarcia')
        .replace(/\bVacuum Wave\b/g, 'Vuotonda')
        .replace(/\bVi[cs]e Grip\b/g, 'Presa').replace(/\bVice[Gg]rip\b/g, 'Presa')
        .replace(/\bVine Whip\b/g, 'Frustata')
        .replace(/\bVital Throw\b/g, 'Vitaltiro')
        .replace(/\bWake\-[Uu]p Slap\b/g, 'Svegliopacca')
        .replace(/\bWater Gun\b/g, 'Pistolacqua')
        .replace(/\bWater Pulse\b/g, 'Idropulsar')
        .replace(/\bWater Sport\b/g, 'Docciascudo')
        .replace(/\bWater Spout\b/g, 'Zampillo')
        .replace(/\bWaterfall\b/g, 'Cascata')
        .replace(/\bWeather Ball\b/g, 'Palla Clima')
        .replace(/\bWide Guard\b/g, 'Bodyguard')
        .replace(/\bWhirlpool\b/g, 'Mulinello')
        .replace(/\bWhirlwind\b/g, 'Turbine')
        .replace(/\bWill\-O\-Wisp\b/g, 'Fuocofatuo')
        .replace(/\bWing Attack\b/g, "Attacco d'Ala")
        .replace(/\bWish\b/g, 'Desiderio')
        .replace(/\bWithdraw\b/g, 'Ritirata')
        .replace(/\bWood Hammer\b/g, 'Mazzuolegno')
        .replace(/\bWorry Seed\b/g, 'Affannoseme')
        .replace(/\bWrap\b/g, 'Avvolgibotta')
        .replace(/\bWring Out\b/g, 'Strizzata')
        .replace(/\bX\-[Ss]cissor\b/g, 'Forbice X')
        .replace(/\bYawn\b/g, 'Sbadiglio')
        .replace(/\bZap Cannon\b/g, 'Elettrocannone')
        .replace(/\bGuard Split\b/g, 'Paridifesa')
        .replace(/\bPower Split\b/g, 'Pariattacco')
        .replace(/\bWonder Room\b/g, 'Mirabilzona')
        .replace(/\bVenoshock\b/g, 'Velenoshock')
        .replace(/\bAutotomize\b/g, 'Sganciapesi')
        .replace(/\bMagic Room\b/g, 'Magicozona')
        .replace(/\bSmack Down\b/g, 'Abbattimento')
        .replace(/\bStorm Throw\b/g, 'Tempestretta')
        .replace(/\bFlame Burst\b/g, 'Pirolancio')
        .replace(/\bQuiver Dance\b/g, 'Eledanza')
        .replace(/\bSynchronoise\b/g, 'Sincrumore')
        .replace(/\bElectro Ball\b/g, 'Energisfera')
        .replace(/\bSoak\b/g, 'Inondazione')
        .replace(/\bCoil\b/g, 'Arrotola')
        .replace(/\bLow Sweep\b/g, 'Calciobasso')
        .replace(/\bFoul Play\b/g, 'Ripicca')
        .replace(/\bSimple Beam\b/g, 'Ondisinvolta')
        .replace(/\bEntrainment\b/g, 'Saltamicizia')
        .replace(/\bAfter You\b/g, 'Cortesia')
        .replace(/\bRound\b/g, 'Coro')
        .replace(/\bEchoed Voice\b/g, 'Echeggiavoce')
        .replace(/\bChip Away\b/g, 'Insidia')
        .replace(/\bClear Smog\b/g, 'Pulifumo')
        .replace(/\bStored Power\b/g, 'Veicolaforza')
        .replace(/\bQuick Guard\b/g, 'Anticipo')
        .replace(/\bAlly Switch\b/g, 'Cambiaposto')
        .replace(/\bScald\b/g, 'Idrovampata')
        .replace(/\bShell Smash\b/g, 'Gettaguscio')
        .replace(/\bHeal Pulse\b/g, 'Curapulsar')
        .replace(/\bHex\b/g, 'Sciagura')
        .replace(/\bSky Drop\b/g, 'Cadutalibera')
        .replace(/\bShift Gear\b/g, 'Cambiomarcia')
        .replace(/\bCircle Throw\b/g, 'Ribaltiro')
        .replace(/\bIncinerate\b/g, 'Bruciatutto')
        .replace(/\bQuash\b/g, 'Spintone')
        .replace(/\bAcrobatics\b/g, 'Acrobazia')
        .replace(/\bRetaliate\b/g, 'Nemesi')
        .replace(/\bFinal Gambit\b/g, 'Azzardo')
        .replace(/\bBestow\b/g, 'Cediregalo')
        .replace(/\bInferno\b/g, 'Marchiatura')
        .replace(/\bWater Pledge\b/g, 'Acquapatto')
        .replace(/\bFire Pledge\b/g, 'Fiammapatto')
        .replace(/\bGrass Pledge\b/g, 'Erbapatto')
        .replace(/\bVolt Switch\b/g, 'Invertivolt')
        .replace(/\bBulldoze\b/g, 'Battiterra')
        .replace(/\bFrost Breath\b/g, 'Alitogelido')
        .replace(/\bDragon Tail\b/g, 'Codadrago')
        .replace(/\bWork Up\b/g, 'Cuordileone')
        .replace(/\bElectroweb\b/g, 'Elettrotela')
        .replace(/\bDrill Run\b/g, 'Giravvita')
        .replace(/\bDual Chop\b/g, 'Doppiocolpo')
        .replace(/\bHorn Leech\b/g, 'Legnicorno')
        .replace(/\bSacred Sword\b/g, 'Spadasolenne')
        .replace(/\bRazor Shell\b/g, 'Conchilama')
        .replace(/\bHeat Crash\b/g, 'Marchiafuoco')
        .replace(/\bLeaf Tornado\b/g, 'Vorticerba')
        .replace(/\bSteamroller\b/g, 'Rulloduro')
        .replace(/\bCotton Guard\b/g, 'Cotonscudo')
        .replace(/\bNight Daze\b/g, 'Urtoscuro')
        .replace(/\bPsystrike\b/g, 'Psicobotta')
        .replace(/\bTail Slap\b/g, 'Spazzasberla')
        .replace(/\bHurricane\b/g, 'Tifone')
        .replace(/\bGear Grind\b/g, 'Ingracolpo')
        .replace(/\bSearing Shot\b/g, 'Sparafuoco')
        .replace(/\bTechno Blast\b/g, 'Tecnobotto')
        .replace(/\bRelic Song\b/g, 'Cantoantico')
        .replace(/\bSecret Sword\b/g, 'Spadamistica')
        .replace(/\bGlaciate\b/g, 'Gelamondo')
        .replace(/\bBolt Strike\b/g, 'Lucesiluro')
        .replace(/\bBlue Flare\b/g, 'Fuocoblu')
        .replace(/\bFiery Dance\b/g, 'Voldifuoco')
        .replace(/\bFreeze Shock\b/g, 'Elettrogelo')
        .replace(/\bIce Burn\b/g, 'Vampagelida')
        .replace(/\bSnarl\b/g, 'Urlorabbia')
        .replace(/\bIcicle Crash\b/g, 'Scagliagelo')
        .replace(/\bV\-[Cc]reate\b/g, 'Generatore V')
        .replace(/\bFusion Flare\b/g, 'Incrofiamma')
        .replace(/\bFusion Bolt\b/g, 'Incrotuono')
        .replace(/\bBaby\-Doll Eyes\b/g, 'Occhioni Teneri')
        .replace(/\bBoomburst\b/g, 'Ondaboato')
        .replace(/\bConfide\b/g, 'Confidenza')
        .replace(/\bCrafty Shield\b/g, 'Truccodifesa')
        .replace(/\bDazzling Gleam\b/g, 'Magibrillio')
        .replace(/\bDisarming Voice\b/g, 'Incantavoce')
        .replace(/\bDraining Kiss\b/g, 'Assorbibacio')
        .replace(/\bEerie Impulse\b/g, 'Elettromistero')
        .replace(/\bElectric Terrain\b/g, 'Campo Elettrico')
        .replace(/\bElectrify\b/g, 'Elettrocontagio')
        .replace(/\bFairy Lock\b/g, 'Blocco Fatato')
        .replace(/\bFairy Wind\b/g, 'Vento di Fata')
        .replace(/\bFell Stinger\b/g, 'Pungiglione')
        .replace(/\bFlower Shield\b/g, 'Fiordifesa')
        .replace(/\bFreeze\-Dry\b/g, 'Liofilizzazione')
        .replace(/\bGeomancy\b/g, 'Geocontrollo')
        .replace(/\bGrassy Terrain\b/g, 'Campo Erboso')
        .replace(/\bInfestation\b/g, 'Assillo')
        .replace(/\bKing['’’]s Shield\b/g, 'Scudo Reale')
        .replace(/\bLand['’]s Wrath\b/g, 'Forza Tellurica')
        .replace(/\bMoonblast\b/g, 'Forza Lunare')
        .replace(/\bMystical Fire\b/g, 'Magifiamma')
        .replace(/\bNuzzle\b/g, 'Elettrococcola')
        .replace(/\bOblivion Wing\b/g, 'Ali del Fato')
        .replace(/\bParting Shot\b/g, 'Monito')
        .replace(/\bPhantom Force\b/g, 'Spettrotuffo')
        .replace(/\bPlay Nice\b/g, 'Simpatia')
        .replace(/\bPlay Rough\b/g, 'Carineria')
        .replace(/\bPowder\b/g, 'Pulviscoppio')
        .replace(/\bPower\-Up Punch\b/g, 'Crescipugno')
        .replace(/\bRototiller\b/g, 'Aracampo')
        .replace(/\bSpiky Shield\b/g, 'Agodifesa')
        .replace(/\bSticky Web\b/g, 'Rete Vischiosa')
        .replace(/\bTopsy\-Turvy\b/g, 'Sottosopra')
        .replace(/\bVenom Drench\b/g, 'Velenotrappola')
        .replace(/\bWater Shuriken\b/g, 'Acqualame')
        .replace(/\bBelch\b/g, 'Rutto')
        .replace(/\bHold Back\b/g, 'Riguardo')
        .replace(/\bDiamond Storm\b/g, 'Diamantempesta')
        .replace(/\bCelebrate\b/g, 'Auguri')
        .replace(/\bMagnetic Flux\b/g, 'Controllo Polare')
        .replace(/\bHappy Hour\b/g, 'Cuccagna')
        .replace(/\bHold Hands\b/g, 'Mano nella Mano')
        .replace(/\bHyperspace Hole\b/g, 'Forodimensionale')
        .replace(/\bThousand Arrows\b/g, 'Mille Frecce')
        .replace(/\bThousand Waves\b/g, 'Mille Onde')
        .replace(/\bLight of Ruin\b/g, 'Luce Nefasta')
        .replace(/\bOrigin Pulse\b/g, 'Primopulsar')
        .replace(/\bPrecipice Blades\b/g, 'Spade Telluriche')
        .replace(/\bDragon Ascent\b/g, 'Ascesa del Drago')
        .replace(/\bHyperspace Fury\b/g, 'Urtodimensionale')
        .replace(/\bBreakneck Blitz\b/g, 'Carica Travolgente')
        .replace(/\bAll\-Out Pummeling\b/g, 'Iperscarica Furiosa')
        .replace(/\bSupersonic Skystrike\b/g, 'Picchiata Devastante')
        .replace(/\bAcid Downpour\b/g, 'Acidiluvio Corrosivo')
        .replace(/\bTectonic Rage\b/g, 'Furore della Terra')
        .replace(/\bContinental Crush\b/g, 'Gigamacigno Polverizzante')
        .replace(/\bSavage Spin\-Out\b/g, 'Bozzolo Fatale')
        .replace(/\bNever\-Ending Nightmare\b/g, 'Abbraccio Spettrale')
        .replace(/\bCorkscrew Crash\b/g, 'Spirale Perforante')
        .replace(/\bInferno Overdrive\b/g, 'Fiammobomba Detonante')
        .replace(/\bHydro Vortex\b/g, 'Idrovortice Abissale')
        .replace(/\bBloom Doom\b/g, 'Floriscoppio Sfolgorante')
        .replace(/\bGigavolt Havoc\b/g, 'Gigascarica Folgorante')
        .replace(/\bShattered Psyche\b/g, 'Impatto Psicocinetico')
        .replace(/\bSubzero Slammer\b/g, 'Criodistruzione Polare')
        .replace(/\bDevastating Drake\b/g, 'Dragoschianto Finale')
        .replace(/\bBlack Hole Eclipse\b/g, 'Buco Nero del Non Ritorno')
        .replace(/\bTwinkle Tackle\b/g, 'Astroimpatto Fatato')
        .replace(/\bCatastropika\b/g, 'Super Pikaboom')
        .replace(/\bShore Up\b/g, 'Sabbiaccumulo')
        .replace(/\bFirst Impression\b/g, 'Schermaglia')
        .replace(/\bBaneful Bunker\b/g, 'Fortino')
        .replace(/\bSpirit Shackle\b/g, "Cucitura d'Ombra")
        .replace(/\bDarkest Lariat\b/g, 'Braccioteso')
        .replace(/\bSparkling Aria\b/g, 'Canto Effimero')
        .replace(/\bIce Hammer\b/g, 'Martelgelo')
        .replace(/\bFloral Healing\b/g, 'Cura Floreale')
        .replace(/\bHigh Horsepower\b/g, 'Forza Equina')
        .replace(/\bStrength Sap\b/g, 'Assorbiforza')
        .replace(/\bSolar Blade\b/g, 'Lama Solare')
        .replace(/\bLeafage\b/g, 'Fogliame')
        .replace(/\bSpotlight\b/g, 'Riflettore')
        .replace(/\bToxic Thread\b/g, 'Velenotela')
        .replace(/\bLaser Focus\b/g, 'Concentrazione')
        .replace(/\bGear Up\b/g, 'Marciainpi&ugrave;')
        .replace(/\bThroat Chop\b/g, 'Colpo Infernale')
        .replace(/\bPollen Puff\b/g, 'Sferapolline')
        .replace(/\bAnchor Shot\b/g, "Colpo d'Ancora")
        .replace(/\bPsychic Terrain\b/g, 'Campo Psichico')
        .replace(/\bLunge\b/g, 'Assalto')
        .replace(/\bFire Lash\b/g, 'Frusta di Fuoco')
        .replace(/\bPower Trip\b/g, 'Tracotanza')
        .replace(/\bBurn Up\b/g, 'Ultima Fiamma')
        .replace(/\bSpeed Swap\b/g, 'Velociscambio')
        .replace(/\bSmart Strike\b/g, 'Sottilcorno')
        .replace(/\bPurify\b/g, 'Purificazione')
        .replace(/\bRevelation Dance\b/g, 'Mutadanza')
        .replace(/\bCore Enforcer\b/g, 'Nucleocastigo')
        .replace(/\bTrop Kick\b/g, 'Tropicalcio')
        .replace(/\bInstruct\b/g, 'Imposizione')
        .replace(/\bBeak Blast\b/g, 'Cannonbecco')
        .replace(/\bClanging Scales\b/g, 'Clamorsquame')
        .replace(/\bDragon Hammer\b/g, 'Marteldrago')
        .replace(/\bBrutal Swing\b/g, 'Vorticolpo')
        .replace(/\bAurora Veil\b/g, 'Velaurora')
        .replace(/\bSinister Arrow Raid\b/g, 'Dardoassalto Spettrale')
        .replace(/\bMalicious Moonsault\b/g, 'Iperschianto delle Tenebre')
        .replace(/\bOceanic Operetta\b/g, 'Sinfonia del Mare')
        .replace(/\bGuardian of Alola\b/g, 'Collera del Guardiano')
        .replace(/\bSoul\-Stealing 7\-Star Strike\b/g, 'Colpo Eptastellare Rubanima')
        .replace(/\bStoked Sparksurfer\b/g, 'Elettrosurf Folgorante')
        .replace(/\bPulverizing Pancake\b/g, 'Adesso Faccio sul Serio')
        .replace(/\bExtreme Evoboost\b/g, 'Potenziamento Eevolutivo')
        .replace(/\bGenesis Supernova\b/g, 'Supernova delle Origini')
        .replace(/\bShell Trap\b/g, 'Gusciotrappola')
        .replace(/\bFleur Cannon\b/g, 'Cannonfiore')
        .replace(/\bPsychic Fangs\b/g, 'Psicozanna')
        .replace(/\bStomping Tantrum\b/g, 'Battipiedi')
        .replace(/\bShadow Bone\b/g, 'Ossotetro')
        .replace(/\bAccelerock\b/g, 'Rocciarapida')
        .replace(/\bLiquidation\b/g, 'Idrobreccia')
        .replace(/\bPrismatic Laser\b/g, 'Prismalaser')
        .replace(/\bSpectral Thief\b/g, 'Ombrafurto')
        .replace(/\bSunsteel Strike\b/g, 'Astrocarica')
        .replace(/\bMoongeist Beam\b/g, "Raggio d'Ombra")
        .replace(/\bTearful Look\b/g, 'Occhionilucidi')
        .replace(/\bZing Zap\b/g, 'Elettropizzico')
        .replace(/\bNature['’]s Madness\b/g, 'Ira della Natura')
        .replace(/\bMulti\-Attack\b/g, 'Multiattacco')
        .replace(/\b10,000,000 Volt Thunderbolt\b/g, 'Iperfulmine')
        .replace(/\bMind Blown\b/g, 'Sbalorditesta')
        .replace(/\bPhoton Geyser\b/g, 'Geyser Fotonico')
        .replace(/\bPlasma Fists\b/g, 'Pugni Plasma')
        .replace(/\bDouble Iron Bash\b/g, 'Pugni Corazzati')
        .replace(/\bClangorous Soulblaze\b/g, 'Dracofonia Divampante')
        .replace(/\bSplintered Stormshards\b/g, 'Litotempesta Radiale')
        .replace(/\bLet's Snuggle Forever\b/g, 'Dolcesacco di Botte')
        .replace(/\bMenacing Moonraze Maelstrom\b/g, 'Deflagrazione Lunare')
        .replace(/\bSearing Sunraze Smashh\b/g, 'Supercollisione Solare')
        .replace(/\bLight That Burns the Sky\b/g, 'Fotodistruzione Apocalittica')

        .replace(/\bFloaty Fall\b/g, 'Piombaflap')
        .replace(/\bPika Papow\b/g, 'Pikasaetta')
        .replace(/\bSurfasplash\b/g, 'Splishy Splash')
        .replace(/\bZippy Zap\b/g, 'Sprintaboom')
        .replace(/\bBouncy Bubble\b/g, 'Bollaslurp')
        .replace(/\bBuzzy Buzz\b/g, 'Elettrozap')
        .replace(/\bSizzly Slide\b/g, 'Fiammabam')
        .replace(/\bGlitzy Glow\b/g, 'Auraswoosh')
        .replace(/\bBaddy Bad\b/g, 'Zona Buiabuia')
        .replace(/\bSappy Seed\b/g, 'Bombafrush')
        .replace(/\bFreezy Frost\b/g, 'Scricchiagelo')
        .replace(/\bSparkly Swirl\b/g, 'Sbrilluccibufera')
        .replace(/\bVeevee Volley\b/g, 'Eeveempatto')

        .replace(/\bMax Guard\b/g, 'Dynabarriera')
        .replace(/\bDynamax Cannon\b/g, 'Cannone Dynamax')
        .replace(/\bSnipe Shot\b/g, 'Tiromirato')
        .replace(/\bJaw Lock\b/g, 'Morsostretto')
        .replace(/\bStuff Cheeks\b/g, 'Riempiguance')
        .replace(/\bNo Retreat\b/g, 'Spalle al Muro')
        .replace(/\bTar Shot\b/g, 'Colpocatrame')
        .replace(/\bMagic Powder\b/g, 'Magipolvere')
        .replace(/\bMagic Pulviscoppio\b/g, 'Magipolvere')
        .replace(/\bDragon Darts\b/g, 'Dragofrecce')
        .replace(/\bTeatime\b/g, 'Ora del T&egrave;')
        .replace(/\bOctolock\b/g, 'Tentacolock')
        .replace(/\bBolt Beak\b/g, 'Beccoshock')
        .replace(/\bFishious Rend\b/g, 'Branchiomorso')
        .replace(/\bCourt Change\b/g, 'Cambiocampo')
        .replace(/\bMax Flare\b/g, 'Dynafiammata')
        .replace(/\bMax Flutterby\b/g, 'Dynainsetto')
        .replace(/\bMax Lightning\b/g, 'Dynasaetta')
        .replace(/\bMax Strike\b/g, 'Dynattacco')
        .replace(/\bMax Knuckle\b/g, 'Dynapugno')
        .replace(/\bMax Phantasm\b/g, 'Dynavuoto')
        .replace(/\bMax Hailstorm\b/g, 'Dynagelo')
        .replace(/\bMax Grandinestorm\b/g, 'Dynagelo')
        .replace(/\bMax Ooze\b/g, 'Dynacorrosione')
        .replace(/\bMax Geyser\b/g, 'Dynaflusso')
        .replace(/\bMax Airstream\b/g, 'Dynajet')
        .replace(/\bMax Starfall\b/g, 'Dynafata')
        .replace(/\bMax Wyrmwind\b/g, 'Dynadragone')
        .replace(/\bMax Mindstorm\b/g, 'Dynapsiche')
        .replace(/\bMax Rockfall\b/g, 'Dynamacigno')
        .replace(/\bMax Quake\b/g, 'Dynasisma')
        .replace(/\bMax Darkness\b/g, 'Dynatenebre')
        .replace(/\bMax Overgrowth\b/g, 'Dynaflora')
        .replace(/\bMax Steelspike\b/g, 'Dynametallo')
        .replace(/\bClangorous Soul\b/g, 'Dracofonia')
        .replace(/\bBody Press\b/g, 'Schiacciacorpo')
        .replace(/\bDecorate\b/g, 'Decorazione')
        .replace(/\bDrum Beating\b/g, 'Tamburattacco')
        .replace(/\bSnap Trap\b/g, 'Tagliola')
        .replace(/\bPyro Ball\b/g, 'Palla Infuocata')
        .replace(/\bBehemoth Blade\b/g, 'Taglio Maestoso')
        .replace(/\bBehemoth Bash\b/g, 'Colpo Maestoso')
        .replace(/\bAura Wheel\b/g, "Ruota d'Aura")
        .replace(/\bBreaking Swipe\b/g, 'Vastoimpatto')
        .replace(/\bBranch Poke\b/g, 'Ramostoccata')
        .replace(/\bOverdrive\b/g, 'Overdrive')
        .replace(/\bApple Acido\b/g, 'Acido Malico')
        .replace(/\bApple Acid\b/g, 'Acido Malico')
        .replace(/\bGrav Apple\b/g, 'Forza G')
        .replace(/\bSpirit Break\b/g, 'Frantumanima')
        .replace(/\bStrange Steam\b/g, 'Vapore Incantato')
        .replace(/\bLife Dew\b/g, 'Goccia Vitale')
        .replace(/\bObstruct\b/g, 'Sbarramento')
        .replace(/\bFalse Surrender\b/g, 'Supplicolpo')
        .replace(/\bMeteor Assault\b/g, 'Sfolgorassalto')
        .replace(/\bEternabeam\b/g, 'Raggio Infinito')
        .replace(/\bSteel Beam\b/g, "Raggio d'Acciaio")
        .replace(/\bExpanding Force\b/g, 'Vastenergia')
        .replace(/\bSteel Roller\b/g, 'Ferrorullo')
        .replace(/\bScale Shot\b/g, 'Squamacolpo')
        .replace(/\bMeteor Beam\b/g, 'Raggiometeora')
        .replace(/\bShell Side Arm\b/g, 'Armaguscio')
        .replace(/\bMisty Explosion\b/g, 'Nebbioscoppio')
        .replace(/\bMisty Esplosione\b/g, 'Nebbioscoppio')
        .replace(/\bNebbiay Esplosione\b/g, 'Nebbioscoppio')
        .replace(/\bGrassy Glide\b/g, 'Erboscivolata')
        .replace(/\bRising Voltage\b/g, 'Elettroimpennata')
        // .replace(/\bRiCanto Voltage\b/g, 'Elettroimpennata')
        .replace(/\bTerrain Pulse\b/g, 'Campopulsar')
        .replace(/\bSkitter Smack\b/g, 'Strisciacolpo')
        .replace(/\bBurning Jealousy\b/g, 'Fiamminvidia')
        .replace(/\bLash Out\b/g, 'Sfogarabbia')
        // .replace(/\bPoltergeist\b/g, 'Poltergeist')
        .replace(/\bCorrosive Gas\b/g, 'Gas Corrosivo')
        // .replace(/\bCoaching\b/g, 'Coaching')
        .replace(/\bFlip Turn\b/g, 'Virata')
        .replace(/\bTriple Axel\b/g, 'Triplo Axel')
        .replace(/\bDual Wingbeat\b/g, 'Doppia Ala')
        .replace(/\bScorching Sands\b/g, 'Sabbiardente')
        .replace(/\bJungle Healing\b/g, 'Giunglacura')
        .replace(/\bWicked Blow\b/g, 'Pugnotenebra')
        .replace(/\bSurging Strikes\b/g, 'Idroraffica')
        .replace(/\bFreezing Glare\b/g, 'Sguardo Gelido').replace(/\bFreezing Sguardo Feroce\b/g, 'Sguardo Gelido')
        .replace(/\bThunderous Kick\b/g, 'Calcio Tonante')
        // .replace(/Tuonoous Kick/g, 'Calcio Tonante')
        .replace(/\bFiery Wrath\b/g, 'Furia Ardente')
        .replace(/\bEerie Spell\b/g, 'Inquietantesimo')
        .replace(/\bThunder Cage\b/g, 'Elettrogabbia').replace(/\bTuono Cage\b/g, 'Elettrogabbia')
        .replace(/\bDragon Energy\b/g, 'Dragoenergia')
        .replace(/\bGlacial Lance\b/g, 'Lancia Glaciale')
        .replace(/\bAstral Barrage\b/g, 'Schegge Astrali').replace(/\bAstral Attacco Pioggia\b/g, 'Schegge Astrali').replace(/\bAstral Sferattacco\b/g, 'Schegge Astrali')

        .replace(/\bDire Claw\b/g, 'Artigli Fatali')
        .replace(/\bPsyshield Bash\b/g, 'Barrierassalto')
        .replace(/\bPower Shift\b/g, 'Scambioforza')
        .replace(/\bStone Axe\b/g, 'Rocciascure')
        .replace(/\bSpringtide Storm\b/g, 'Tempesta Zefirea')
        .replace(/\bMystical Power\b/g, 'Forza Mistica')
        .replace(/\bRaging Fury\b/g, 'Ira Furente')
        .replace(/\bWave Crash\b/g, 'Ondaschianto')
        .replace(/\bChloroblast\b/g, 'Clorofillaser')
        .replace(/\bMountain Gale\b/g, 'Soffio d\'Iceberg')
        .replace(/\bVictory Dance\b/g, 'Danzavittoria')
        .replace(/\bHeadlong Rush\b/g, 'Scontro Frontale')
        .replace(/\bBarb Barrage\b/g, 'Mille Fielespine').replace(/\bBarb Attacco Pioggia\b/g, 'Mille Fielespine').replace(/\bBarb Sferattacco\b/g, 'Mille Fielespine')
        .replace(/\bEsper Wing\b/g, 'Ali d\'Aura')
        .replace(/\bBitter Malice\b/g, 'Livore')
        .replace(/\bShelter\b/g, 'Barricata')
        .replace(/\bTriple Arrows\b/g, 'Triplodardo')
        .replace(/\bInfernal Parade\b/g, 'Corteo Spettrale')
        .replace(/\bCeaseless Edge\b/g, 'Lama Milleflutti')
        .replace(/\bBleakwind Storm\b/g, 'Tempesta Boreale')
        .replace(/\bWildbolt Storm\b/g, 'Tempesta Tonante')
        .replace(/\bSandsear Storm\b/g, 'Tempesta Ardente')
        .replace(/\bLunar Blessing\b/g, 'Invocaluna')
        .replace(/\bTake Heart\b/g, 'Baldimpulso')

        .replace(/\bG\-Max Vine Lash\b/g, 'Gigasferzata')
        .replace(/\bG\-Max Wildfire\b/g, 'Gigavampa')
        .replace(/\bG\-Max Cannonade\b/g, 'Gigacannonata')
        .replace(/\bG\-Max Befuddle\b/g, 'Gigastupore')
        .replace(/\bG\-Max Volt Crash\b/g, 'Gigapikafolgori')
        .replace(/\bG\-Max Gold Rush\b/g, 'Gigamonete')
        .replace(/\bG\-Max Chi Strike\b/g, 'Gigapugnointuito')
        .replace(/\bG\-Max Terror\b/g, 'Gigaillusione')
        .replace(/\bG\-Max Foam Burst\b/g, 'Gigaschiuma')
        .replace(/\bG\-Max Resonance\b/g, 'Gigamelodia')
        .replace(/\bG\-Max Cuddle\b/g, 'Gigabbraccio')
        .replace(/\bG\-Max Replenish\b/g, 'Gigarinnovamento')
        .replace(/\bG\-Max Malodor\b/g, 'Gigafetore')
        .replace(/\bG\-Max Meltdown\b/g, 'Gigaliquefazione')
        .replace(/\bG\-Max Drum Solo\b/g, 'Gigarullio')
        .replace(/\bG\-Max Fireball\b/g, 'Gigafiammopalla')
        .replace(/\bG\-Max Hydrosnipe\b/g, 'Gigasparomirato')
        .replace(/\bG\-Max Wind Rage\b/g, 'Gigaciclone')
        .replace(/\bG\-Max Gravitas\b/g, 'Gigagravitoforza')
        .replace(/\bG\-Max Stonesurge\b/g, 'Gigarocciagetto')
        .replace(/\bG\-Max Volcalith\b/g, 'Gigalapilli')
        .replace(/\bG\-Max Tartness\b/g, 'Gigattaccoacido')
        .replace(/\bG\-Max Sweetness\b/g, 'Gigambrosia')
        .replace(/\bG\-Max Sandblast\b/g, 'Gigavortisabbia')
        .replace(/\bG\-Max Stun Shock\b/g, 'Gigatoxiscossa')
        .replace(/\bG\-Max Centiferno\b/g, 'Gigamillefiamme')
        .replace(/\bG\-Max Smite\b/g, 'Gigacastigo')
        .replace(/\bG\-Max Snooze\b/g, 'Gigatorpore')
        .replace(/\bG\-Max Finale\b/g, 'Gigagranfinale')
        .replace(/\bG\-Max Steelsurge\b/g, 'Gigaferroaculei')
        .replace(/\bG\-Max Depletion\b/g, 'Gigalogoramento')
        .replace(/\bG\-Max One Blow\b/g, 'Gigasingolcolpo')
        .replace(/\bG\-Max Rapid Flow\b/g, 'Gigapluricolpo')

    // Mosse ombra
        .replace(/\bShadow Blast\b/g, 'Ombrolame')
        .replace(/\bShadow Blitz\b/g, 'Ombrattacco')
        .replace(/\bShadow Bolt\b/g, 'Fulminombra')
        .replace(/\bShadow Break\b/g, 'Ombrospinta')
        .replace(/\bShadow Chill\b/g, 'Gelodombra')
        .replace(/\bShadow Down\b/g, 'Declinoscuro')
        .replace(/\bShadow End\b/g, 'Fineoscuro')
        .replace(/\bShadow Fire\b/g, 'Fuocoscuro')
        .replace(/\bShadow Half\b/g, 'Iraoscura')
        .replace(/\bShadow Mist\b/g, 'Nebbiascura')
        .replace(/\bShadow Panic\b/g, 'Ombrapanico')
        .replace(/\bShadow Rave\b/g, 'Ombrolancia')
        .replace(/\bShadow Rush\b/g, 'Ombroraffica')
        .replace(/\bShadow Shed\b/g, 'Ombrannulla')
        .replace(/\bShadow Sky\b/g, 'Cieloscuro')
        .replace(/\bShadow Storm\b/g, 'Turbinombra')
        .replace(/\bShadow Wave\b/g, 'Ondascura')

        .replace(/\bTera Blast\b/g, 'Terascoppio')
        .replace(/\bSilk Trap\b/g, 'Telatrappola')
        .replace(/\bAxe Kick\b/g, 'Calcio ad Ascia')
        .replace(/\bLast Respects\b/g, 'Omaggio ai KO')
        .replace(/\bLumina Crash\b/g, 'Fotocollisione')
        .replace(/\bOrder Up\b/g, 'Alta Cucina')
        .replace(/\bJet Punch\b/g, 'Pugnojet')
        .replace(/\bSpicy Extract\b/g, 'Essenza Piccante')
        .replace(/\bSpin Out\b/g, 'Slittaruote')
        .replace(/\bPopulation Bomb\b/g, 'Infestazione')
        .replace(/\bIce Spinner\b/g, 'Vortighiaccio')
        .replace(/\bGlaive Rush\b/g, 'Spadoncarica')
        .replace(/\bRevival Blessing\b/g, 'Preghiera Vitale')
        .replace(/\bSalt Cure\b/g, 'Sotto Sale')
        .replace(/\bTriple Dive\b/g, 'Triplo Tuffo').replace(/\bTriple Sub\b/g, 'Triplo Tuffo')
        .replace(/\bMortal Spin\b/g, 'Glitturbine')
        .replace(/\bDoodle\b/g, 'Ricalco')
        .replace(/\bFillet Away\b/g, 'Alleggerimento')
        .replace(/\bKowtow Cleave\b/g, 'Genufendente')
        .replace(/\bFlower Trick\b/g, 'Prestigiafiore').replace(/\bFlower Raggiro\b/g, 'Prestigiafiore')
        .replace(/\bTorch Song\b/g, 'Canzone Ardente')
        .replace(/\bAqua Step\b/g, 'Idroballetto')
        .replace(/\bRaging Bull\b/g, 'Scatenatoro')
        .replace(/\bMake It Rain\b/g, "Corsa all'Oro")
        .replace(/\bPound\b/g, 'Botta')
        .replace(/\bRuination\b/g, 'Catastrofe')
        .replace(/\bCollision Course\b/g, 'Turboschianto')
        .replace(/\bElectro Drift\b/g, 'Fulmiscatto')
        .replace(/\bShed Tail\b/g, 'Tagliacoda')
        .replace(/\bChilly Reception\b/g, 'Freddura')
        .replace(/\bTidy Up\b/g, 'Pulizie')
        .replace(/\bSnowscape\b/g, 'Vista Innevata')
        .replace(/\bPounce\b/g, 'Balzo')
        .replace(/\bTrailblaze\b/g, 'Apripista')
        .replace(/\bChilling Water\b/g, 'Doccia Fredda')
        .replace(/\bHyper Drill\b/g, 'Ipertrapano')
        .replace(/\bTwin Beam\b/g, 'Doppioraggio')
        .replace(/\bRage Fist\b/g, 'Pugno Furibondo').replace(/\bIra Fist\b/g, 'Pugno Furibondo')
        .replace(/\bArmor Cannon\b/g, 'Corazza Cannone')
        .replace(/\bBitter Blade\b/g, 'Lama del Rimorso')
        .replace(/\bDouble Shock\b/g, 'Doppiolampo')
        .replace(/\bGigaton Hammer\b/g, 'Granmartello')
        .replace(/\bComeuppance\b/g, 'Ritorsione')
        .replace(/\bAqua Cutter\b/g, 'Idrotaglio')
        .replace(/\bBlazing Torque\b/g, 'Turboustione')
        .replace(/\bWicked Torque\b/g, 'Turbotenebra')
        .replace(/\bNoxious Torque\b/g, 'Turbotossina')
        .replace(/\bCombat Torque\b/g, 'Turborissa')
        .replace(/\bMagical Torque\b/g, 'Turboincanto')
        .replace(/\bHydro Steam\b/g, 'Idrovapore')
        .replace(/\bPsyblade\b/g, 'Psicolama')
        .replace(/\bBlood Moon\b/g, 'Luna Rossa')
        .replace(/\bSyrup Bomb\b/g, 'Bomba Sciroppata')
        .replace(/\bMatcha Gotcha\b/g, 'Spruzzatè')
        .replace(/\bIvy Cudgel\b/g, 'Clava di Liane')

    // Correzione errori
        // .replace(/Acidoobomba/g, 'Acidobomba')
        // .replace(/GastroAcidoo/g, 'Gastroacido')
        // .replace(/SbaFossalio/g, 'Sbadiglio')
        // .replace(/DrudFossaon/g, 'Druddigon')
        // .replace(/Fascinoander/g, 'Charmander')
        // .replace(/Fascinoeleon/g, 'Charmeleon')
        // .replace(/SandLacerazione/g, 'Sandslash')
        // .replace(/AegiLacerazione/g, 'Aegislash')
        // .replace(/Fossalett/g, 'Diglett')
        // .replace(/Leccataitung/g, 'Lickitung')
        // .replace(/BeautiVolo/g, 'Beautifly')
        // .replace(/Vologon/g, 'Flygon')
        // .replace(/Tenagliaerl/g, 'Clamperl')
        // .replace(/GaMorso/g, 'Gabite')
        // .replace(/Tossinaroak/g, 'Toxicroak')
        // .replace(/LeccataiLeccatay/g, 'Lickilicky')
        // .replace(/IncineBoato/g, 'Incineroar')
        // .replace(/TaglioieVolo/g, 'Cutiefly')
        // .replace(/ExeggGrazia/g, 'Exeggcute')
        // .replace(/Desiderioiwashi/g, 'Wishiwashi')
        // .replace(/Taglioe/gi, 'Grazia')
        // .replace(/Ruggitoithe/g, 'Growlithe')
        // .replace(/Voloing/g, 'Flying')
        // .replace(/ZoBoatok/gi, 'Zoroark')
        // .replace(/Confusionee/gi, 'Confusione')
        // .replace(/Acidoo/gi, 'Acido')
        // .replace(/Mimicaa/gi, 'Mimica')
        // .replace(/Cantole/gi, 'Single')
        .replace(/\bWater Assorbimento\b/g, 'Water Absorb')
        // .replace(/Fossagersby/gi, 'Diggersby')
        // .replace(/PyBoato/gi, 'Pyroar')
        .replace(/\bEffect Spora\b/g, 'Effect Spore')
        .replace(/\bComete Swim\b/g, 'Swift Swim')
        // .replace(/Hyper Taglioter/gi, 'Hyper Cutter')
        // .replace(/Maledizioned Body/gi, 'Cursed Body')
        .replace(/\bVolt Assorbimento\b/g, 'Volt Absorb')
        .replace(/\bAssorbimento Bulb\b/g, 'Absorb Bulb')
        .replace(/\bpsichico color\b/g, 'psico color')
        .replace(/\bPsichico Terrain\b/g, 'Campo Psichico')
        // .replace(/Scintillaling Aria/g, 'Canto Effimero')
        .replace(/\bPsichico Fangs\b/g, 'Psicozanna')
        // .replace(/Pestoneing Tantrum/g, 'Battipiedi')
        // .replace(/AnnullaBarrierae/g, 'Annullabarriere')
        .replace(/\bForza Sap\b/g, 'Assorbiforza')
        .replace(/\bSupersuono Skystrike\b/g, 'Picchiata Devastante')
        .replace(/\bAcido Downpour\b/g, 'Acidiluvio Corrosivo')
        .replace(/\bTectonic Ira\b/g, 'Furore della Terra')
        .replace(/\bNever\-Ending Incubo\b/g, 'Abbraccio Spettrale')
        .replace(/\bMarchiatura Overdrive\b/g, 'Fiammobomba Detonante')
        // .replace(/Subzero Schiantomer/g, 'Criodistruzione Polare')
        .replace(/\bTwinkle Azione\b/g, 'Astroimpatto Fatato')
        .replace(/\bTossina Thread\b/g, 'Velenotela')
        // .replace(/Stoked ScintillaSurfer/g, 'Elettrosurf Folgorante')
        .replace(/\bSpectral Furto\b/g, 'Ombrafurto')
        .replace(/\b10,000,000 Volt Fulmine\b/g, 'Iperfulmine')
};

if (utils.updateMenu) { utils.updateMenu() } ;
}(utils || { macros: {} }));
