"use strict";
/**
 * "abilità" macro, that translates move names
 */

(function (utils) {
  const macros = utils.macros;

  /*

L'argomento battleHeld, con default false, indica se
devono essere tradotti solo gli strumenti tenuti
in lotta

*/
  macros.strumenti = function (str, battleHeld) {
    battleHeld = battleHeld || false;
    if (!battleHeld) {
      str = str
        // Pietre evolutive
        .replace(/\bSun Stone\b/g, "Pietrasolare")
        .replace(/\bMoon Stone\b/g, "Pietralunare")
        .replace(/\bFire Stone\b/g, "Pietrafocaia")
        .replace(/\bThunder Stone\b/g, "Pietratuono")
        .replace(/\bWater Stone\b/g, "Pietraidrica")
        .replace(/\bLeaf Stone\b/g, "Pietrafoglia")
        .replace(/\bShiny Stone\b/g, "Pietrabrillo")
        .replace(/\bDusk Stone\b/g, "Neropietra")
        .replace(/\bDawn Stone\b/g, "Pietralbore")
        .replace(/\bIce Stone\b/g, "Pietragelo")
        .replace(/\bOval Stone\b/g, "Pietraovale")

        // Altri strumenti evolutivi
        .replace(/\Tart Apple\b/g, "Aspropomo")
        .replace(/\bSweet Apple\b/g, "Dolcepomo")
        .replace(/\bSyrupy Apple\b/g, "Sciroppomo")
        .replace(/\bGalarica Cuff\b/g, "Fascia Galarnoce")
        .replace(/\bGalarica Cuff\b/g, "Corona Galarnoce")
        .replace(/\bChipped Pot\b/g, "Teiera crepata")
        .replace(/\bCracked Pot\b/g, "Teiera rotta")
        .replace(/\bBlack Augurite\b/g, "Augite nera")
        .replace(/\bPeat Block\b/g, "Blocco di torba")
        .replace(/\bLinking Cord\b/g, "Filo dell'unione")
        .replace(/\bAuspicious Armor\b/g, "Armatura fausta")
        .replace(/\bMalicious Armor\b/g, "Armatura infausta")
        .replace(/\bStrawberry Sweet\b/g, "Bonbonfragola")
        .replace(/\bLove Sweet\b/g, "Bonboncuore")
        .replace(/\bBerry Sweet\b/g, "Bonbonbosco")
        .replace(/\bClover Sweet\b/g, "Bonbonfoglio")
        .replace(/\bFlower Sweet\b/g, "Bonbonfiore")
        .replace(/\bStar Sweet\b/g, "Bonbonstella")
        .replace(/\bRibbon Sweet\b/g, "Bonbonfiocco")
        .replace(/\bMetal Alloy\b/g, "Metallo composito")
        .replace(/\bUnremarkable Teacup\b/g, "Tazza dozzinale")
        .replace(/\bMasterpiece Teacup\b/g, "Tazza eccezionale")

        // Strumenti per cambiare forma
        .replace(/\bYellow Nectar\b/g, "Nettare giallo")
        .replace(/\bPink Nectar\b/g, "Nettare giallo")
        .replace(/\bRed Nectar\b/g, "Nettare rosso")
        .replace(/\bPurple Nectar\b/g, "Nettare viola")

        // Strumenti da vendere
        .replace(/\bTiny Mushroom\b/g, "Minifungo")
        .replace(/\bBig Mushroom\b/g, "Grande Fungo")
        .replace(/\bBig Pearl\b/g, "Grande Perla")
        .replace(/\bPearl String\b/g, "Trittiperla")
        .replace(/\bPearl\b/g, "Perla")
        .replace(/\bStardust\b/g, "Polvostella")
        .replace(/\bStar Piece\b/g, "Pezzo Stella")
        .replace(/\bGold Leaf\b/g, "Fogliadoro")
        .replace(/\bSilver Leaf\b/g, "Fogliargento")
        .replace(/\bBrick Piece\b/g, "Mattoncino")
        .replace(/\bNugget\b/g, "Pepita")
        .replace(/\bHeart Scale\b/g, "Squama Cuore")
        .replace(/\bRare Bone\b/g, "Osso raro")
        .replace(/\bPretty Wing\b/g, "Piumabella")
        .replace(/\bBalm Mushroom\b/g, "Profumfungo")
        .replace(/\bBig Nugget\b/g, "Granpepita")
        .replace(/\bComet Shard\b/g, "Pezzo Cometa")
        .replace(/\bRelic Copper\b/g, "Soldantico")
        .replace(/\bRelic Silver\b/g, "Ducatantico")
        .replace(/\bRelic Gold\b/g, "Doblonantico")
        .replace(/\bRelic Vase\b/g, "Vasantico")
        .replace(/\bRelic Band\b/g, "Bracciantico")
        .replace(/\bRelic Statue\b/g, "Statuantica")
        .replace(/\bRelic Crown\b/g, "Coronantica")
        .replace(/\bGold Bottle Cap\b/g, "Tappo d'oro")
        .replace(/\bBottle Cap\b/g, "Tappo d'argento")
        .replace(/\bTiny Bamboo Shoot\b/g, "Minibambù")
        .replace(/\bBig Bamboo Shoot\b/g, "Grande bambù")
        .replace(/\bBeach Glass\b/g, "Vetro marino")
        .replace(/\bChalky Stone\b/g, "Gessetto")
        .replace(/\bStretchy Spring\b/g, "Molla elastica")
        .replace(/\bLone Earring\b/g, "Orecchino")
        .replace(/\bMarble\b/g, "Biglia")
        .replace(/\bGalarica Twig\b/g, "Ramo Galarnoce")

        // Rimedi
        .replace(/\bMax Potion\b/g, "Pozione Max")
        .replace(/\bHyper Potion\b/g, "Iperpozione")
        .replace(/\bSuper Potion\b/g, "Superpozione")
        .replace(/\bPotion\b/g, "Pozione")
        .replace(/\bAntidote\b/g, "Antidoto")
        .replace(/\bBurn Heal\b/g, "Antiscottatura")
        .replace(/\bIce Heal\b/g, "Antigelo")
        .replace(/\bAwakening\b/g, "Sveglia")
        .replace(/\bParalyze Heal\b/g, "Antiparalisi")
        .replace(/\bFull Restore\b/g, "Ricarica Totale")
        .replace(/\bFull Heal\b/g, "Cura Totale")
        .replace(/\bMax Revive\b/g, "Revitalizzante Max")
        .replace(/\bRevive\b/g, "Revitalizzante")
        .replace(/\bFresh Water\b/g, "Acqua Fresca")
        .replace(/\bSoda Pop\b/g, "Gassosa")
        .replace(/\bLemonade\b/g, "Lemonsucco")
        .replace(/\bMax Ether\b/g, "Etere Max")
        .replace(/\bEther\b/g, "Etere")
        .replace(/\bMax Elixir\b/g, "Elisir Max")
        .replace(/\bElixir\b/g, "Elisir")
        .replace(/\bMoomoo Milk\b/g, "Latte Mumu")
        .replace(/\bEnergy Powder\b/g, "Polvenergia")
        .replace(/\bEnergy Root\b/g, "Radicenergia")
        .replace(/\bHeal Powder\b/g, "Polvocura")
        .replace(/\bRevival Herb\b/g, "Vitalerba")
        .replace(/\bSacred Ash\b/g, "Cenere magica")
        .replace(/\bRage Candy Bar\b/g, "Iramella")
        .replace(/\bLava Cookie\b/g, "Lavottino")
        .replace(/\bBerry Juice\b/g, "Succo di Bacca")
        .replace(/\bHP Up\b/g, "PS-Su")
        .replace(/\bProtein\b/g, "Proteina")
        .replace(/\bIron\b/g, "Ferro")
        .replace(/\bCarbos\b/g, "Carburante")
        .replace(/\bCalcium\b/g, "Calcio")
        .replace(/\bRare Candy\b/g, "Caramella Rara")
        .replace(/\bPP Up\b/g, "PP-Su")
        .replace(/\bZinc\b/g, "Zinco")
        .replace(/\bPP Max\b/g, "PP-Max")
        .replace(/\bSweet Heart\b/g, "Dolcecuore")
        .replace(/\bHealth Wing\b/g, "Piumsalute")
        .replace(/\bMuscle Wing\b/g, "Piumpotenza")
        .replace(/\bResist Wing\b/g, "Piumtutela")
        .replace(/\bGenius Wing\b/g, "Piumingegno")
        .replace(/\bClever Wing\b/g, "Piumintuito")
        .replace(/\bSwift Wing\b/g, "Piumreazione")
        .replace(/\bCasteliacone\b/g, "Conostropoli")
        .replace(/\bLumiose Galette\b/g, "Pan di Lumi")
        .replace(/\bShalour Sable\b/g, "Yantafrollino")
        .replace(/\bPewter Crunchies\b/g, "Plumbeosalatini")

        // Balls
        .replace(/\bPoké Ball\b/g, "Pok&eacute; Ball")
        .replace(/\bGreat Ball\b/g, "Mega Ball")
        .replace(/\bUltra Ball\b/g, "Ultra Ball")
        .replace(/\bMaster Ball\b/g, "Master Ball")
        .replace(/\bSafari Ball\b/g, "Safari Ball")
        .replace(/\bHeavy Ball\b/g, "Peso Ball")
        .replace(/\bLevel Ball\b/g, "Level Ball")
        .replace(/\bLure Ball\b/g, "Esca Ball")
        .replace(/\bFast Ball\b/g, "Rapid Ball")
        .replace(/\bFriend Ball\b/g, "Friend Ball")
        .replace(/\bMoon Ball\b/g, "Luna Ball")
        .replace(/\bLove Ball\b/g, "Love Ball")
        .replace(/\bSport Ball\b/g, "Gara Ball")
        .replace(/\bNet Ball\b/g, "Rete Ball")
        .replace(/\bDive Ball\b/g, "Sub Ball")
        .replace(/\bNest Ball\b/g, "Minor Ball")
        .replace(/\bRepeat Ball\b/g, "Bis Ball")
        .replace(/\bTimer Ball\b/g, "Timer Ball")
        .replace(/\bLuxury Ball\b/g, "Chic Ball")
        .replace(/\bPremier Ball\b/g, "Premier Ball")
        .replace(/\bHeal Ball\b/g, "Cura Ball")
        .replace(/\bDusk Ball\b/g, "Scuro Ball")
        .replace(/\bQuick Ball\b/g, "Velox Ball")
        .replace(/\bPark Ball\b/g, "Parco Ball")
        .replace(/\bCherish Ball\b/g, "Pregio Ball")
        .replace(/\bDream Ball\b/g, "Dream Ball")

        // Messaggi - Gen II
        .replace(/\bFlower Mail\b/g, "Messaggio Fiore")
        .replace(/\bSurf Mail\b/g, "Mess. Surf")
        .replace(/\bLitebluemail\b/g, "Mess. Azzurro")
        .replace(/\bPortraitmail\b/g, "Mess. Ritratto")
        .replace(/\bLovely Mail\b/g, "Mess. Dolce")
        .replace(/\bEon Mail\b/g, "Mess. Eon")
        .replace(/\bMorph Mail\b/g, "Mess. Morph")
        .replace(/\bBluesky Mail\b/g, "Mess. Cielo")
        .replace(/\bMusic Mail\b/g, "Mess. Musica")
        .replace(/\bMirage Mail\b/g, "Mess. Visione")

        // Messaggi - Gen III
        .replace(/\bOrange Mail\b/g, "Mess. Agrume")
        .replace(/\bHarbor Mail\b/g, "Mess. Porto")
        .replace(/\bGlitter Mail\b/g, "Mess. Luci")
        .replace(/\bMech Mail\b/g, "Mess. Tecno")
        .replace(/\bWood Mail\b/g, "Mess. Bosco")
        .replace(/\bWave Mail\b/g, "Mess. Onda")
        .replace(/\bBead Mail\b/g, "Mess. Perle")
        .replace(/\bShadow Mail\b/g, "Mess. Ombra")
        .replace(/\bTropic Mail\b/g, "Mess. Tropic")
        .replace(/\bDream Mail\b/g, "Mess. Sogno")
        .replace(/\bFab Mail\b/g, "Mess. Fab")
        .replace(/\bRetro Mail\b/g, "Mess. Retro")

        // Messaggi - Gen IV
        .replace(/\bGrass Mail\b/g, "Mess. Erba")
        .replace(/\bFlame Mail\b/g, "Mess. Fiamma")
        .replace(/\bBubble Mail\b/g, "Mess. Bolla")
        .replace(/\bBloom Mail\b/g, "Mess. Petalo")
        .replace(/\bTunnel Mail\b/g, "Mess. Tunnel")
        .replace(/\bSteel Mail\b/g, "Mess. Lega")
        .replace(/\bHeart Mail\b/g, "Mess. Cuore")
        .replace(/\bSnow Mail\b/g, "Mess. Neve")
        .replace(/\bSpace Mail\b/g, "Mess. Spazio")
        .replace(/\bAir Mail\b/g, "Mess.  Aereo")
        .replace(/\bMosaic Mail\b/g, "Mess.  Iride")
        .replace(/\bBrick Mail\b/g, "Mess. Muro")

        // Messaggi - Gen V
        .replace(/\bGreet Mail\b/g, "Mess. Inizio")
        .replace(/\bFavored Mail\b/g, "Mess. TVB")
        .replace(/\bRSVP Mail\b/g, "Mess. Invito")
        .replace(/\bThanks Mail\b/g, "Mess. Grazie")
        .replace(/\bInquiry Mail\b/g, "Mess. Chiedi")
        .replace(/\bLike Mail\b/g, "Mess. Sugg.")
        .replace(/\bReply Mail\b/g, "Mess. Risp.")
        .replace(/\bBridgeMail S\b/g, "Mess. Frec.")
        .replace(/\bBridgeMail D\b/g, "Mess. Libec.")
        .replace(/\bBridgeMail T\b/g, "Mess. Prop.")
        .replace(/\bBridgeMail V\b/g, "Mess. Vill.")
        .replace(/\bBridgeMail M\b/g, "Mess. Merav.")

        // Strumenti lotta
        .replace(/\bGuard Spec.\b/g, "Superguardia")
        .replace(/\bDire Hit\b/g, "Supercolpo")
        .replace(/\bX Attack\b/g, "Attacco X")
        .replace(/\bX Defend\b/g, "Difesa X")
        .replace(/\bX Defense\b/g, "Difesa X")
        .replace(/\bX Speed\b/g, "Velocit&agrave; X")
        .replace(/\bX Accuracy\b/g, "Precisione X")
        .replace(/\bX Special\b/g, "Special X")
        .replace(/\bX Sp\. Atk\b/g, "Attacco Speciale X")
        .replace(/\bX Sp\. Def\b/g, "Difesa Speciale X")
        .replace(/\bPoké Doll\b/g, "Pokébambola")
        .replace(/\bFluffy Tail\b/g, "Coda Skitty")
        .replace(/\bBlue Flute\b/g, "Flauto Blu")
        .replace(/\bYellow Flute\b/g, "Flauto Giallo")
        .replace(/\bRed Flute\b/g, "Flauto Rosso")
        .replace(/\bPoké Toy\b/g, "Pok&eacute;gingillo")
        .replace(/\bAbility Urge\b/g, "Chiamabilit&agrave;")
        .replace(/\bItem Drop\b/g, "Lascioggetto")
        .replace(/\bItem Urge\b/g, "Chiamoggetto")
        .replace(/\bReset Urge\b/g, "Ripristino")

        // Strumenti base - Gen I
        .replace(/\bCoin Case\b/g, "Salvadanaio")
        .replace(/\bItemfinder\b/g, "Detector")
        .replace(/\bOld Rod\b/g, "Amo Vecchio")
        .replace(/\bGood Rod\b/g, "Amo Buono")
        .replace(/\bSuper Rod\b/g, "Super Amo")
        .replace(/\bS\.S\. Ticket\b/g, "Biglietto Nave")
        .replace(/\bOak's Parcel\b/g, "Pacco Oak")
        .replace(/\bPoké Flute\b/g, "Pok&eacute;flauto")
        .replace(/\bSecret Key\b/g, "Chiave Segreta")
        .replace(/\bBike Voucher\b/g, "Buono Bici")
        .replace(/\bGold Teeth\b/g, "Denti d'Oro")
        .replace(/\bCard Key\b/g, "Apriporta")
        .replace(/\bLift Key\b/g, "Chiave Ascensore")
        .replace(/\bSilph Scope\b/g, "Spettrosonda")
        .replace(/\bBicycle\b/g, "Bicicletta")
        .replace(/\bTown Map\b/g, "Mappa")
        .replace(/\bFishing Rod\b/g, "Canna da pesca")

        // Strumenti base - Gen II
        .replace(/\bGS Ball\b/g, "GS Ball")
        .replace(/\bEgg Ticket\b/g, "Bigl. Uovo")
        .replace(/\bClear Bell\b/g, "Campana Chiara")
        .replace(/\bBlue Card\b/g, "Carta Blu")
        .replace(/\bSquirtBottle\b/g, "Annaffiatoio")
        .replace(/\bSquirt Bottle\b/g, "Annaffiatoio")
        .replace(/\bRed Scale\b/g, "Squama Rossa")
        .replace(/\bLost Item\b/g, "Strumento Perso")
        .replace(/\bPass\b/g, "Superpass")
        .replace(/\bMachine Part\b/g, "Pezzo macch.")
        .replace(/\bSilver Wing\b/g, "Aladargento")
        .replace(/\bRainbow Wing\b/g, "Ala d'Iride")
        .replace(/\bSilver Feather\b/g, "Aladargento")
        .replace(/\bRainbow Feather\b/g, "Ala d'Iride")
        .replace(/\bMystery Egg\b/g, "Uovo Mistero")
        .replace(/\bSecretPotion\b/g, "Poz. Segreta")

        // Strumenti base - Gen III
        .replace(/\bMach Bike\b/g, "Bici Corsa")
        .replace(/\bWailmer Pail\b/g, "Vaso Wailmer")
        .replace(/\bDevon Goods\b/g, "Merce Devon")
        .replace(/\bSoot Sack\b/g, "Sacco Cenere")
        .replace(/\bBasement Key\b/g, "Chiave Sotterraneo")
        .replace(/\bAcro Bike\b/g, "Bici Cross")
        .replace(/\bPokéblock Case\b/g, "Porta Pok&eacute;melle")
        .replace(/\bLetter\b/g, "Lettera")
        .replace(/\bEon Ticket\b/g, "Biglietto Eone")
        .replace(/\bRed Orb\b/g, "Sfera Rossa")
        .replace(/\bBlue Orb\b/g, "Sfera Blu")
        .replace(/\bScanner\b/g, "Scanner")
        .replace(/\bGo\-Goggles\b/g, "Occhialoni")
        // .replace(/\bMeteorite\b/g, 'Meteorite')
        .replace(/\bRm\. (\d) Key\b/g, "Chiave stanza $1")
        .replace(/\bStorage Key\b/g, "L.")
        .replace(/\bDevon Scope\b/g, "Devonscopio")
        .replace(/\bVs\. Seeker\b/g, "Cercasfide")
        .replace(/\bFame Checker\b/g, "Pok&eacute;VIP")
        .replace(/\bTM Case\b/g, "Porta MT-MN")
        .replace(/\bBerry Pouch\b/g, "Porta Bacche")
        .replace(/\bTeachy TV\b/g, "Pok&eacute; TV")
        // .replace(/\bRainbow Pass\b/g, "Sette Pass")
        .replace(/\bRainbow Superpass\b/g, "Sette Pass")
        .replace(/\bTea\b/g, "T&egrave;")
        .replace(/\bMysticTicket\b/g, "Biglietto Mistero")
        .replace(/\bAuroraTicket\b/g, "Biglietto Aurora")
        .replace(/\bPowder Jar\b/g, "Portafarina")
        .replace(/\bRuby\b/g, "Rubino")
        .replace(/\bSapphire\b/g, "Zaffiro")
        .replace(/\bMagma Emblem\b/g, "Stemma Magma")
        .replace(/\bOld Sea Map\b/g, "Mappa Stinta")
        .replace(/\bKey to Room 1\b/g, "Chiave stanza 1")
        .replace(/\bKey to Room 2\b/g, "Chiave stanza 2")
        .replace(/\bKey to Room 4\b/g, "Chiave stanza 4")
        .replace(/\bKey to Room 6\b/g, "Chiave stanza 6")

        // Strumenti base - Gen IV
        .replace(/\bExplorer Kit\b/g, "Esplorokit")
        .replace(/\bPoké Radar\b/g, "Pok&eacute; Radar")
        .replace(/\bPoint Card\b/g, "Scheda Punti")
        .replace(/\bJournal\b/g, "Agenda")
        .replace(/\bSeal Case\b/g, "Portabolli")
        .replace(/\bFashion Case\b/g, "Scatola Chic")
        .replace(/\bPal Pad\b/g, "Blocco Amici")
        .replace(/\bWorks Key\b/g, "Turbinchiave")
        .replace(/\bOld Charm\b/g, "Arcamuleto")
        .replace(/\bGalactic Key\b/g, "Galachiave")
        .replace(/\bSprayduck\b/g, "Sprayduck")
        .replace(/\bPoffin Case\b/g, "Portapoffin")
        .replace(/\bSuite Key\b/g, "Chiave Suite")
        .replace(/\bOak's Letter\b/g, "Lettera di Oak")
        .replace(/\bOak's Lettera\b/g, "Lettera di Oak")
        .replace(/\bLunar Wing\b/g, "Ala Lunare")
        .replace(/\bMember Card\b/g, "Scheda Soci")
        .replace(/\bParcel\b/g, "Pacco")
        .replace(/\bVs\. Recorder\b/g, "Registradati")
        .replace(/\bGracidea\b/g, "Gracidea")
        .replace(/\bApricorn Box\b/g, "Ghicobox")
        .replace(/\bUnown Report\b/g, "UnownBloc")
        .replace(/\bBerry Pots\b/g, "Piantabacche")
        .replace(/\bDowsing MCHN\b/g, "Ricerca Strum.")
        .replace(/\bGB Sounds\b/g, "Lettore GB")
        .replace(/\bTidal Bell\b/g, "Camp. Onda")
        .replace(/\bData Card\b/g, "Scheda Dati")
        .replace(/\bJade Orb\b/g, "Sfera Verde")
        .replace(/\bEnigma Stone\b/g, "Misticristal")
        .replace(/\bLunar Feather\b/g, "Piumalunare")
        .replace(/\bLoot Sack\b/g, "Bottinosacca")
        .replace(/\bRed Chain\b/g, "Catena rossa")

        // Strumenti base - Gen V
        // .replace(/\bLiberty Pass\b/g, "Liberticket")
        .replace(/\bLiberty Superpass\b/g, "Liberticket")
        .replace(/\bProp Case\b/g, "Portagadget")
        .replace(/\bDragon Skull\b/g, "Teschio")
        .replace(/\bLight Stone\b/g, "Chiarolite")
        .replace(/\bDark Stone\b/g, "Scurolite")
        .replace(/\bXtransceiver\b/g, "Interpok&eacute;")
        .replace(/\bGram (\d)\b/g, "Missiva $1")
        .replace(/\bColress MCHN\b/g, "Acrocongegno")
        .replace(/\bDNA Splicers\b/g, "Cuneo DNA")
        .replace(/\bDropped Item\b/g, "Oggetto Perso")
        .replace(/\bGrubby Hanky\b/g, "Pezza Sporca")
        .replace(/\bMedal Box\b/g, "Box Premi")
        .replace(/\bOval Charm\b/g, "Ovamuleto")
        .replace(/\bPermit\b/g, "Permesso")
        .replace(/\bPlasma Card\b/g, "Carta Plasma")
        .replace(/\bReveal Glass\b/g, "Verispecchio")
        .replace(/\bShiny Charm\b/g, "Cromamuleto")
        .replace(/\bMagma Stone\b/g, "Magmapietra")
        .replace(/\bColress Machine\b/g, "Acrocongegno")

        // Strumenti base - Gen VI
        .replace(/\bAdventure Rules\b/g, "Guida Avventura")
        .replace(/\bElevator Key\b/g, "Chiave ascensore")
        .replace(/\bHolo Caster\b/g, "Holovox")
        .replace(/\bHonor of Kalos\b/g, "Emblema di Kalos")
        .replace(/\bIntriguing Stone\b/g, "Sasso suggestivo")
        .replace(/\bLens Case\b/g, "Portalenti")
        .replace(/\bLooker Ticket\b/g, "Carta Bellocchio")
        .replace(/\bMega Ring\b/g, "Megacerchio")
        .replace(/\bPower Plant Pass\b/g, "Pass Centrale")
        .replace(/\bProf's Letter\b/g, "Lettera del Prof")
        .replace(/\bProf's Lettera\b/g, "Lettera del Prof")
        .replace(/\bRoller Skates\b/g, "Pattini")
        .replace(/\bSprinklotad\b/g, "Irrigalotad")
        .replace(/\bTMV Pass\b/g, "Pass TMV")
        .replace(/\bAqua Suit\b/g, "Tuta Idro")
        .replace(/\bMagma Suit\b/g, "Tuta Magma")
        .replace(/\bPair of Tickets\b/g, "Biglietto doppio")
        .replace(/\bMega Bracelet\b/g, "Megabracciale")
        .replace(/\bMega Pendant\b/g, "Megapendente")
        .replace(/\bMega Glasses\b/g, "Megaocchiali")
        .replace(/\bMega Anchor\b/g, "Megaancora")
        .replace(/\bMega Stickpin\b/g, "Megaspilla")
        .replace(/\bMega Tiara\b/g, "Megadiadema")
        .replace(/\bMega Anklet\b/g, "Megagambale")
        .replace(/\bKey Stone\b/g, "Pietrachiave")
        .replace(/\bMeteorite Shard\b/g, "Framm. meteorite")
        .replace(/\bEon Flute\b/g, "Flauto Eone")
        .replace(/\bCommon Stone\b/g, "Sasso qualsiasi")

        // Strumenti base - Gen VII
        .replace(/\bAutograph \b/g, "Autografo")
        .replace(/\bZ-Power Ring\b/g, "Supercerchio Z")
        .replace(/\bIlima's Normium Z\b/g, "Normium Z Liam")
        .replace(/\bBlue Petal\b/g, "Petalo azzurro")
        .replace(/\bGreen Petal\b/g, "Petalo verde")
        .replace(/\bOrange Petal\b/g, "Petalo arancione")
        .replace(/\bPink Petal\b/g, "Petalo rosa")
        .replace(/\bPurple Petal\b/g, "Petalo violetto")
        .replace(/\bRed Petal\b/g, "Petalo rosso")
        .replace(/\bYellow Petal\b/g, "Petalo giallo")
        .replace(/\bRainbow Flower\b/g, "Fiore arcobaleno")
        .replace(/\bEnigmatic Card\b/g, "Lettera segreta")
        .replace(/\bMoon Flute\b/g, "Flauto lunare")
        .replace(/\bSun Flute\b/g, "Flauto solare")
        .replace(/\bN-Lunarizer\b/g, "Necrolunix")
        .replace(/\bN-Solarizer\b/g, "Necrosolix")
        .replace(/\bSurge Badge\b/g, "Medaglia Tonante")
        .replace(/\bForage Bag\b/g, "Portaingredienti")
        .replace(/\bProfessor['’]s Mask\b/g, "Maschera Prof.")
        .replace(/\bSparkling Stone\b/g, "Pietra lucente")
        .replace(/\bLure\b/g, "Profumo invito")
        .replace(/\bSuper Lure\b/g, "Superprofumo")
        .replace(/\bMax Lure\b/g, "Profumo max")
        .replace(/\bLeft Poké Ball\b/g, "Poké Ball altrui")
        .replace(/\bPower-Up Pocket\b/g, "Tasca potenziam.")
        .replace(/\bClothing Trunk\b/g, "Valigia vestiti")
        .replace(/\bCatching Pocket\b/g, "Tasca cattura")
        .replace(/\bBattle Pocket\b/g, "Tasca lotta")

        // Strumenti base - Gen VIII
        .replace(/\bArmor Pass\b/g, "Pass Armatura")
        .replace(/\bRusted Shield\b/g, "Scudo rovinato")
        .replace(/\bRusted Sword\b/g, "Spada rovinata")
        .replace(/\bEndorsement\b/g, "Referenze")
        .replace(/\bCarrot Seeds\b/g, "Semi di carota")
        .replace(/\bIceroot Carrot\b/g, "Carota algida")
        .replace(/\bShaderoot Carrot\b/g, "Carota oscura")
        .replace(/\bRadiant Petal\b/g, "Petalo lucente")
        .replace(/\bWhite Mane Hair\b/g, "Crini bianchi")
        .replace(/\bBlack Mane Hair\b/g, "Crini neri")
        .replace(/\bWooden Crown\b/g, "Corona di legno")
        // .replace(/\bOld letter\b/g, "Vecchia lettera")
        .replace(/\bOld lettera\b/g, "Vecchia lettera")
        .replace(/\bProf's Lettera\b/g, "Lettera del Prof")
        .replace(/\bRoller Skates\b/g, "Pattini")
        .replace(/\bSprinklotad\b/g, "Irrigalotad")
        .replace(/\bTMV Pass\b/g, "Pass TMV")
        .replace(/\bSonia's Book\b/g, "Libro di Sonia")
        .replace(/\bDynamax Crystal\b/g, "Dynacristallo")
        .replace(/\bRotom Phone\b/g, "Smart Rotom")

        // Strumenti chiave - Gen IX
        .replace(/\bRotom Catalog\b/g, "Catalogo Rotom")
        .replace(/\bKofu's Wallet\b/g, "Portafogli di Algaro")
        .replace(/\bShiny Charm\b/g, "Cromamuleto")
        .replace(/\bAdvnture Guide\b/g, "Guida avventura")
        .replace(/\bSandwich\b/g, "Panino")
        .replace(/\bKoraidon['’]s Poké Ball\b/g, "Poké Ball Koraidon")
        .replace(/\bMiraidon['’]s Poké Ball\b/g, "Poké Ball Miraidon")
        .replace(/\bTera Orb\b/g, "Terasfera")
        .replace(/\bScarlet Book\b/g, "Libro scarlatto")
        .replace(/\bViolet Book\b/g, "Libro violetto")
        .replace(/\bScroll of Darkness\b/g, "Rotolo del Buio")
        .replace(/\bScroll of Waters\b/g, "Rotolo dell'Acqua")
        .replace(/\bGracidea\b/g, "Gracidea")
        .replace(/\bPrison Bottle\b/g, "Vaso del vincolo")
        .replace(/\bReins of Unity\b/g, "Briglie legame")
        .replace(/\bReveal Glass\b/g, "Verispecchio")
        .replace(/\bTeal Mask\b/g, "Maschera Turchese")
        .replace(/\bExp. Charm\b/g, "Esperienzamuleto")
        .replace(/\bCrystal Cluster\b/g, "Pezzo di cristallo")
        .replace(/\bGlimmering Charm\b/g, "Brillamuleto")
        .replace(/\bRoto-Stick\b/g, "Bastone Rotoselfie")
        .replace(/\bTeal Style Card\b/g, "Tessera chic verde")
        .replace(/\bMark Charm\b/g, "Emblemamuleto")
        .replace(/\bBriar's Book\b/g, "Libro di Rea")
        .replace(/\bCatching Charm\b/g, "Catturamuleto")
        .replace(/\bIndigo Disk\b/g, "Disco indaco")
        .replace(/\bIndigo Style Card\b/g, "Tessera chic blu")
        .replace(/\bSynchro Machine\b/g, "Sincronizzatore")
        .replace(/\bMythical Pecha Berry\b/g, "Baccapesca misteriosa")
        .replace(/\bMythical Baccapesca\b/g, "Baccapesca misteriosa")
        .replace(/\bKoraidon's Poké Ball\b/g, "Poké Ball Koraidon")
        .replace(/\bMiraidon's Poké Ball\b/g, "Poké Ball Miraidon")
        .replace(/\bTeal Mask\b/g, "Maschera Turchese")
        .replace(/\bWellspring Mask\b/g, "Maschera Pozzo")
        .replace(/\bHearthflame Mask\b/g, "Maschera Focolare")
        .replace(/\bCornerstone Mask\b/g, "Maschera Fondamenta")
        // Spuntini
        // .replace(/\bTreat\b/g, "Spuntino")
        .replace(
          /\b(Articuno|Zapdos|Moltres|Raikou|Entei|Suicune|Lugia|Ho-Oh|Latias|Latios|Kyogre|Groudon|Rayquaza|Cobalion|Terrakion|Virizion|Reshiram|Zekrom|Kyurem|Solgaleo|Lunala|Necrozma|Kubfu|Glastrier|Spectrier) Treat\b/g,
          "Spuntino per $1",
        )

        // // Ghicocche
        // .replace(/\bRed Apricorn\b/g, "Ghicocca Rsa")
        // .replace(/\bBlu Apricorn\b/g, "Ghicocca Blu")
        // .replace(/\bYlw Apricorn\b/g, "Ghicocca Gia")
        // .replace(/\bGrn Apricorn\b/g, "Ghicocca Ver")
        // .replace(/\bWht Apricorn\b/g, "Ghicocca Bln")
        // .replace(/\bBlk Apricorn\b/g, "Ghicocca Nra")
        // .replace(/\bPnk Apricorn\b/g, "Ghicocca Ros")

        // Altri strumenti
        .replace(/\bSuper Repel\b/g, "Superrepellente")
        .replace(/\bMax Repel\b/g, "Repellente Max")
        .replace(/\bRepel\b/g, "Repellente")
        .replace(/\bEscape Rope\b/g, "Fune di Fuga")
        .replace(/\bBlack Flute\b/g, "Flauto Nero")
        .replace(/\bWhite Flute\b/g, "Flauto Bianco")
        .replace(/\bShoal Salt\b/g, "Sale Ondoso")
        .replace(/\bShoal Shell\b/g, "Gusciondoso")
        .replace(/\bRed Shard\b/g, "Coccio Rosso")
        .replace(/\bBlue Shard\b/g, "Coccio Blu")
        .replace(/\bYellow Shard\b/g, "Coccio Giallo")
        .replace(/\bGreen Shard\b/g, "Coccio Verde")
        .replace(/\bExp. Share\b/g, "Condividi Esp.")
        .replace(/\bNormal Box\b/g, "Scat. Normale")
        .replace(/\bGorgeous Box\b/g, "Scat. Lusso")
        .replace(/\bSlowpokeTail\b/g, "CodaSlowpoke")
        .replace(/\bHoney\b/g, "Miele")
        .replace(/\bGrowth Mulch\b/g, "Fertilrapido")
        .replace(/\bDamp Mulch\b/g, "Fertilidro")
        .replace(/\bStable Mulch\b/g, "Fertilsaldo")
        .replace(/\bGooey Mulch\b/g, "Fertilcolla")
        .replace(/\bRoot Fossil\b/g, "Radifossile")
        .replace(/\bClaw Fossil\b/g, "Fossilunghia")
        .replace(/\bHelix Fossil\b/g, "Helixfossile")
        .replace(/\bDome Fossil\b/g, "Domofossile")
        .replace(/\bOld Amber\b/g, "Ambra Antica")
        .replace(/\bArmor Fossil\b/g, "Fossilscudo")
        .replace(/\bSkull Fossil\b/g, "Fossilcranio")
        .replace(/\bOdd Keystone\b/g, "Roccianima")
        .replace(/\bCover Fossil\b/g, "Fossiltappo")
        .replace(/\bPlume Fossil\b/g, "Fossilpiuma")
        .replace(/\bPass Orb\b/g, "Passabilia")
        .replace(/\bJaw Fossil\b/g, "Fossilmascella")
        .replace(/\bSail Fossil\b/g, "Fossilpinna")
        .replace(/\bAmaze Mulch\b/g, "Fertilprodigio")
        .replace(/\bBoost Mulch\b/g, "Fertilcopioso")
        .replace(/\bSurprise Mulch\b/g, "Fertilsorpresa")
        .replace(/\bRich Mulch\b/g, "Fertilflorido")
        .replace(/\bDiscount Coupon\b/g, "Buono sconto")
        .replace(/\bStrange Souvenir\b/g, "Strano ninnolo")
        .replace(/\bAbility Capsule\b/g, "Capsula abilit&agrave;")
        .replace(/\bJoy Scent\b/g, "Olio di Pino")
        .replace(/\bExcite Scent\b/g, "Olio di Rosa")
        .replace(/\bVivid Scent\b/g, "Olio Sublime")
        .replace(/\bColognes Case\b/g, "Portaoli")
        .replace(/\bColognes\b/g, "Oli")
        .replace(/\bAdrenaline Orb\b/g, "Fifasfera")
        .replace(/\bAbility Patch\b/g, "Cerotto abilità")
        .replace(/\bFossilized Bird\b/g, "Ornitofossile")
        .replace(/\bFossilized Dino\b/g, "Plesiofossile")
        .replace(/\bFossilized Drake\b/g, "Dracofossile")
        .replace(/\bFossilized Fish\b/g, "Ittiofossile")
        .replace(/\bDynamax Candy\b/g, "Caram. Dynamax")
        .replace(/\bDynite Ore\b/g, "Rocciamax")
        .replace(/\bFestival Ticket\b/g, "Festicket")
        .replace(/\bMirror Herb\b/g, "Foglia carbone")
        .replace(/\bFiery Pick\b/g, "Stecchino infuocato")
        .replace(/\bMax Mushrooms\b/g, "Fungomax")

        // Strumenti da picnic
        .replace(/\bAcademy Bottle\b/g, "Borraccia accademia")
        .replace(/\bPolka-Dot Bottle\b/g, "Borraccia a pois")
        .replace(/\bStriped Bottle\b/g, "Borraccia a righe")
        .replace(/\bDiamond Bottle\b/g, "Borraccia a rombi")
        .replace(/\bAcademy Cup\b/g, "Tazza accademia")
        .replace(/\bStriped Cup\b/g, "Tazza a righe verticali")
        .replace(/\bPolka-Dot Cup\b/g, "Tazza a pois")
        .replace(/\bFlower Pattern Cup\b/g, "Tazza a fiori")
        .replace(/\bAcademy Tablecloth\b/g, "Tovaglia accademia")
        .replace(/\bWhimsical Tablecloth\b/g, "Tovaglia carina")
        .replace(/\bLeafy Tablecloth\b/g, "Tovaglia natura")
        .replace(/\bSpooky Tablecloth\b/g, "Tovaglia dispetto")
        .replace(/\bAcademy Ball\b/g, "Palla accademia")
        .replace(/\bMarill Ball\b/g, "Palla Marill")
        .replace(/\bYarn Ball\b/g, "Palla gomitolo")
        .replace(/\bCyber Ball\b/g, "Palla gaming")
        .replace(/\bGold Pick\b/g, "Stecchino oro")
        .replace(/\bSilver Pick\b/g, "Stecchino argento")
        .replace(/\bRed-Flag Pick\b/g, "Bandierina rossa")
        .replace(/\bBlue-Flag Pick\b/g, "Bandierina blu")
        .replace(/\bPika-Pika Pick\b/g, "Stecchino Pikachu")
        .replace(/\bWinking Pika Pick\b/g, "Stecchino pikapika")
        .replace(/\bVee-Vee Pick\b/g, "Stecchino Eevee")
        .replace(/\bSmiling Vee Pick\b/g, "Stecchino veevee")
        .replace(/\bBlue Poké Ball Pick\b/g, "Stecchino Ball blu")
        .replace(/\bPink Bottle\b/g, "Borraccia rosa")
        .replace(/\bBlue Bottle\b/g, "Borraccia celeste")
        .replace(/\bYellow Bottle\b/g, "Borraccia gialla")
        .replace(/\bSteel Bottle (R)\b/g, "Borraccia inox R")
        .replace(/\bSteel Bottle (Y)\b/g, "Borraccia inox G")
        .replace(/\bSteel Bottle (B)\b/g, "Borraccia inox B")
        .replace(/\bSilver Bottle\b/g, "Borraccia argento")
        .replace(/\bBarred Cup\b/g, "Tazza a righe orizzontali")
        .replace(/\bDiamond Pattern Cup\b/g, "Tazza a rombi")
        .replace(/\bFire Pattern Cup\b/g, "Tazza con fiamme")
        .replace(/\bPink Cup\b/g, "Tazza rosa")
        .replace(/\bBlue Cup\b/g, "Tazza celeste")
        .replace(/\bYellow Cup\b/g, "Tazza gialla")
        .replace(/\bPikachu Cup\b/g, "Tazza Pikachu")
        .replace(/\bEevee Cup\b/g, "Tazza Eevee")
        .replace(/\bSlowpoke Cup\b/g, "Tazza Slowpoke")
        .replace(/\bSilver Cup\b/g, "Tazza argento")
        .replace(/\bExercise Ball\b/g, "Palla fitness")
        .replace(/\bPlaid Tablecloth (Y)\b/g, "Tovaglia a quadri gialla")
        .replace(/\bPlaid Tablecloth (B)\b/g, "Tovaglia a quadri viola")
        .replace(/\bPlaid Tablecloth (R)\b/g, "Tovaglia a quadri rossa")
        .replace(/\bB&W Grass Tablecloth\b/g, "Tovaglia erba alta")
        .replace(/\bBattle Tablecloth\b/g, "Tovaglia sfida")
        .replace(/\bMonstrous Tablecloth\b/g, "Tovaglia mostruosa")
        .replace(/\bStriped Tablecloth\b/g, "Tovaglia a righe")
        .replace(/\bDiamond Tablecloth\b/g, "Tovaglia a rombi")
        .replace(/\bPolka-Dot Tablecloth\b/g, "Tovaglia a pois")
        .replace(/\bLilac Tablecloth\b/g, "Tovaglia lilla")
        .replace(/\bMint Tablecloth\b/g, "Tovaglia menta")
        .replace(/\bPeach Tablecloth\b/g, "Tovaglia pesca")
        .replace(/\bYellow Tablecloth\b/g, "Tovaglia gialla")
        .replace(/\bBlue Tablecloth\b/g, "Tovaglia blu")
        .replace(/\bPink Tablecloth\b/g, "Tovaglia rosa")
        .replace(/\bGold Bottle\b/g, "Borraccia oro")
        .replace(/\bBronze Bottle\b/g, "Borraccia bronzo")
        .replace(/\bGold Cup\b/g, "Tazza oro")
        .replace(/\bBronze Cup\b/g, "Tazza bronzo")
        .replace(/\bGreen Poké Ball Pick\b/g, "Stecchino Ball verde")
        .replace(/\bRed Poké Ball Pick\b/g, "Stecchino Ball rosso")
        .replace(/\bParty Sparkler Pick\b/g, "Stecchino scintille")
        .replace(/\bHeroic Sword Pick\b/g, "Stecchino spadone")
        .replace(/\bMagical Star Pick\b/g, "Stecchino magistella")
        .replace(/\bMagical Heart Pick\b/g, "Stecchino magicuore")
        .replace(/\bParasol Pick\b/g, "Ombrellino")
        .replace(/\bBlue-Sky Flower Pick\b/g, "Stecchino fiore blu")
        .replace(/\bSunset Flower Pick\b/g, "Stecchino fiore arancio")
        .replace(/\bSunrise Flower Pick\b/g, "Stecchino fiore rosso")
        .replace(/\bBlue Dish\b/g, "Piatto celeste")
        .replace(/\bGreen Dish\b/g, "Piatto verde")
        .replace(/\bOrange Dish\b/g, "Piatto arancione")
        .replace(/\bRed Dish\b/g, "Piatto rosso")
        .replace(/\bWhite Dish\b/g, "Piatto bianco")
        .replace(/\bPiatto giallo\b/g, "Yellow Dish")

        // Caramelle LGPE
        .replace(/\bHealth Candy\b/g, "Caramella vitalità S")
        .replace(/\bHealth Candy L\b/g, "Caramella vitalità M")
        .replace(/\bHealth Candy XL\b/g, "Caramella vitalità L")
        .replace(/\bMighty Candy\b/g, "Caramella potenza S")
        .replace(/\bMighty Candy L\b/g, "Caramella potenza M")
        .replace(/\bMighty Candy XL\b/g, "Caramella potenza L")
        .replace(/\bTough Candy\b/g, "Caramella protezione S")
        .replace(/\bTough Candy L\b/g, "Caramella protezione M")
        .replace(/\bTough Candy XL\b/g, "Caramella protezione L")
        .replace(/\bSmart Candy\b/g, "Caramella acume S")
        .replace(/\bSmart Candy L\b/g, "Caramella acume M")
        .replace(/\bSmart Candy XL\b/g, "Caramella acume L")
        .replace(/\bCourage Candy\b/g, "Caramella intuito S")
        .replace(/\bCourage Candy L\b/g, "Caramella intuito M")
        .replace(/\bCourage Candy XL\b/g, "Caramella intuito L")
        .replace(/\bQuick Candy\b/g, "Caramella rapidità S")
        .replace(/\bQuick Candy L\b/g, "Caramella rapidità M")
        .replace(/\bQuick Candy XL\b/g, "Caramella rapidità L")

        // Mochi
        .replace(/\bHealth Mochi\b/g, "Mochi della salute")
        .replace(/\bMuscle Mochi\b/g, "Mochi della potenza")
        .replace(/\bResist Mochi\b/g, "Mochi della tutela")
        .replace(/\bGenius Mochi\b/g, "Mochi dell'ingegno")
        .replace(/\bClever Mochi\b/g, "Mochi dell'intuito")
        .replace(/\bSwift Mochi\b/g, "Mochi della reazione")
        .replace(/\bFresh-Start Mochi\b/g, "Mochi del ripristino")

        // Poteri Rotom
        .replace(/\bRoto Bargain\b/g, "Sconto'n'roll")
        .replace(/\bRoto Boost\b/g, "Stat'n'roll")
        .replace(/\bRoto Catch\b/g, "Acchiappa'n'roll")
        .replace(/\bRoto Encounter\b/g, "Incontra'n'roll")
        .replace(/\bRoto Exp. Points\b/g, "Esp'n'roll")
        .replace(/\bRoto Friendship\b/g, "Affetto'n'roll")
        .replace(/\bRoto HP Restore\b/g, "PS'n'roll")
        .replace(/\bRoto Hatch\b/g, "Cova'n'roll")
        .replace(/\bRoto PP Restore\b/g, "PP'n'roll")
        .replace(/\bRoto Prize Money\b/g, "Soldi'n'roll")
        .replace(/\bRoto Stealth\b/g, "Repelle'n'roll")

        // Mente
        .replace(/\bHardy Mint\b/g, "Menta Ardita")
        .replace(/\bLonely Mint\b/g, "Menta Schiva")
        .replace(/\bBrave Mint\b/g, "Menta Audace")
        .replace(/\bAdamant Mint\b/g, "Menta Decisa")
        .replace(/\bNaughty Mint\b/g, "Menta Birbona")
        .replace(/\bBold Mint\b/g, "Menta Sicura")
        .replace(/\bDocile Mint\b/g, "Menta Docile")
        .replace(/\bRelaxed Mint\b/g, "Menta Placida")
        .replace(/\bImpish Mint\b/g, "Menta Scaltra")
        .replace(/\bLax Mint\b/g, "Menta Fiacca")
        .replace(/\bTimid Mint\b/g, "Menta Timida")
        .replace(/\bHasty Mint\b/g, "Menta Lesta")
        .replace(/\bSerious Mint\b/g, "Menta Seria")
        .replace(/\bJolly Mint\b/g, "Menta Allegra")
        .replace(/\bNaive Mint\b/g, "Menta Ingenua")
        .replace(/\bModest Mint\b/g, "Menta Modesta")
        .replace(/\bMild Mint\b/g, "Menta Mite")
        .replace(/\bQuiet Mint\b/g, "Menta Quieta")
        .replace(/\bBashful Mint\b/g, "Menta Ritrosa")
        .replace(/\bRash Mint\b/g, "Menta Ardente")
        .replace(/\bCalm Mint\b/g, "Menta Calma")
        .replace(/\bGentle Mint\b/g, "Menta Gentile")
        .replace(/\bSassy Mint\b/g, "Menta Vivace")
        .replace(/\bCareful Mint\b/g, "Menta Cauta")
        .replace(/\bQuirky Mint\b/g, "Menta Furba")

        // Materiali per MT
        .replace(/\bVenonat Fang\b/g, "Zanna di Venonat")
        .replace(/\bDiglett Dirt\b/g, "Terra di Diglett")
        .replace(/\bMeowth Fur\b/g, "Pelo di Meowth")
        .replace(/\bPsyduck Down\b/g, "Piuma di Psyduck")
        .replace(/\bMankey Fur\b/g, "Pelo di Mankey")
        .replace(/\bGrowlithe Fur\b/g, "Pelo di Growlithe")
        .replace(/\bSlowpoke Claw\b/g, "Artiglio di Slowpoke")
        .replace(/\bMagnemite Screw\b/g, "Vite di Magnemite")
        .replace(/\bGrimer Toxin\b/g, "Tossine di Grimer")
        .replace(/\bShellder Pearl\b/g, "Perla di Shellder")
        .replace(/\bGastly Gas\b/g, "Gas di Gastly")
        .replace(/\bDrowzee Fur\b/g, "Pelo di Drowzee")
        .replace(/\bVoltorb Sparks\b/g, "Elettricità di Voltorb")
        .replace(/\bScyther Claw\b/g, "Artiglio di Scyther")
        .replace(/\bTauros Hair\b/g, "Pelo di Tauros")
        .replace(/\bMagikarp Scales\b/g, "Squama di Magikarp")
        .replace(/\bDitto Goo\b/g, "Appiccicume di Ditto")
        .replace(/\bEevee Fur\b/g, "Pelo di Eevee")
        .replace(/\bDratini Scales\b/g, "Squama di Dratini")
        .replace(/\bPichu Fur\b/g, "Pelo di Pichu")
        .replace(/\bIgglybuff Fluff\b/g, "Pelo di Igglybuff")
        .replace(/\bMareep Wool\b/g, "Lana di Mareep")
        .replace(/\bHoppip Leaf\b/g, "Foglia di Hoppip")
        .replace(/\bSunkern Leaf\b/g, "Foglia di Sunkern")
        .replace(/\bWooper Slime\b/g, "Muco di Wooper")
        .replace(/\bMurkrow Bauble\b/g, "Tesoro di Murkrow")
        .replace(/\bMisdreavus Tears\b/g, "Lacrime di Misdreavus")
        .replace(/\bGirafarig Fur\b/g, "Pelo di Girafarig")
        .replace(/\bPineco Husk\b/g, "Guscio di Pineco")
        .replace(/\bDunsparce Scales\b/g, "Squama di Dunsparce")
        .replace(/\bQwilfish Spines\b/g, "Aculeo di Qwilfish")
        .replace(/\bHeracross Claw\b/g, "Artiglio di Heracross")
        .replace(/\bSneasel Claw\b/g, "Artiglio di Sneasel")
        .replace(/\bTeddiursa Claw\b/g, "Artiglio di Teddiursa")
        .replace(/\bDelibird Parcel\b/g, "Scorte di Delibird")
        .replace(/\bHoundour Fang\b/g, "Zanna di Houndour")
        .replace(/\bPhanpy Nail\b/g, "Unghia di Phanpy")
        .replace(/\bStantler Hair\b/g, "Pelo di Stantler")
        .replace(/\bLarvitar Claw\b/g, "Artiglio di Larvitar")
        .replace(/\bWingull Feather\b/g, "Penna di Wingull")
        .replace(/\bRalts Dust\b/g, "Oggetto di Ralts")
        .replace(/\bSurskit Syrup\b/g, "Sciroppo di Surskit")
        .replace(/\bShroomish Spores\b/g, "Spore di Shroomish")
        .replace(/\bSlakoth Fur\b/g, "Pelo di Slakoth")
        .replace(/\bMakuhita Sweat\b/g, "Sudore di Makuhita")
        .replace(/\bAzurill Fur\b/g, "Pelo di Azurill")
        .replace(/\bSableye Gem\b/g, "Gemma di Sableye")
        .replace(/\bMeditite Sweat\b/g, "Sudore di Meditite")
        .replace(/\bGulpin Mucus\b/g, "Muco di Gulpin")
        .replace(/\bNumel Lava\b/g, "Lava di Numel")
        .replace(/\bTorkoal Coal\b/g, "Carbone di Torkoal")
        .replace(/\bSpoink Pearl\b/g, "Perla di Spoink")
        .replace(/\bCacnea Needle\b/g, "Spina di Cacnea")
        .replace(/\bSwablu Fluff\b/g, "Piuma di Swablu")
        .replace(/\bZangoose Claw\b/g, "Artiglio di Zangoose")
        .replace(/\bSeviper Fang\b/g, "Zanna di Seviper")
        .replace(/\bBarboach Slime\b/g, "Muco di Barboach")
        .replace(/\bShuppet Scrap\b/g, "Brandello di Shuppet")
        .replace(/\bTropius Leaf\b/g, "Foglia di Tropius")
        .replace(/\bSnorunt Fur\b/g, "Pelo di Snorunt")
        .replace(/\bLuvdisc Scales\b/g, "Squama di Luvdisc")
        .replace(/\bBagon Scales\b/g, "Squama di Bagon")
        .replace(/\bStarly Feather\b/g, "Penna di Starly")
        .replace(/\bKricketot Shell\b/g, "Esuvia di Kricketot")
        .replace(/\bShinx Fang\b/g, "Zanna di Shinx")
        .replace(/\bCombee Honey\b/g, "Nettare di Combee")
        .replace(/\bPachirisu Fur\b/g, "Pelo di Pachirisu")
        .replace(/\bBuizel Fur\b/g, "Pelo di Buizel")
        .replace(/\bShellos Mucus\b/g, "Bava di Shellos")
        .replace(/\bDrifloon Gas\b/g, "Gas di Drifloon")
        .replace(/\bStunky Fur\b/g, "Pelo di Stunky")
        .replace(/\bBronzor Fragment\b/g, "Frammento di Bronzor")
        .replace(/\bBonsly Tears\b/g, "Lacrime di Bonsly")
        .replace(/\bHappiny Dust\b/g, "Oggetto di Happiny")
        .replace(/\bSpiritomb Fragment\b/g, "Frammento di Spiritomb")
        .replace(/\bGible Scales\b/g, "Squama di Gible")
        .replace(/\bRiolu Fur\b/g, "Pelo di Riolu")
        .replace(/\bHippopotas Sand\b/g, "Sabbia di Hippopotas")
        .replace(/\bCroagunk Poison\b/g, "Tossine di Croagunk")
        .replace(/\bFinneon Scales\b/g, "Squama di Finneon")
        .replace(/\bSnover Berries\b/g, "Bacca di Snover")
        .replace(/\bRotom Sparks\b/g, "Elettricità di Rotom")
        .replace(/\bPetilil Leaf\b/g, "Foglia di Petilil")
        .replace(/\bBasculin Fang\b/g, "Dente di Basculin")
        .replace(/\bSandile Claw\b/g, "Artiglio di Sandile")
        .replace(/\bZorua Fur\b/g, "Pelo di Zorua")
        .replace(/\bGothita Eyelash\b/g, "Ciglia di Gothita")
        .replace(/\bDeerling Hair\b/g, "Pelo di Deerling")
        .replace(/\bFoongus Spores\b/g, "Spore di Foongus")
        .replace(/\bAlomomola Mucus\b/g, "Muco di Alomomola")
        .replace(/\bTynamo Slime\b/g, "Muco di Tynamo")
        .replace(/\bAxew Scales\b/g, "Squama di Axew")
        .replace(/\bCubchoo Fur\b/g, "Pelo di Cubchoo")
        .replace(/\bCryogonal Ice\b/g, "Ghiaccio di Cryogonal")
        .replace(/\bPawniard Blade\b/g, "Lama di Pawniard")
        .replace(/\bRufflet Feather\b/g, "Penna di Rufflet")
        .replace(/\bDeino Scales\b/g, "Squama di Deino")
        .replace(/\bLarvesta Fuzz\b/g, "Pelo di Larvesta")
        .replace(/\bFletchling Feather\b/g, "Penna di Fletchling")
        .replace(/\bScatterbug Powder\b/g, "Polvere di Scatterbug")
        .replace(/\bLitleo Tuft\b/g, "Crine di Litleo")
        .replace(/\bFlabébé Pollen\b/g, "Polline di Flabébé")
        .replace(/\bSkiddo Leaf\b/g, "Foglia di Skiddo")
        .replace(/\bSkrelp Kelp\b/g, "Alga di Skrelp")
        .replace(/\bClauncher Claw\b/g, "Chela di Clauncher")
        .replace(/\bHawlucha Down\b/g, "Piuma di Hawlucha")
        .replace(/\bDedenne Fur\b/g, "Pelo di Dedenne")
        .replace(/\bGoomy Goo\b/g, "Bava di Goomy")
        .replace(/\bKlefki Key\b/g, "Chiave di Klefki")
        .replace(/\bBergmite Ice\b/g, "Ghiaccio di Bergmite")
        .replace(/\bNoibat Fur\b/g, "Pelo di Noibat")
        .replace(/\bYungoos Fur\b/g, "Pelo di Yungoos")
        .replace(/\bCrabrawler Shell\b/g, "Carapace di Crabrawler")
        .replace(/\bOricorio Feather\b/g, "Penna di Oricorio")
        .replace(/\bRockruff Rock\b/g, "Roccia di Rockruff")
        .replace(/\bMareanie Spike\b/g, "Aculeo di Mareanie")
        .replace(/\bMudbray Mud\b/g, "Fango di Mudbray")
        .replace(/\bFomantis Leaf\b/g, "Foglia di Fomantis")
        .replace(/\bSalandit Gas\b/g, "Gas di Salandit")
        .replace(/\bBounsweet Sweat\b/g, "Sudore di Bounsweet")
        .replace(/\bOranguru Fur\b/g, "Pelo di Oranguru")
        .replace(/\bPassimian Fur\b/g, "Pelo di Passimian")
        .replace(/\bSandygast Sand\b/g, "Sabbia di Sandygast")
        .replace(/\bKomala Claw\b/g, "Artiglio di Komala")
        .replace(/\bMimikyu Scrap\b/g, "Brandello di Mimikyu")
        .replace(/\bBruxish Tooth\b/g, "Dente di Bruxish")
        .replace(/\bChewtle Claw\b/g, "Unghia di Chewtle")
        .replace(/\bSkwovet Fur\b/g, "Pelo di Skwovet")
        .replace(/\bArrokuda Scales\b/g, "Squama di Arrokuda")
        .replace(/\bRookidee Feather\b/g, "Penna di Rookidee")
        .replace(/\bToxel Sparks\b/g, "Elettricità di Toxel")
        .replace(/\bFalinks Sweat\b/g, "Sudore di Falinks")
        .replace(/\bCufant Tarnish\b/g, "Ruggine di Cufant")
        .replace(/\bRolycoly Coal\b/g, "Carbone di Rolycoly")
        .replace(/\bSilicobra Sand\b/g, "Sabbia di Silicobra")
        .replace(/\bIndeedee Fur\b/g, "Pelo di Indeedee")
        .replace(/\bPincurchin Spines\b/g, "Aculeo di Pincurchin")
        .replace(/\bSnom Thread\b/g, "Filo di Snom")
        .replace(/\bImpidimp Hair\b/g, "Pelo di Impidimp")
        .replace(/\bApplin Juice\b/g, "Succo di Applin")
        .replace(/\bSinistea Chip\b/g, "Coccio di Sinistea")
        .replace(/\bHatenna Dust\b/g, "Oggetto di Hatenna")
        .replace(/\bStonjourner Stone\b/g, "Roccia di Stonjourner")
        .replace(/\bEiscue Down\b/g, "Piuma di Eiscue")
        .replace(/\bDreepy Powder\b/g, "Polvere di Dreepy")
        .replace(/\bLechonk Hair\b/g, "Pelo di Lechonk")
        .replace(/\bTarountula Thread\b/g, "Filo di Tarountula")
        .replace(/\bNymble Claw\b/g, "Artiglio di Nymble")
        .replace(/\bPawmi Fur\b/g, "Pelo di Pawmi")
        .replace(/\bTandemaus Fur\b/g, "Pelo di Tandemaus")
        .replace(/\bFidough Fur\b/g, "Pelo di Fidough")
        .replace(/\bSmoliv Oil\b/g, "Olio di Smoliv")
        .replace(/\bSquawkabilly Feather\b/g, "Penna di Squawkabilly")
        .replace(/\bNacli Salt\b/g, "Sale di Nacli")
        .replace(/\bCharcadet Soot\b/g, "Fuliggine di Charcadet")
        .replace(/\bTadbulb Mucus\b/g, "Muco di Tadbulb")
        .replace(/\bWattrel Feather\b/g, "Penna di Wattrel")
        .replace(/\bMaschiff Fang\b/g, "Zanna di Maschiff")
        .replace(/\bShroodle Ink\b/g, "Inchiostro di Shroodle")
        .replace(/\bBramblin Twig\b/g, "Ramoscello di Bramblin")
        .replace(/\bToedscool Flaps\b/g, "Pieghe di Toedscool")
        .replace(/\bKlawf Claw\b/g, "Chela di Klawf")
        .replace(/\bCapsakid Seed\b/g, "Seme di Capsakid")
        .replace(/\bRellor Mud\b/g, "Fango di Rellor")
        .replace(/\bFlittle Down\b/g, "Piuma di Flittle")
        .replace(/\bTinkatink Hair\b/g, "Pelo di Tinkatink")
        .replace(/\bWiglett Sand\b/g, "Sabbia di Wiglett")
        .replace(/\bBombirdier Feather\b/g, "Penna di Bombirdier")
        .replace(/\bFinizen Mucus\b/g, "Muco di Finizen")
        .replace(/\bVaroom Fume\b/g, "Gas di Varoom")
        .replace(/\bCyclizar Scales\b/g, "Squama di Cyclizar")
        .replace(/\bOrthworm Tarnish\b/g, "Ruggine di Orthworm")
        .replace(/\bGlimmet Crystal\b/g, "Cristallo di Glimmet")
        .replace(/\bGreavard Wax\b/g, "Cera di Greavard")
        .replace(/\bFlamigo Down\b/g, "Piuma di Flamigo")
        .replace(/\bCetoddle Grease\b/g, "Grasso di Cetoddle")
        .replace(/\bVeluza Fillet\b/g, "Filetto di Veluza")
        .replace(/\bDondozo Whisker\b/g, "Barbiglio di Dondozo")
        .replace(/\bTatsugiri Scales\b/g, "Squama di Tatsugiri")
        .replace(/\bFrigibax Scales\b/g, "Squama di Frigibax")
        .replace(/\bGimmighoul Coin\b/g, "Moneta di Gimmighoul")
        .replace(/\bEkans Fang\b/g, "Zanna di Ekans")
        .replace(/\bSandshrew Claw\b/g, "Artiglio di Sandshrew")
        .replace(/\bVulpix Fur\b/g, "Pelo di Vulpix")
        .replace(/\bPoliwag Slime\b/g, "Muco di Poliwag")
        .replace(/\bBellsprout Vine\b/g, "Viticcio di Bellsprout")
        .replace(/\bGeodude Fragment\b/g, "Frammento di Geodude")
        .replace(/\bKoffing Gas\b/g, "Gas di Koffing")
        .replace(/\bSentret Fur\b/g, "Pelo di Sentret")
        .replace(/\bHoothoot Feather\b/g, "Penna di Hoothoot")
        .replace(/\bSpinarak Thread\b/g, "Filo di Spinarak")
        .replace(/\bCleffa Fur\b/g, "Pelo di Cleffa")
        .replace(/\bAipom Hair\b/g, "Pelo di Aipom")
        .replace(/\bYanma Spike\b/g, "Aculeo di Yanma")
        .replace(/\bGligar Fang\b/g, "Zanna di Gligar")
        .replace(/\bSlugma Lava\b/g, "Lava di Slugma")
        .replace(/\bSwinub Hair\b/g, "Pelo di Swinub")
        .replace(/\bPoochyena Fang\b/g, "Zanna di Poochyena")
        .replace(/\bLotad Leaf\b/g, "Foglia di Lotad")
        .replace(/\bSeedot Stem\b/g, "Picciolo di Seedot")
        .replace(/\bNosepass Fragment\b/g, "Frammento di Nosepass")
        .replace(/\bVolbeat Fluid\b/g, "Fluido di Volbeat")
        .replace(/\bIllumise Fluid\b/g, "Fluido di Illumise")
        .replace(/\bCorphish Shell\b/g, "Carapace di Corphish")
        .replace(/\bFeebas Scales\b/g, "Squama di Feebas")
        .replace(/\bDuskull Fragment\b/g, "Frammento di Duskull")
        .replace(/\bChingling Fragment\b/g, "Frammento di Chingling")
        .replace(/\bMunchlax Fang\b/g, "Zanna di Munchlax")
        .replace(/\bTimburr Sweat\b/g, "Sudore di Timburr")
        .replace(/\bSewaddle Leaf\b/g, "Foglia di Sewaddle")
        .replace(/\bDucklett Feather\b/g, "Penne di Ducklett")
        .replace(/\bLitwick Soot\b/g, "Fuliggine di Litwick")
        .replace(/\bMienfoo Claw\b/g, "Artiglio di Mienfoo")
        .replace(/\bVullaby Feather\b/g, "Penna di Vullaby")
        .replace(/\bCarbink Jewel\b/g, "Gemma di Carbink")
        .replace(/\bPhantump Twig\b/g, "Ramo di Phantump")
        .replace(/\bGrubbin Thread\b/g, "Filo di Grubbin")
        .replace(/\bCutiefly Powder\b/g, "Polvere di Cutiefly")
        .replace(/\bJangmo-o Scales\b/g, "Squama di Jangmo-o")
        .replace(/\bCramorant Down\b/g, "Piuma di Cramorant")
        .replace(/\bMorpeko Snack\b/g, "Seme di Morpeko")
        .replace(/\bPoltchageist Powder\b/g, "Polvere di Poltchageist")
        .replace(/\bOddish Leaf\b/g, "Foglia di Oddish")
        .replace(/\bTentacool Stinger\b/g, "Aculeo di Tentacool")
        .replace(/\bDoduo Down\b/g, "Piuma di Doduo")
        .replace(/\bSeel Fur\b/g, "Pelo di Seel")
        .replace(/\bExeggcute Shell\b/g, "Guscio di Exeggcute")
        .replace(/\bRhyhorn Fang\b/g, "Zanna di Rhyhorn")
        .replace(/\bHorsea Ink\b/g, "Inchiostro di Horsea")
        .replace(/\bLapras Teardrop\b/g, "Lacrime di Lapras")
        .replace(/\bPorygon Fragment\b/g, "Frammento di Porygon")
        .replace(/\bChinchou Sparks\b/g, "Elettricità di Chinchou")
        .replace(/\bSnubbull Hair\b/g, "Pelo di Snubbull")
        .replace(/\bSkarmory Feather\b/g, "Penna di Skarmory")
        .replace(/\bSmeargle Paint\b/g, "Pittura di Smeargle")
        .replace(/\bTyrogue Sweat\b/g, "Sudore di Tyrogue")
        .replace(/\bElekid Fur\b/g, "Pelo di Elekid")
        .replace(/\bMagby Hair\b/g, "Pelo di Magby")
        .replace(/\bPlusle Fur\b/g, "Pelo di Plusle")
        .replace(/\bMinun Fur\b/g, "Pelo di Minun")
        .replace(/\bTrapinch Shell\b/g, "Guscio di Trapinch")
        .replace(/\bBeldum Claw\b/g, "Artiglio di Beldum")
        .replace(/\bCranidos Spike\b/g, "Punta di Cranidos")
        .replace(/\bShieldon Claw\b/g, "Artiglio di Shieldon")
        .replace(/\bBlitzle Mane Hair\b/g, "Crine di Blitzle")
        .replace(/\bDrilbur Claw\b/g, "Artiglio di Drilbur")
        .replace(/\bCottonee Fluff\b/g, "Lanugine di Cottonee")
        .replace(/\bScraggy Sweat\b/g, "Sudore di Scraggy")
        .replace(/\bMinccino Fur\b/g, "Pelo di Minccino")
        .replace(/\bSolosis Gel\b/g, "Gel di Solosis")
        .replace(/\bJoltik Thread\b/g, "Filo di Joltik")
        .replace(/\bGolett Shard\b/g, "Frammento di Golett")
        .replace(/\bEspurr Fur\b/g, "Pelo di Espurr")
        .replace(/\bInkay Ink\b/g, "Inchiostro di Inkay")
        .replace(/\bPikipek Feather\b/g, "Penna di Pikipek")
        .replace(/\bDewpider Thread\b/g, "Filo di Dewpider")
        .replace(/\bComfey Flower\b/g, "Fiore di Comfey")
        .replace(/\bMinior Shell\b/g, "Guscio di Minior")
        .replace(/\bMilcery Cream\b/g, "Panna di Milcery")
        .replace(/\bDuraludon Tarnish\b/g, "Ruggine di Duraludon")

        // Sedie ???
        .replace(/\bSimple Chairs\b/g, "Sedie semplici")
        .replace(/\bAcademy Chairs\b/g, "Sedie accademia")
        .replace(/\bAcademy Chairs\b/g, "Sedie accademia")
        .replace(/\bWhimsical Chairs\b/g, "Sedie carine")
        .replace(/\bLeafy Chairs\b/g, "Sedie natura")
        .replace(/\bSpooky Chairs\b/g, "Sedie dispetto")
        .replace(/\bPlaid Chairs \(Y\)\b/g, "Sedie a quadri gialle")
        .replace(/\bPlaid Chairs \(B\)\b/g, "Sedie a quadri viola")
        .replace(/\bPlaid Chairs \(R\)\b/g, "Sedie a quadri rosse")
        .replace(/\bB&W Grass Chairs\b/g, "Sedie erba alta")
        .replace(/\bBattle Chairs\b/g, "Sedie sfida")
        .replace(/\bMonstrous Chairs\b/g, "Sedie mostruose")
        .replace(/\bStriped Chairs\b/g, "Sedie a righe")
        .replace(/\bDiamond Chairs\b/g, "Sedie a rombi")
        .replace(/\bPolka-Dot Chairs\b/g, "Sedie a pois")
        .replace(/\bLilac Chairs\b/g, "Sedie lilla")
        .replace(/\bMint Chairs\b/g, "Sedie menta")
        .replace(/\bPeach Chairs\b/g, "Sedie pesca")
        .replace(/\bYellow Chairs\b/g, "Sedie gialle")
        .replace(/\bBlue Chairs\b/g, "Sedie blu")
        .replace(/\bPink Chairs\b/g, "Sedie rosa")

        // Varie ed eventuali
        .replace(/\bTM(\d{2,3})\b/gi, "MT$1")
        .replace(/\bHM(\d{2,3})\b/gi, "MN$1")
        .replace(/\bTR(\d{2,3})\b/gi, "DT$1")
        .replace(/\{\{DL\|([\w-\s]+)\|([\w\s]+)\}\}/gi, "[[$1#$2|$2]]")
        .replace(
          /Evolution\-inducing held item/gi,
          "Strumenti tenuti che provocano Evoluzione",
        );
    }

    str = str
      // Strumenti tenuti - Gen II
      .replace(/\bBright ?Powder\b/g, "Luminpolvere")
      .replace(/\bQuick Claw\b/g, "Rapidartiglio")
      .replace(/\bKing's Rock\b/g, "Roccia di re")
      .replace(/\bSilver ?Powder\b/g, "Argenpolvere")
      .replace(/\bAmulet Coin\b/g, "Monetamuleto")
      .replace(/\bCleanse Tag\b/g, "Velopuro")
      .replace(/\bSmoke Ball\b/g, "Palla fumo")
      .replace(/\bEverstone\b/g, "Pietrastante")
      .replace(/\bFocus Band\b/g, "Bandana")
      .replace(/\bFocus Sash\b/g, "Focalnastro")
      .replace(/\bLucky Egg\b/g, "Fortunuovo")
      .replace(/\bScope Lens\b/g, "Mirino")
      .replace(/\bMetal Coat\b/g, "Metalcoperta")
      .replace(/\bLeftovers\b/g, "Avanzi")
      .replace(/\bDragon Scale\b/g, "Squama Drago")
      .replace(/\bLight Ball\b/g, "Elettropalla")
      .replace(/\bSoft Sand\b/g, "Sabbia Soffice")
      .replace(/\bHard Stone\b/g, "Pietradura")
      .replace(/\bMiracle Seed\b/g, "Miracolseme")
      .replace(/\bBlack ?Glasses\b/g, "Occhialineri")
      .replace(/\bBlack ?[Bb]elt\b/g, "Cinturanera")
      .replace(/\bMagnet\b/g, "Calamita")
      .replace(/\bMystic Water\b/g, "Acqua magica")
      .replace(/\bSharp Beak\b/g, "Beccaffilato")
      .replace(/\bPoison Barb\b/g, "Velenaculeo")
      .replace(/\bNever\-Melt Ice\b/g, "Gelomai")
      .replace(/\bNever[Mm]elt[Ii]ce\b/g, "Gelomai")
      .replace(/\bSpell Tag\b/g, "Spettrotarga")
      .replace(/\bTwisted ?Spoon\b/g, "Cucchiaio Torto")
      .replace(/\bCharcoal\b/g, "Carbonella")
      .replace(/\bDragon Fang\b/g, "Dentedidrago")
      .replace(/\bPink Bow\b/g, "Fiocco Rosa")
      .replace(/\bPolkadot Bow\b/g, "Fiocco Pois")
      .replace(/\bUp\-Grade\b/g, "Upgrade")
      .replace(/\bLucky Punch\b/g, "Fortunpugno")
      .replace(/\bMetal Powder\b/g, "Metalpolvere")
      .replace(/\bThick Club\b/g, "Ossospesso")
      .replace(/\b(Leek|Stick)\b/g, "Gambo")
      .replace(/\bBerserk Gene\b/g, "Gene Furioso")

      // Strumenti tenuti - Gen III
      .replace(/\bWhite Herb\b/g, "Erbachiara")
      .replace(/\bMacho Brace\b/g, "Crescicappa")
      .replace(/\bSoothe Bell\b/g, "Calmanella")
      .replace(/\bMental Herb\b/g, "Mentalerba")
      .replace(/\bChoice Band\b/g, "Bendascelta")
      .replace(/\bSoul Dew\b/g, "Cuorugiada")
      .replace(/\bDeep\s?Sea\s?Tooth\b/g, "Denteabissi")
      .replace(/\bDeep\s?Sea\s?Scale\b/g, "Squamabissi")
      .replace(/\bSilk Scarf\b/g, "Sciarpa seta")
      .replace(/\bShell Bell\b/g, "Conchinella")
      .replace(/\bSea Incense\b/g, "Marearoma")
      .replace(/\bLax Incense\b/g, "Distraroma")
      .replace(/\bRed Scarf\b/g, "Fascia Rossa")
      .replace(/\bBlue Scarf\b/g, "Fascia Blu")
      .replace(/\bPink Scarf\b/g, "Fascia Rosa")
      .replace(/\bGreen Scarf\b/g, "Fascia Verde")
      .replace(/\bYellow Scarf\b/g, "Fascia Gialla")

      // Strumenti tenuti - Gen IV
      .replace(/\bFlame Plate\b/g, "Lastrarogo")
      .replace(/\bSplash Plate\b/g, "Lastraidro")
      .replace(/\bZap Plate\b/g, "Lastrasaetta")
      .replace(/\bMeadow Plate\b/g, "Lastraprato")
      .replace(/\bIcicle Plate\b/g, "Lastragelo")
      .replace(/\bFist Plate\b/g, "Lastrapugno")
      .replace(/\bToxic Plate\b/g, "Lastrafiele")
      .replace(/\bEarth Plate\b/g, "Lastrageo")
      .replace(/\bSky Plate\b/g, "Lastracielo")
      .replace(/\bMind Plate\b/g, "Lastramente")
      .replace(/\bInsect Plate\b/g, "Lastrabaco")
      .replace(/\bStone Plate\b/g, "Lastrapietra")
      .replace(/\bSpooky Plate\b/g, "Lastratetra")
      .replace(/\bDraco Plate\b/g, "Lastradrakon")
      .replace(/\bDread Plate\b/g, "Lastratimore")
      .replace(/\bIron Plate\b/g, "Lastraferro")
      .replace(/\bFerro Plate\b/g, "Lastraferro")
      .replace(/\bOdd Incense\b/g, "Bizzoaroma")
      .replace(/\bRock Incense\b/g, "Roccioaroma")
      .replace(/\bFull Incense\b/g, "Gonfioaroma")
      .replace(/\bWave Incense\b/g, "Ondaroma")
      .replace(/\bRose Incense\b/g, "Rosaroma")
      .replace(/\bLuck Incense\b/g, "Fortunaroma")
      .replace(/\bPure Incense\b/g, "Puroaroma")
      .replace(/\bProtector\b/g, "Copertura")
      .replace(/\bElectirizer\b/g, "Elettritore")
      .replace(/\bMagmarizer\b/g, "Magmatore")
      .replace(/\bDubious Disc\b/g, "Dubbiodisco")
      .replace(/\bReaper Cloth\b/g, "Terrorpanno")
      .replace(/\bRazor Claw\b/g, "Affilartiglio")
      .replace(/\bRazor Fang\b/g, "Affilodente")
      .replace(/\bAdamant Orb\b/g, "Adamasfera")
      .replace(/\bLustrous Orb\b/g, "Splendisfera")
      .replace(/\bGriseous Orb\b/g, "Grigiosfera")
      .replace(/\bWide Lens\b/g, "Grandelente")
      .replace(/\bMuscle Band\b/g, "Muscolbanda")
      .replace(/\bWise Glasses\b/g, "Saviocchiali")
      .replace(/\bExpert Belt\b/g, "Abilcintura")
      .replace(/\bLight Clay\b/g, "Creta Luce")
      .replace(/\bLife Orb\b/g, "Assorbisfera")
      .replace(/\bPower Herb\b/g, "Vigorerba")
      .replace(/\bToxic Orb\b/g, "Tossicsfera")
      .replace(/\bFlame Orb\b/g, "Fiammosfera")
      .replace(/\bQuick Powder\b/g, "Velopolvere")
      .replace(/\bZoom Lens\b/g, "Zoomlente")
      .replace(/\bMetronome\b/g, "Plessimetro")
      .replace(/\bIron Ball\b/g, "Ferropalla")
      .replace(/\bFerro Ball\b/g, "Ferropalla")
      .replace(/\bLagging Tail\b/g, "Rallentocoda")
      .replace(/\bDestiny Knot\b/g, "Destincomune")
      .replace(/\bBlack Sludge\b/g, "Fangopece")
      .replace(/\bIcy Rock\b/g, "Rocciafredda")
      .replace(/\bSmooth Rock\b/g, "Roccialiscia")
      .replace(/\bHeat Rock\b/g, "Rocciacalda")
      .replace(/\bDamp Rock\b/g, "Rocciaumida")
      .replace(/\bGrip Claw\b/g, "Presartigli")
      .replace(/\bChoice Scarf\b/g, "Stolascelta")
      .replace(/\bSticky Barb\b/g, "Vischiopunta")
      .replace(/\bPower Bracer\b/g, "Vigorcerchio")
      .replace(/\bPower Belt\b/g, "Vigorfascia")
      .replace(/\bPower Lens\b/g, "Vigorlente")
      .replace(/\bPower Band\b/g, "Vigorbanda")
      .replace(/\bPower Anklet\b/g, "Vigorgliera")
      .replace(/\bPower Weight\b/g, "Vigorpeso")
      .replace(/\bShed Shell\b/g, "Disfoguscio")
      .replace(/\bBig Root\b/g, "Granradice")
      .replace(/\bChoice Specs\b/g, "Lentiscelta")

      // Strumenti tenuti - Gen V
      .replace(/\bDouse Drive\b/g, "Idromodulo")
      .replace(/\bShock Drive\b/g, "Voltmodulo")
      .replace(/\bBurn Drive\b/g, "Piromodulo")
      .replace(/\bChill Drive\b/g, "Gelomodulo")
      .replace(/\bPrism Scale\b/g, "Squama Bella")
      .replace(/\bEviolite\b/g, "Evolcondensa")
      .replace(/\bFloat Stone\b/g, "Pietralieve")
      .replace(/\bRocky Helmet\b/g, "Bitorzolelmo")
      .replace(/\bAir Balloon\b/g, "Palloncino")
      .replace(/\bRed Card\b/g, "Cartelrosso")
      .replace(/\bRing Target\b/g, "Facilsaglio")
      .replace(/\bBinding Band\b/g, "Legafascia")
      .replace(/\bAbsorb Bulb\b/g, "Bulbo")
      .replace(/\bCell Battery\b/g, "Ricaripila")
      .replace(/\bEject Button\b/g, "Pulsantefuga")
      .replace(/\bFire Gem\b/g, "Bijoufuoco")
      .replace(/\bWater Gem\b/g, "Bijouacqua")
      .replace(/\bElectric Gem\b/g, "Bijouelettro")
      .replace(/\bGrass Gem\b/g, "Bijouerba")
      .replace(/\bIce Gem\b/g, "Bijoughiac.")
      .replace(/\bFighting Gem\b/g, "Bijoulotta")
      .replace(/\bPoison Gem\b/g, "Bijouveleno")
      .replace(/\bGround Gem\b/g, "Bijouterra")
      .replace(/\bFlying Gem\b/g, "Bijouvolante")
      .replace(/\bPsychic Gem\b/g, "Bijoupsico")
      .replace(/\bBug Gem\b/g, "Bijoucoleot.")
      .replace(/\bRock Gem\b/g, "Bijouroccia")
      .replace(/\bGhost Gem\b/g, "Bijouspettro")
      .replace(/\bDragon Gem\b/g, "Bijoudrago")
      .replace(/\bDark Gem\b/g, "Bijoubuio")
      .replace(/\bSteel Gem\b/g, "Bijouacciaio")
      .replace(/\bNormal Gem\b/g, "Bijounormale")

      // Strumenti tenuti - Gen VI
      .replace(/\bWhipped Dream\b/g, "Dolcespuma")
      .replace(/\bSachet\b/g, "Bustina Aromi")
      .replace(/\bPixie Plate\b/g, "Lastraspiritello")
      .replace(/\bLuminous Moss\b/g, "Muschioluce")
      .replace(/\bSnowball\b/g, "Palla di Neve")
      .replace(/\bAssault Vest\b/g, "Corpetto assalto")
      .replace(/\bSafety Goggles\b/g, "Visierantisabbia")
      .replace(/\bWeakness Policy\b/g, "Vulneropolizza")
      .replace(/\bFairy Gem\b/g, "Bijoufolletto")

      // Strumenti tenuti - Gen VII
      .replace(/\bTerrain Extender\b/g, "Fissacampo")
      .replace(/\bElectric Seed\b/g, "Elettroseme")
      .replace(/\bGrassy Seed\b/g, "Erbaseme")
      .replace(/\bMisty Seed\b/g, "Nebbiaseme")
      .replace(/\bPsychic Seed\b/g, "Psicoseme")
      .replace(/\bProtective Pads\b/g, "Smorzaurti")

      // ROM
      .replace(/\bGrass Memory\b/g, "ROM Erba")
      .replace(/\bWater Memory\b/g, "ROM Acqua")
      .replace(/\bFire Memory\b/g, "ROM Fuoco")
      .replace(/\bFlying Memory\b/g, "ROM Volante")
      .replace(/\bFighting Memory\b/g, "ROM Lotta")
      .replace(/\bGround Memory\b/g, "ROM Terra")
      .replace(/\bDark Memory\b/g, "ROM Buio")
      .replace(/\bDragon Memory\b/g, "ROM Drago")
      .replace(/\bRock Memory\b/g, "ROM Roccia")
      .replace(/\bPoison Memory\b/g, "ROM Veleno")
      .replace(/\bGhost Memory\b/g, "ROM Spettro")
      .replace(/\bPsychic Memory\b/g, "ROM Psico")
      .replace(/\bElectric Memory\b/g, "ROM Elettro")
      .replace(/\bSteel Memory\b/g, "ROM Acciaio")
      .replace(/\bNormal Memory\b/g, "ROM Normale")
      .replace(/\bBug Memory\b/g, "ROM Coleottero")
      .replace(/\bFairy Memory\b/g, "ROM Folletto")
      .replace(/\bIce Memory\b/g, "ROM Ghiaccio")

      // Strumenti tenuti - Gen VIII
      .replace(/\bBlunder Policy\b/g, "Fiascopolizza")
      .replace(/\bThroat Spray\b/g, "Spray gola")
      .replace(/\bRoom Service\b/g, "Distorservizio")
      .replace(/\bHeavy-Duty Boots\b/g, "Scarponi robusti")
      .replace(/\bUtility Umbrella\b/g, "Superombrello")
      .replace(/\bEject Pack\b/g, "Zainofuga")

      // Strumenti tenuti - Gen IX
      .replace(/\bAbility Shield\b/g, "Scudo abilità")
      .replace(/\bPunching Glove\b/g, "Guantone")
      .replace(/\bClear Amulet\b/g, "Ciondolochiaro")
      .replace(/\b(Leek|Stick)\b/g, "Gambo")
      .replace(/\bFairy Feather\b/g, "Piuma fatata")
      .replace(/\bCovert Cloak\b/g, "Anonimanto")
      .replace(/\bLoaded Dice\b/g, "Dado truccato")
      .replace(/\bBooster Energy\b/g, "Capsula energetica")
      .replace(/\bAdamant Crystal\b/g, "Adamasferoide")
      .replace(/\bLustrous Globe\b/g, "Splendisferoide")
      .replace(/\bGriseous Core\b/g, "Grigiosferoide")
      .replace(/\bLeader's Crest\b/g, "Simbolo del capo")

      // Bacche - Gen II - no template
      .replace(/\bGold Berry\b/g, "Bacca Oro")
      .replace(/\bPSNCureBerry\b/g, "Baccantiveleno")
      .replace(/\bPRZCureBerry\b/g, "Baccantiparalisi")
      .replace(/\bMint Berry\b/g, "Bacca Menta")
      .replace(/\bBurnt Berry\b/g, "Bacca Bruciata")
      .replace(/\bIce Berry\b/g, "Bacca Ghiaccio")
      .replace(/\bBitter Berry\b/g, "Bacca Amara")
      .replace(/\bMysteryBerry\b/g, "Bacca Misteriosa")
      .replace(/\bMiracleBerry\b/g, "Bacca Miracolosa")

      // Bacche - Gen II - con template
      .replace(/\{\{b\|Berry\}\}/gi, "[[Bacca]]")
      .replace(/\{\{b\|Gold\}\}/gi, "[[Bacca Oro]]")
      .replace(/\{\{b\|Mint\}\}/gi, "[[Bacca Menta]]")
      .replace(/\{\{b\|Burnt\}\}/gi, "[[Bacca Bruciata]]")
      .replace(/\{\{b\|Ice\}\}/gi, "[[Bacca Ghiaccio]]")
      .replace(/\{\{b\|Bitter\}\}/gi, "[[Bacca Amara]]")

      // Bacche - Gen III - no template
      .replace(/\bCheri Berry\b/g, "Baccaliegia")
      .replace(/\bChesto Berry\b/g, "Baccastagna")
      .replace(/\bPecha Berry\b/g, "Baccapesca")
      .replace(/\bRawst Berry\b/g, "Baccafrago")
      .replace(/\bAspear Berry\b/g, "Baccaperina")
      .replace(/\bLeppa Berry\b/g, "Baccamela")
      .replace(/\bOran Berry\b/g, "Baccarancia")
      .replace(/\bPersim Berry\b/g, "Baccaki")
      .replace(/\bLum Berry\b/g, "Baccaprugna")
      .replace(/\bSitrus Berry\b/g, "Baccacedro")
      .replace(/\bFigy Berry\b/g, "Baccafico")
      .replace(/\bWiki Berry\b/g, "Baccaprugna")
      .replace(/\bMago Berry\b/g, "Baccamango")
      .replace(/\bAguav Berry\b/g, "Baccaguava")
      .replace(/\bIapapa Berry\b/g, "Baccapaia")
      .replace(/\bRazz Berry\b/g, "Baccalampon")
      .replace(/\bBluk Berry\b/g, "Baccamora")
      .replace(/\bNanab Berry\b/g, "Baccabana")
      .replace(/\bWepear Berry\b/g, "Baccapera")
      .replace(/\bPinap Berry\b/g, "Baccananas")
      .replace(/\bPomeg Berry\b/g, "Baccagrana")
      .replace(/\bKelpsy Berry\b/g, "Baccalga")
      .replace(/\bQualot Berry\b/g, "Baccaloquat")
      .replace(/\bHondew Berry\b/g, "Baccamelon")
      .replace(/\bGrepa Berry\b/g, "Baccauva")
      .replace(/\bTamato Berry\b/g, "Baccamodoro")
      .replace(/\bCornn Berry\b/g, "Baccavena")
      .replace(/\bMagost Berry\b/g, "Baccagostan")
      .replace(/\bRabuta Berry\b/g, "Baccambutan")
      .replace(/\bNomel Berry\b/g, "Baccalemon")
      .replace(/\bSpelon Berry\b/g, "Baccamelos")
      .replace(/\bPamtre Berry\b/g, "Baccapalma")
      .replace(/\bWatmel Berry\b/g, "Baccacomero")
      .replace(/\bDurin Berry\b/g, "Baccadurian")
      .replace(/\bBelue Berry\b/g, "Baccartillo")
      .replace(/\bLiechi Berry\b/g, "Baccalici")
      .replace(/\bGanlon Berry\b/g, "Baccalongan")
      .replace(/\bSalac Berry\b/g, "Baccasalak")
      .replace(/\bPetaya Berry\b/g, "Baccapitaya")
      .replace(/\bApicot Berry\b/g, "Baccacocca")
      .replace(/\bLansat Berry\b/g, "Baccalangsa")
      .replace(/\bStarf Berry\b/g, "Baccambola")
      .replace(/\bEnigma Berry\b/g, "Baccaenigma")

      // Bacche - Gen III - con template
      .replace(/\{\{b\|Cheri\}\}/gi, "[[Baccaliegia]]")
      .replace(/\{\{b\|Chesto\}\}/gi, "[[Baccastagna]]")
      .replace(/\{\{b\|Pecha\}\}/gi, "[[Baccapesca]]")
      .replace(/\{\{b\|Rawst\}\}/gi, "[[Baccafrago]]")
      .replace(/\{\{b\|Aspear\}\}/gi, "[[Baccaperina]]")
      .replace(/\{\{b\|Leppa\}\}/gi, "[[Baccamela]]")
      .replace(/\{\{b\|Oran\}\}/gi, "[[Baccarancia]]")
      .replace(/\{\{b\|Persim\}\}/gi, "[[Baccaki]]")
      .replace(/\{\{b\|Lum\}\}/gi, "[[Baccaprugna]]")
      .replace(/\{\{b\|Sitrus\}\}/gi, "[[Baccacedro]]")
      .replace(/\{\{b\|Figy\}\}/gi, "[[Baccafico]]")
      .replace(/\{\{b\|Wiki\}\}/gi, "[[Baccaprugna]]")
      .replace(/\{\{b\|Mago\}\}/gi, "[[Baccamango]]")
      .replace(/\{\{b\|Aguav\}\}/gi, "[[Baccaguava]]")
      .replace(/\{\{b\|Iapapa\}\}/gi, "[[Baccapaia]]")
      .replace(/\{\{b\|Razz\}\}/gi, "[[Baccalampon]]")
      .replace(/\{\{b\|Bluk\}\}/gi, "[[Baccamora]]")
      .replace(/\{\{b\|Nanab\}\}/gi, "[[Baccabana]]")
      .replace(/\{\{b\|Wepear\}\}/gi, "[[Baccapera]]")
      .replace(/\{\{b\|Pinap\}\}/gi, "[[Baccananas]]")
      .replace(/\{\{b\|Pomeg\}\}/gi, "[[Baccagrana]]")
      .replace(/\{\{b\|Kelpsy\}\}/gi, "[[Baccalga]]")
      .replace(/\{\{b\|Qualot\}\}/gi, "[[Baccaloquat]]")
      .replace(/\{\{b\|Hondew\}\}/gi, "[[Baccamelon]]")
      .replace(/\{\{b\|Grepa\}\}/gi, "[[Baccauva]]")
      .replace(/\{\{b\|Tamato\}\}/gi, "[[Baccamodoro]]")
      .replace(/\{\{b\|Cornn\}\}/gi, "[[Baccavena]]")
      .replace(/\{\{b\|Magost\}\}/gi, "[[Baccagostan]]")
      .replace(/\{\{b\|Rabuta\}\}/gi, "[[Baccambutan]]")
      .replace(/\{\{b\|Nomel\}\}/gi, "[[Baccalemon]]")
      .replace(/\{\{b\|Spelon\}\}/gi, "[[Baccamelos]]")
      .replace(/\{\{b\|Pamtre\}\}/gi, "[[Baccapalma]]")
      .replace(/\{\{b\|Watmel\}\}/gi, "[[Baccacomero]]")
      .replace(/\{\{b\|Durin\}\}/gi, "[[Baccadurian]]")
      .replace(/\{\{b\|Belue\}\}/gi, "[[Baccartillo]]")
      .replace(/\{\{b\|Liechi\}\}/gi, "[[Baccalici]]")
      .replace(/\{\{b\|Ganlon\}\}/gi, "[[Baccalongan]]")
      .replace(/\{\{b\|Salac\}\}/gi, "[[Baccasalak]]")
      .replace(/\{\{b\|Petaya\}\}/gi, "[[Baccapitaya]]")
      .replace(/\{\{b\|Apicot\}\}/gi, "[[Baccacocca]]")
      .replace(/\{\{b\|Lansat\}\}/gi, "[[Baccalangsa]]")
      .replace(/\{\{b\|Starf\}\}/gi, "[[Baccambola]]")
      .replace(/\{\{b\|Enigma\}\}/gi, "[[Baccaenigma]]")

      // Bacche - Gen IV - no template
      .replace(/\bOcca Berry\b/g, "Baccacao")
      .replace(/\bPassho Berry\b/g, "Baccapasflo")
      .replace(/\bWacan Berry\b/g, "Baccaparmen")
      .replace(/\bRindo Berry\b/g, "Baccarindo")
      .replace(/\bYache Berry\b/g, "Baccamoya")
      .replace(/\bChople Berry\b/g, "Baccarosmel")
      .replace(/\bKebia Berry\b/g, "Baccakebia")
      .replace(/\bShuca Berry\b/g, "Baccanaca")
      .replace(/\bCoba Berry\b/g, "Baccababa")
      .replace(/\bPayapa Berry\b/g, "Baccapayapa")
      .replace(/\bTanga Berry\b/g, "Baccaitan")
      .replace(/\bCharti Berry\b/g, "Baccaciofo")
      .replace(/\bKasib Berry\b/g, "Baccacitrus")
      .replace(/\bHaban Berry\b/g, "Baccahaban")
      .replace(/\bColbur Berry\b/g, "Baccaxan")
      .replace(/\bBabiri Berry\b/g, "Baccababiri")
      .replace(/\bChilan Berry\b/g, "Baccacinlan")
      .replace(/\bMicle Berry\b/g, "Baccaracolo")
      .replace(/\bCustap Berry\b/g, "Baccacrela")
      .replace(/\bJaboca Berry\b/g, "Baccajaba")
      .replace(/\bRowap Berry\b/g, "Baccaroam")

      // Bacche - Gen IV - con template
      .replace(/\{\{b\|Occa\}\}/gi, "[[Baccacao]]")
      .replace(/\{\{b\|Passho\}\}/gi, "[[Baccapasflo]]")
      .replace(/\{\{b\|Wacan\}\}/gi, "[[Baccaparmen]]")
      .replace(/\{\{b\|Rindo\}\}/gi, "[[Baccarindo]]")
      .replace(/\{\{b\|Yache\}\}/gi, "[[Baccamoya]]")
      .replace(/\{\{b\|Chople\}\}/gi, "[[Baccarosmel]]")
      .replace(/\{\{b\|Kebia\}\}/gi, "[[Baccakebia]]")
      .replace(/\{\{b\|Shuca\}\}/gi, "[[Baccanaca]]")
      .replace(/\{\{b\|Coba\}\}/gi, "[[Baccababa]]")
      .replace(/\{\{b\|Payapa\}\}/gi, "[[Baccapayapa]]")
      .replace(/\{\{b\|Tanga\}\}/gi, "[[Baccaitan]]")
      .replace(/\{\{b\|Charti\}\}/gi, "[[Baccaciofo]]")
      .replace(/\{\{b\|Kasib\}\}/gi, "[[Baccacitrus]]")
      .replace(/\{\{b\|Haban\}\}/gi, "[[Baccahaban]]")
      .replace(/\{\{b\|Colbur\}\}/gi, "[[Baccaxan]]")
      .replace(/\{\{b\|Babiri\}\}/gi, "[[Baccababiri]]")
      .replace(/\{\{b\|Chilan\}\}/gi, "[[Baccacinlan]]")
      .replace(/\{\{b\|Micle\}\}/gi, "[[Baccaracolo]]")
      .replace(/\{\{b\|Custap\}\}/gi, "[[Baccacrela]]")
      .replace(/\{\{b\|Jaboca\}\}/gi, "[[Baccajaba]]")
      .replace(/\{\{b\|Rowap\}\}/gi, "[[Baccaroam]]")

      // Bacche - Gen VI - no template
      .replace(/\bRoseli Berry\b/g, "Baccarcad&egrave;")
      .replace(/\bKee Berry\b/g, "Baccalighia")
      .replace(/\bMaranga Berry\b/g, "Baccapane")

      // Bacche - Gen VI - template
      .replace(/\{\{b\|Roseli\}\}/gi, "[[Baccarcad&egrave;]]")
      .replace(/\{\{b\|Kee\}\}/gi, "[[Baccalighia]]")
      .replace(/\{\{b\|Maranga\}\}/gi, "[[Baccapane]]")

      // Megapietre
      .replace(/\bAbomasite\b/g, "Abomasnowite")
      .replace(/\bAlakazite\b/g, "Alakazamite")
      .replace(/\bBlastoisinite\b/g, "Blastoisite")
      .replace(/\bHeracronite\b/g, "Heracrossite")
      .replace(/\bHoundoominite\b/g, "Houndoomite")
      .replace(/\bLucarionite\b/g, "Lucarite")
      .replace(/\bManectite\b/g, "Manectricite")
      .replace(/\bMewtwonite X\b/g, "Mewtwoite X")
      .replace(/\bMewtwonite Y\b/g, "Mewtwoite Y")
      .replace(/\bSablenite\b/g, "Sableyite")
      .replace(/\bAltarianite\b/g, "Altarite")
      .replace(/\bSharpedonite\b/g, "Sharpedite")
      .replace(/\bSlowbronite\b/g, "Slowbroite")
      .replace(/\bGlalitite\b/g, "Glalite")

      // Cristalli Z
      .replace(/\bBuginium Z\b/g, "Insectium Z")
      .replace(/\bDarkinium Z\b/g, "Obscurium Z")
      .replace(/\bDragonium Z\b/g, "Draconium Z")
      .replace(/\bElectrium Z\b/g, "Electrium Z")
      .replace(/\bFairium Z\b/g, "Follectium Z")
      .replace(/\bFightinium Z\b/g, "Luctium Z")
      .replace(/\bFirium Z\b/g, "Pirium Z")
      .replace(/\bFlyinium Z\b/g, "Volantium Z")
      .replace(/\bGhostium Z\b/g, "Spectrium Z")
      .replace(/\bGrassium Z\b/g, "Herbium Z")
      .replace(/\bGroundium Z\b/g, "Terrium Z")
      .replace(/\bIcium Z\b/g, "Glacium Z")
      .replace(/\bNormalium Z\b/g, "Normium Z")
      .replace(/\bPoisonium Z\b/g, "Venenium Z")
      .replace(/\bPsychium Z\b/g, "Psichium Z")
      .replace(/\bRockium Z\b/g, "Petrium Z")
      .replace(/\bSteelium Z\b/g, "Metallium Z")
      .replace(/\bWaterium Z\b/g, "Idrium Z")
      .replace(/\bPikanium Z\b/g, "Pikacium Z")
      .replace(/\bAloraichium Z\b/g, "Aloraicium Z")
      .replace(/\bEevium Z\b/g, "Eevium Z")
      .replace(/\bSnorlium Z\b/g, "Snorlactium Z")
      //.replace(/Mewnium Z/g, 'Mewnium Z')
      .replace(/\bDecidium Z\b/g, "Deciduenium Z")
      .replace(/\bIncinium Z\b/g, "Incineronium Z")
      .replace(/\bPrimarium Z\b/g, "Primarinium Z")
      .replace(/\bTapunium Z\b/g, "Tapium Z")
      //.replace(/Marshadium Z/g, 'Marshadium Z')
      .replace(/\bLycanium\b/g, "Lycanrochium Z")
      .replace(/\bMimikium Z\b/g, "Mimikyum Z")
      .replace(/\bPikashunium Z\b/g, "Ashpikacium Z")
      .replace(/\bSolganium Z\b/g, "Solgaleium Z")
      // .replace(/\bLunalium Z\b/g, "Lunalium Z")
      // .replace(/\bUltranecrozium Z\b/g, "Ultranecrozium Z")

      // Correzione errori
      .replace(/\bCalamita Pull\b/g, "Magnetismo")

      // Teraliti
      .replace(/\bNormal Tera Shard\b/g, "Teralite Normale")
      .replace(/\bFire Tera Shard\b/g, "Teralite Fuoco")
      .replace(/\bWater Tera Shard\b/g, "Teralite Acqua")
      .replace(/\bElectric Tera Shard\b/g, "Teralite Elettro")
      .replace(/\bGrass Tera Shard\b/g, "Teralite Erba")
      .replace(/\bIce Tera Shard\b/g, "Teralite Ghiaccio")
      .replace(/\bFighting Tera Shard\b/g, "Teralite Lotta")
      .replace(/\bPoison Tera Shard\b/g, "Teralite Veleno")
      .replace(/\bGround Tera Shard\b/g, "Teralite Terra")
      .replace(/\bFlying Tera Shard\b/g, "Teralite Volante")
      .replace(/\bPsychic Tera Shard\b/g, "Teralite Psico")
      .replace(/\bBug Tera Shard\b/g, "Teralite Coleottero")
      .replace(/\bRock Tera Shard\b/g, "Teralite Roccia")
      .replace(/\bGhost Tera Shard\b/g, "Teralite Spettro")
      .replace(/\bDragon Tera Shard\b/g, "Teralite Drago")
      .replace(/\bDark Tera Shard\b/g, "Teralite Buio")
      .replace(/\bSteel Tera Shard\b/g, "Teralite Acciaio")
      .replace(/\bFairy Tera Shard\b/g, "Teralite Folletto")
      .replace(/\bStellar Tera Shard\b/g, "Teralite Astrale")

      // Piume
      .replace(/\bHealth (Wing|Feather)\b/g, "Piumsalute")
      .replace(/\bMuscle (Wing|Feather)\b/g, "Piumpotenza")
      .replace(/\bResist (Wing|Feather)\b/g, "Piumtutela")
      .replace(/\bGenius (Wing|Feather)\b/g, "Piumingegno")
      .replace(/\bClever (Wing|Feather)\b/g, "Piumintuito")
      .replace(/\bSwift (Wing|Feather)\b/g, "Piumreazione")
      .replace(/\bPretty (Wing|Feather)\b/g, "Piumabella")

      // Piastre
      .replace(/\bKanto Slate\b/g, "Piastra di Kanto")
      .replace(/\bJohto Slate\b/g, "Piastra di Johto")
      .replace(/\bDiscovery Slate\b/g, "Piastra degli esordi")
      .replace(/\bSoul Slate\b/g, "Piastra del cuore")
      .replace(/\bGenome Slate\b/g, "Piastra del gene")
      .replace(/\bSquall Slate\b/g, "Piastra dei venti")
      .replace(/\bRainbow Slate\b/g, "Piastra arcobaleno")
      .replace(/\bOceanic Slate\b/g, "Piastra dei mari")
      .replace(/\bTectonic Slate\b/g, "Piastra delle terre")
      .replace(/\bStratospheric Slate\b/g, "Piastra dei cieli")
      .replace(/\bDistortion Slate\b/g, "Piastra distorta")

      // Caramelle Esperienza
      .replace(/\bExp. Candy XS\b/g, "Caram. Esp. XS")
      .replace(/\bExp. Candy S\b/g, "Caram. Esp. S")
      .replace(/\bExp. Candy M\b/g, "Caram. Esp. M")
      .replace(/\bExp. Candy L\b/g, "Caram. Esp. L")
      .replace(/\bExp. Candy XL\b/g, "Caram. Esp. XL")

      // Ghicocche
      .replace(/\bWhite Apricorn\b/g, "Ghicocca Bianca")
      .replace(/\bBlue Apricorn\b/g, "Ghicocca Blu")
      .replace(/\bYellow Apricorn\b/g, "Ghicocca Gialla")
      .replace(/\bBlack Apricorn\b/g, "Ghicocca Nera")
      .replace(/\bPink Apricorn\b/g, "Ghicocca Rosa")
      .replace(/\bRed Apricorn\b/g, "Ghicocca Rossa")
      .replace(/\bGreen Apricorn\b/g, "Ghicocca Verde")

      // Strumenti di LPA
      .replace(/\bTime Balm\b/g, "Sferazen tempo")
      .replace(/\bSpace Balm\b/g, "Sferazen spazio")
      .replace(/\bMysterious Balm\b/g, "Sferazen")
      .replace(/\bLinking Cord\b/g, "Filo dell'unione")
      .replace(/\bHometown Muffin\b/g, "Muffin classico")
      .replace(/\bSpoiled Apricorn\b/g, "Ghicocca bacata")
      .replace(/\bApricorn\b/g, "Bacca ghicocca")
      .replace(/\bJubilife Muffin\b/g, "Muffin Giubilo")
      .replace(/\bAux Powerguard\b/g, "Multi extra")
      .replace(/\bDire Hit\b/g, "Supercolpo")
      .replace(/\bChoice Dumpling\b/g, "Involtoscelta")
      .replace(/\bTwice-Spiced Radish\b/g, "Doppiaceto")
      .replace(/\bSwap Snack\b/g, "Invertigratin")
      .replace(/\bCaster Fern\b/g, "Felcetonda")
      .replace(/\bSeed of Mastery\b/g, "Seme padronanza")
      // .replace(/\bPoké Ball\b/g, "Poké Ball")
      .replace(/\bEternal Ice\b/g, "Ghiaccio perenne")
      .replace(/\bUxie[’']s Claw\b/g, "Artiglio di Uxie")
      .replace(/\bAzelf[’']s Fang\b/g, "Zanna di Azelf")
      .replace(/\bMesprit[’']s Plume\b/g, "Piuma di Mesprit")
      .replace(/\bBlack Tumblestone\b/g, "Ciottolo nero")
      .replace(/\bSky Tumblestone\b/g, "Ciottolo celeste")
      .replace(/\bTumblestone\b/g, "Ciottolo")
      .replace(/\bCelestica Flute\b/g, "Flauto memordei")
      .replace(/\bFine Remedy\b/g, "Preparato buono")
      .replace(/\bSuperb Remedy\b/g, "Preparato ottimo")
      .replace(/\bRemedy\b/g, "Preparato")
      .replace(/\bDazzling Honey\b/g, "Miele luccicante")
      .replace(/\bHearty Grains\b/g, "Spiga rigogliosa")
      .replace(/\bPlump Beans\b/g, "Fagiolo paffuto")
      .replace(/\bSpringy Mushroom\b/g, "Fungo gommoso")
      .replace(/\bCrunchy Salt\b/g, "Minerale duro")
      .replace(/\bWood\b/g, "Legno")
      .replace(/\bKing[’']s Leaf\b/g, "Foglia regina")
      .replace(/\bMarsh Balm\b/g, "Sferazen palude")
      // .replace(/\bPoké Ball\b/g, "Poké Ball")
      .replace(/\bGreat Ball\b/g, "Mega Ball")
      .replace(/\bUltra Ball\b/g, "Ultra Ball")
      .replace(/\bFeather Ball\b/g, "Piuma Ball")
      .replace(/\bPokéshi Doll\b/g, "Pokékokeshi")
      .replace(/\bSmoke Bomb\b/g, "Palla orba")
      .replace(/\bScatter Bang\b/g, "Scoppiosfera")
      .replace(/\bSticky Glob\b/g, "Sfera viscosa")
      .replace(/\bStar Piece\b/g, "Pezzo Stella")
      .replace(/\bBugwort\b/g, "Erba repellente")
      .replace(/\bSuper Potion\b/g, "Superpozione")
      .replace(/\bHyper Potion\b/g, "Iperpozione")
      .replace(/\bMax Potion\b/g, "Pozione Max")
      .replace(/\bPotion\b/g, "Pozione")
      .replace(/\bFull Restore\b/g, "Ricarica totale")
      .replace(/\bOld Gateau\b/g, "Dolce Gateau")
      .replace(/\bJubilife Muffin\b/g, "Muffin Giubilo")
      .replace(/\bFull Heal\b/g, "Cura totale")
      .replace(/\bMax Revive\b/g, "Revitalizz. Max")
      .replace(/\bRevive\b/g, "Revitalizzante")
      .replace(/\bMax Ether\b/g, "Tonico PP")
      .replace(/\bMax Elixir\b/g, "Tonico PP Max")
      .replace(/\bAux Power\b/g, "Offensiva extra")
      .replace(/\bAux Guard\b/g, "Difensiva extra")
      .replace(/\bAux Evasion\b/g, "Elusione X")
      .replace(/\bAux Powerguard\b/g, "Multi extra")
      .replace(/\bForest Balm\b/g, "Sferazen foresta")
      .replace(/\bIron Chunk\b/g, "Pezzo di ferro")
      .replace(/\bFerro Chunk\b/g, "Pezzo di ferro")
      .replace(/\bBall of Mud\b/g, "Palla di fango")
      .replace(/\bPop Pod\b/g, "Scoppiettalga")
      .replace(/\bSootfoot Root\b/g, "Patata fumosa")
      .replace(/\bSnowball\b/g, "Palla di neve")
      .replace(/\bSticky Glob\b/g, "Sfera viscosa")
      .replace(/\bBlack Augurite\b/g, "Augite nera")
      .replace(/\bPeat Block\b/g, "Blocco di torba")
      .replace(/\bStealth Spray\b/g, "Furtivizzante")
      // .replace(/\bMedicinal Leek\b/g, "Porro officinale")
      .replace(/\bMedicinal Gambo\b/g, "Porro officinale")
      .replace(/\bVivichoke\b/g, "Revitalboccio")
      .replace(/\bPep-Up Plant\b/g, "Erba PP")
      .replace(/\bTempting Charm B\b/g, "Amuleto Sostituto 2")
      .replace(/\bTempting Charm P\b/g, "Amuleto Sostituto 3")
      .replace(/\bSwordcap\b/g, "Danzaspaditola")
      .replace(/\bIron Barktongue\b/g, "Ferroscudino")
      .replace(/\bFerro Barktongue\b/g, "Ferroscudino")
      .replace(/\bDoppel Bonnets\b/g, "Doppioteamillo")
      .replace(/\bDireshroom\b/g, "Colpogone")
      .replace(/\bSand Radish\b/g, "Rafano costiero")
      .replace(/\bTempting Charm T\b/g, "Amuleto Sostituto 4")
      .replace(/\bTempting Charm Y\b/g, "Amuleto Sostituto 5")
      .replace(/\bCandy Truffle\b/g, "Tartufo dolce")
      .replace(/\bCake-Lure Base\b/g, "Polpetta base")
      .replace(/\bSmoke Bomb\b/g, "Palla orba")
      .replace(/\bPokéshi Doll\b/g, "Pokékokeshi")
      .replace(/\bVolcano Balm\b/g, "Sferazen vulcano")
      .replace(/\bMountain Balm\b/g, "Sferazen monte")
      .replace(/\bSnow Balm\b/g, "Sferazen neve")
      .replace(/\bHoney Cake\b/g, "Polpetta miele")
      .replace(/\bGrain Cake\b/g, "Polpetta spighe")
      .replace(/\bBean Cake\b/g, "Polpetta fagioli")
      .replace(/\bMushroom Cake\b/g, "Polpetta funghi")
      .replace(/\bSalt Cake\b/g, "Polpetta minerale")
      .replace(/\bSwap Snack\b/g, "Invertigratin")
      .replace(/\bChoice Dumpling\b/g, "Involtoscelta")
      .replace(/\bTwice-Spiced Radish\b/g, "Doppiaceto")
      .replace(/\bSurvival Charm R\b/g, "Amuleto tutela 1")
      .replace(/\bSurvival Charm B\b/g, "Amuleto tutela 2")
      .replace(/\bSurvival Charm P\b/g, "Amuleto tutela 3")
      .replace(/\bSurvival Charm T\b/g, "Amuleto tutela 4")
      .replace(/\bSurvival Charm Y\b/g, "Amuleto tutela 5")
      // .replace(/\bTorn Journal\b/g, "Diario rovinato")
      .replace(/\bTorn Agenda\b/g, "Diario rovinato")
      .replace(/\bWarding Charm R\b/g, "Amuleto salute 1")
      .replace(/\bWarding Charm B\b/g, "Amuleto salute 2")
      .replace(/\bWarding Charm P\b/g, "Amuleto salute 3")
      .replace(/\bWarding Charm T\b/g, "Amuleto salute 4")
      .replace(/\bWarding Charm Y\b/g, "Amuleto salute 5")
      .replace(/\bWall Fragment\b/g, "Pezzo di lastra")
      .replace(/\bBasculegion Food\b/g, "Esca Basculegion")
      // .replace(/\bOld Journal\b/g, "Vecchio diario")
      .replace(/\bOld Agenda\b/g, "Vecchio diario")
      // .replace(/\bWing Ball\b/g, "Wing Ball")
      // .replace(/\bJet Ball\b/g, "Jet Ball")
      .replace(/\bHeavy Ball\b/g, "Peso Ball")
      .replace(/\bLeaden Ball\b/g, "Megaton Ball")
      // .replace(/\bGigaton Ball\b/g, "Gigaton Ball")
      .replace(/\bHopo Berry\b/g, "Baccaluppo")
      .replace(/\bGrit Dust\b/g, "Sabbia impegno")
      .replace(/\bGrit Gravel\b/g, "Ghiaia impegno")
      .replace(/\bGrit Pebble\b/g, "Pietra impegno")
      .replace(/\bGrit Rock\b/g, "Roccia impegno")
      .replace(/\bSecret Medicine\b/g, "Rimedio segreto")
      .replace(/\bTempting Charm R\b/g, "Amuleto Sostituto 1")
      .replace(/\bLost Satchel\b/g, "Oggetto smarrito")
      .replace(/\bOrigin Ball\b/g, "Origin Ball")
      .replace(/\bOrigin Ore\b/g, "Rocciorigine")
      .replace(/\bAdamant Crystal\b/g, "Adamasferoide")
      .replace(/\bLustrous Globe\b/g, "Splendisferoide")
      .replace(/\bGriseous Core\b/g, "Grigiosferoide")
      .replace(/\bBlank Plate\b/g, "Lastraripristino")
      .replace(/\bCrafting Kit\b/g, "Kit faidaté")
      // .replace(/\bStrange Ball\b/g, "Strange Ball")
      .replace(/\bPokédex\b/g, "Pokédex")
      .replace(/\bOld Verse (\d*)\b/g, "Antica poesia $1")
      .replace(/\bLegend Plate\b/g, "Lastraleggenda")

      // Caramelle di GO
      .replace(/\bCandy Jar\b/g, "Portacaramelle")
      .replace(/\bBulbasaur Candy\b/g, "Caramella Bulbasaur")
      .replace(/\bCharmander Candy\b/g, "Caramella Charmander")
      .replace(/\bSquirtle Candy\b/g, "Caramella Squirtle")
      .replace(/\bCaterpie Candy\b/g, "Caramella Caterpie")
      .replace(/\bWeedle Candy\b/g, "Caramella Weedle")
      .replace(/\bPidgey Candy\b/g, "Caramella Pidgey")
      .replace(/\bRattata Candy\b/g, "Caramella Rattata")
      .replace(/\bSpearow Candy\b/g, "Caramella Spearow")
      .replace(/\bEkans Candy\b/g, "Caramella Ekans")
      .replace(/\bPikachu Candy\b/g, "Caramella Pikachu")
      .replace(/\bSandshrew Candy\b/g, "Caramella Sandshrew")
      .replace(/\bNidoran♀ Candy\b/g, "Caramella Nidoran♀")
      .replace(/\bNidoran♂ Candy\b/g, "Caramella Nidoran♂")
      .replace(/\bClefairy Candy\b/g, "Caramella Clefairy")
      .replace(/\bVulpix Candy\b/g, "Caramella Vulpix")
      .replace(/\bJigglypuff Candy\b/g, "Caramella Jigglypuff")
      .replace(/\bZubat Candy\b/g, "Caramella Zubat")
      .replace(/\bOddish Candy\b/g, "Caramella Oddish")
      .replace(/\bParas Candy\b/g, "Caramella Paras")
      .replace(/\bVenonat Candy\b/g, "Caramella Venonat")
      .replace(/\bDiglett Candy\b/g, "Caramella Diglett")
      .replace(/\bMeowth Candy\b/g, "Caramella Meowth")
      .replace(/\bPsyduck Candy\b/g, "Caramella Psyduck")
      .replace(/\bMankey Candy\b/g, "Caramella Mankey")
      .replace(/\bGrowlithe Candy\b/g, "Caramella Growlithe")
      .replace(/\bPoliwag Candy\b/g, "Caramella Poliwag")
      .replace(/\bAbra Candy\b/g, "Caramella Abra")
      .replace(/\bMachop Candy\b/g, "Caramella Machop")
      .replace(/\bBellsprout Candy\b/g, "Caramella Bellsprout")
      .replace(/\bTentacool Candy\b/g, "Caramella Tentacool")
      .replace(/\bGeodude Candy\b/g, "Caramella Geodude")
      .replace(/\bPonyta Candy\b/g, "Caramella Ponyta")
      .replace(/\bSlowpoke Candy\b/g, "Caramella Slowpoke")
      .replace(/\bMagnemite Candy\b/g, "Caramella Magnemite")
      .replace(/\bFarfetch’d Candy\b/g, "Caramella Farfetch’d")
      .replace(/\bDoduo Candy\b/g, "Caramella Doduo")
      .replace(/\bSeel Candy\b/g, "Caramella Seel")
      .replace(/\bGrimer Candy\b/g, "Caramella Grimer")
      .replace(/\bShellder Candy\b/g, "Caramella Shellder")
      .replace(/\bGastly Candy\b/g, "Caramella Gastly")
      .replace(/\bOnix Candy\b/g, "Caramella Onix")
      .replace(/\bDrowzee Candy\b/g, "Caramella Drowzee")
      .replace(/\bKrabby Candy\b/g, "Caramella Krabby")
      .replace(/\bVoltorb Candy\b/g, "Caramella Voltorb")
      .replace(/\bExeggcute Candy\b/g, "Caramella Exeggcute")
      .replace(/\bCubone Candy\b/g, "Caramella Cubone")
      .replace(/\bHitmonlee Candy\b/g, "Caramella Hitmonlee")
      .replace(/\bHitmonchan Candy\b/g, "Caramella Hitmonchan")
      .replace(/\bLickitung Candy\b/g, "Caramella Lickitung")
      .replace(/\bKoffing Candy\b/g, "Caramella Koffing")
      .replace(/\bRhyhorn Candy\b/g, "Caramella Rhyhorn")
      .replace(/\bChansey Candy\b/g, "Caramella Chansey")
      .replace(/\bTangela Candy\b/g, "Caramella Tangela")
      .replace(/\bKangaskhan Candy\b/g, "Caramella Kangaskhan")
      .replace(/\bHorsea Candy\b/g, "Caramella Horsea")
      .replace(/\bGoldeen Candy\b/g, "Caramella Goldeen")
      .replace(/\bStaryu Candy\b/g, "Caramella Staryu")
      .replace(/\bMr. Mime Candy\b/g, "Caramella Mr. Mime")
      .replace(/\bScyther Candy\b/g, "Caramella Scyther")
      .replace(/\bJynx Candy\b/g, "Caramella Jynx")
      .replace(/\bElectabuzz Candy\b/g, "Caramella Electabuzz")
      .replace(/\bPinsir Candy\b/g, "Caramella Pinsir")
      .replace(/\bTauros Candy\b/g, "Caramella Tauros")
      .replace(/\bMagikarp Candy\b/g, "Caramella Magikarp")
      .replace(/\bLapras Candy\b/g, "Caramella Lapras")
      .replace(/\bDitto Candy\b/g, "Caramella Ditto")
      .replace(/\bEevee Candy\b/g, "Caramella Eevee")
      .replace(/\bPorygon Candy\b/g, "Caramella Porygon")
      .replace(/\bOmanyte Candy\b/g, "Caramella Omanyte")
      .replace(/\bKabuto Candy\b/g, "Caramella Kabuto")
      .replace(/\bAerodactyl Candy\b/g, "Caramella Aerodactyl")
      .replace(/\bSnorlax Candy\b/g, "Caramella Snorlax")
      .replace(/\bArticuno Candy\b/g, "Caramella Articuno")
      .replace(/\bZapdos Candy\b/g, "Caramella Zapdos")
      .replace(/\bMoltres Candy\b/g, "Caramella Moltres")
      .replace(/\bDratini Candy\b/g, "Caramella Dratini")
      .replace(/\bMewtwo Candy\b/g, "Caramella Mewtwo")
      .replace(/\bMew Candy\b/g, "Caramella Mew")
      .replace(/\bMeltan Candy\b/g, "Caramella Meltan")
      .replace(/\bMagmar Candy\b/g, "Caramella Magmar");

    // Ingredienti (in fondo perché sono parole super generiche)
    if (!battleHeld) {
      str = str

        // Ingredienti
        .replace(/\bVinegar\b/g, "Aceto")
        .replace(/\bPineapple\b/g, "Ananas")
        // .replace(/\bAvocado\b/g, "Avocado")
        // .replace(/\bBanana\b/g, "Banana")
        .replace(/\bBasil\b/g, "Basilico")
        .replace(/\bPeanut Butter\b/g, "Burro di arachidi")
        .replace(/\bButter\b/g, "Burro")
        .replace(/\bCucumber\b/g, "Cetriolo")
        .replace(/\bChorizo\b/g, "Chorizo rosolato")
        .replace(/\bRed Onion\b/g, "Cipolla rossa")
        .replace(/\bOnion\b/g, "Cipolla")
        .replace(/\bSmoke-Poke Tail\b/g, "Coda affumicata")
        .replace(/\bJam\b/g, "Confettura di bosco")
        .replace(/\bWatercress\b/g, "Crescione")
        .replace(/\bCurry Powder\b/g, "Curry in polvere")
        .replace(/\bPackaged Curry\b/g, "Curry precotto")
        .replace(/\bPungent Root\b/g, "Erbe acquatiche")
        .replace(/\bSmoked Fillet\b/g, "Filetto affumicato")
        .replace(/\bFried Fillet\b/g, "Filetto impanato")
        .replace(/\bBaguette\b/g, "Filoncino")
        .replace(/\bCheese\b/g, "Formaggio")
        .replace(/\bCream Cheese\b/g, "Formaggio cremoso")
        .replace(/\bMoomoo Cheese\b/g, "Formaggio Mumu")
        .replace(/\bStrawberry\b/g, "Fragola")
        .replace(/\bFried Food\b/g, "Fritto misto")
        .replace(/\bFruit Bunch\b/g, "Frutti")
        .replace(/\bMixed Mushrooms\b/g, "Funghi")
        .replace(/\bGigantamix\b/g, "Gigaspezia")
        // .replace(/\bLarge Leek\b/g, "Grosso porro")
        .replace(/\bLarge Gambo\b/g, "Grosso porro")
        .replace(/\bPrecooked Burger\b/g, "Hamburger")
        .replace(/\bHamburger\b/g, "Hamburger grigliato")
        .replace(/\bHamburger grigliato grigliato\b/g, "Hamburger grigliato")
        .replace(/\bPotato Salad\b/g, "Insalata di patate")
        // .replace(/\bJalapeño\b/g, "Jalapeño")
        // .replace(/\bKetchup\b/g, "Ketchup")
        // .replace(/\bKiwi\b/g, "Kiwi")
        .replace(/\bCoconut Milk\b/g, "Latte di cocco")
        .replace(/\bTin of Beans\b/g, "Lattina fagioli")
        .replace(/\bBob's Food Tin\b/g, "Lattina Gustavo")
        .replace(/\bLettuce\b/g, "Lattuga")
        .replace(/\bMayonnaise\b/g, "Maionese")
        .replace(/\bMarmalade\b/g, "Marmellata")
        .replace(/\bFancy Apple\b/g, "Mela prelibata")
        .replace(/\bApple\b/g, "Mela")
        .replace(/\bInstant Noodles\b/g, "Noodle precotti")
        .replace(/\bNoodles\b/g, "Noodle")
        .replace(/\bOlive Oil\b/g, "Olio d'oliva")
        .replace(/\bBrittle Bones\b/g, "Ossi sottili")
        .replace(/\bBread\b/g, "Pan carré")
        .replace(/\bBacon\b/g, "Pancetta rosolata")
        .replace(/\bFresh Cream\b/g, "Panna da cucina")
        .replace(/\bWhipped Cream\b/g, "Panna montata")
        // .replace(/\bPasta\b/g, "Pasta")
        .replace(/\bPack of Potatoes\b/g, "Patate")
        .replace(/\bYellow Bell Pepper\b/g, "Peperone giallo")
        .replace(/\bRed Bell Pepper\b/g, "Peperone rosso")
        .replace(/\bGreen Bell Pepper\b/g, "Peperone verde")
        .replace(/\bPepper\b/g, "Pepe")
        .replace(/\bCherry Tomatoes\b/g, "Pomodorini")
        .replace(/\bTomato\b/g, "Pomodoro")
        .replace(/\bHam\b/g, "Prosciutto cotto")
        .replace(/\bProsciutto\b/g, "Prosciutto crudo")
        .replace(/\bProsciutto crudo crudo\b/g, "Prosciutto crudo")
        .replace(/\bHorseradish\b/g, "Rafano")
        .replace(/\bRice\b/g, "Riso")
        .replace(/\bSalt\b/g, "Sale")
        .replace(/\bChili Sauce\b/g, "Salsa piccante")
        .replace(/\bSausages\b/g, "Salsicce")
        .replace(/\bHerbed Sausage\b/g, "Salsiccia alle erbe")
        .replace(/\bBach's Food Tin\b/g, "Scatoletta Bach")
        .replace(/\bMustard\b/g, "Senape")
        .replace(/\bPickle\b/g, "Sottaceto")
        .replace(/\bBitter Herba Mystica\b/g, "Spezia nascosta amara")
        .replace(/\bSour Herba Mystica\b/g, "Spezia nascosta aspra")
        .replace(/\bSweet Herba Mystica\b/g, "Spezia nascosta dolce")
        .replace(/\bSpicy Herba Mystica\b/g, "Spezia nascosta pepata")
        .replace(/\bSalty Herba Mystica\b/g, "Spezia nascosta salata")
        .replace(/\bHerba Mystica\b/g, "Spezia nascosta")
        .replace(/\bSpice Mix\b/g, "Spezie assortite")
        .replace(/\bKlawf Stick\b/g, "Surimi di Klawf")
        // .replace(/\bTofu\b/g, "Tofu")
        .replace(/\bPotato Tortilla\b/g, "Tortilla")
        // .replace(/\bEgg\b/g, "Uovo bollito") // this causes so much troubles
        .replace(/\bBoiled Egg\b/g, "Uovo sodo")
        .replace(/\bSalad Mix\b/g, "Verdure");
      // .replace(/\bWasabi\b/g, "Wasabi")
      // .replace(/\bYogurt\b/g, "Yogurt")
    }

    return str;
  };

  macros["strumenti lotta"] = function (str) {
    return macros.strumenti(str, true);
  };

  if (utils.updateMenu) {
    utils.updateMenu();
  }
})(utils || { macros: {} });
