'use strict';
/**
 * "abilità" macro, that translates move names
 */

(function(utils) {

const macros = utils.macros;


/*

L'argomento battleHeld, con default false, indica se
devono essere tradotti solo gli strumenti tenuti
in lotta

*/
macros.strumenti = function(str, battleHeld) {
    battleHeld = battleHeld || false;
    if (!battleHeld) {
        str = str
        // Pietre evolutive
            .replace(/\bSun Stone\b/g, 'Pietrasolare')
            .replace(/\bMoon Stone\b/g, 'Pietralunare')
            .replace(/\bFire Stone\b/g, 'Pietrafocaia')
            .replace(/\bThunder Stone\b/g, 'Pietratuono')
            .replace(/\bWater Stone\b/g, 'Pietraidrica')
            .replace(/\bLeaf Stone\b/g, 'Pietrafoglia')
            .replace(/\bShiny Stone\b/g, 'Pietrabrillo')
            .replace(/\bDusk Stone\b/g, 'Neropietra')
            .replace(/\bDawn Stone\b/g, 'Pietralbore')
            .replace(/\bOval Stone\b/g, 'Pietraovale')

        // Strumenti da vendere
            .replace(/\bTiny Mushroom\b/g, 'Minifungo')
            .replace(/\bBig Mushroom\b/g, 'Grande Fungo')
            .replace(/\bBig Pearl\b/g, 'Grande Perla')
            .replace(/\bPearl String\b/g, 'Trittiperla')
            .replace(/\bPearl\b/g, 'Perla')
            .replace(/\bStardust\b/g, 'Polvostella')
            .replace(/\bStar Piece\b/g, 'Pezzo Stella')
            .replace(/\bGold Leaf\b/g, 'Fogliadoro')
            .replace(/\bSilver Leaf\b/g, 'Fogliargento')
            .replace(/\bBrick Piece\b/g, 'Mattoncino')
            .replace(/\bNugget\b/g, 'Pepita')
            .replace(/\bHeart Scale\b/g, 'Squama Cuore')
            .replace(/\bRare Bone\b/g, 'Ossopesso')
            .replace(/\bPretty Wing\b/g, 'Piumabella')
            .replace(/\bBalm Mushroom\b/g, 'Profumfungo')
            .replace(/\bBig Nugget\b/g, 'Granpepita')
            .replace(/\bComet Shard\b/g, 'Pezzo Cometa')
            .replace(/\bRelic Copper\b/g, 'Soldantico')
            .replace(/\bRelic Silver\b/g, 'Ducatantico')
            .replace(/\bRelic Gold\b/g, 'Doblonantico')
            .replace(/\bRelic Vase\b/g, 'Vasantico')
            .replace(/\bRelic Band\b/g, 'Bracciantico')
            .replace(/\bRelic Statue\b/g, 'Statuantica')
            .replace(/\bRelic Crown\b/g, 'Coronantica')

        // Rimedi
            .replace(/\bMax Potion\b/g, 'Pozione Max')
            .replace(/\bHyper Potion\b/g, 'Iperpozione')
            .replace(/\bSuper Potion\b/g, 'Superpozione')
            .replace(/\bPotion\b/g, 'Pozione')
            .replace(/\bAntidote\b/g, 'Antidoto')
            .replace(/\bBurn Heal\b/g, 'Antiscottatura')
            .replace(/\bIce Heal\b/g, 'Antigelo')
            .replace(/\bAwakening\b/g, 'Sveglia')
            .replace(/\bParlyze Heal\b/g, 'Antiparalisi')
            .replace(/\bFull Restore\b/g, 'Ricarica Totale')
            .replace(/\bFull Heal\b/g, 'Cura Totale')
            .replace(/\bRevive\b/g, 'Revitalizzante')
            .replace(/\bMax Revive\b/g, 'Revitalizzante Max')
            .replace(/\bFresh Water\b/g, 'Acqua Fresca')
            .replace(/\bSoda Pop\b/g, 'Gassosa')
            .replace(/\bLemonade\b/g, 'Lemonsucco')
            .replace(/\bEther\b/g, 'Etere')
            .replace(/\bMax Ether\b/g, 'Etere Max')
            .replace(/\bElixir\b/g, 'Elisir')
            .replace(/\bMax Elixir\b/g, 'Elisir Max')
            .replace(/\bMoomoo Milk\b/g, 'Latte Mumu')
            .replace(/\bEnergy Powder\b/g, 'Polvenergia')
            .replace(/\bEnergy Root\b/g, 'Radicenergia')
            .replace(/\bHeal Powder\b/g, 'Polvocura')
            .replace(/\bRevival Herb\b/g, 'Vitalerba')
            .replace(/\bSacred Ash\b/g, 'Magicenere')
            .replace(/\bRage Candy Bar\b/g, 'Iramella')
            .replace(/\bLava Cookie\b/g, 'Lavottino')
            .replace(/\bBerry Juice\b/g, 'Succo di Bacca')
            .replace(/\bHP Up\b/g, 'PS-Su')
            .replace(/\bProtein\b/g, 'Proteina')
            .replace(/\bIron\b/g, 'Ferro')
            .replace(/\bCarbos\b/g, 'Carburante')
            .replace(/\bCalcium\b/g, 'Calcio')
            .replace(/\bRare Candy\b/g, 'Caramella Rara')
            .replace(/\bPP Up\b/g, 'PP-Su')
            .replace(/\bZinc\b/g, 'Zinco')
            .replace(/\bPP Max\b/g, 'PP-Max')
            .replace(/\bSweet Heart\b/g, 'Dolcecuore')
            .replace(/\bHealth Wing\b/g, 'Piumsalute')
            .replace(/\bMuscle Wing\b/g, 'Piumpotenza')
            .replace(/\bResist Wing\b/g, 'Piumtutela')
            .replace(/\bGenius Wing\b/g, 'Piumingegno')
            .replace(/\bClever Wing\b/g, 'Piumintuito')
            .replace(/\bSwift Wing\b/g, 'Piumreazione')
            .replace(/\bCasteliacone\b/g, 'Conostropoli')
            .replace(/\bLumiose Galette\b/g, 'Pan di Lumi')

        // Balls
            .replace(/\bPoké Ball\b/g, 'Pok&eacute; Ball')
            .replace(/\bGreat Ball\b/g, 'Mega Ball')
            .replace(/\bUltra Ball\b/g, 'Ultra Ball')
            .replace(/\bMaster Ball\b/g, 'Master Ball')
            .replace(/\bSafari Ball\b/g, 'Safari Ball')
            .replace(/\bHeavy Ball\b/g, 'Peso Ball')
            .replace(/\bLevel Ball\b/g, 'Level Ball')
            .replace(/\bLure Ball\b/g, 'Esca Ball')
            .replace(/\bFast Ball\b/g, 'Rapid Ball')
            .replace(/\bFriend Ball\b/g, 'Friend Ball')
            .replace(/\bMoon Ball\b/g, 'Luna Ball')
            .replace(/\bLove Ball\b/g, 'Love Ball')
            .replace(/\bSport Ball\b/g, 'Gara Ball')
            .replace(/\bNet Ball\b/g, 'Rete Ball')
            .replace(/\bDive Ball\b/g, 'Sub Ball')
            .replace(/\bNest Ball\b/g, 'Minor Ball')
            .replace(/\bRepeat Ball\b/g, 'Bis Ball')
            .replace(/\bTimer Ball\b/g, 'Timer Ball')
            .replace(/\bLuxury Ball\b/g, 'Chich Ball')
            .replace(/\bPremier Ball\b/g, 'Premier Ball')
            .replace(/\bHeal Ball\b/g, 'Cura Ball')
            .replace(/\bDusk Ball\b/g, 'Scuro Ball')
            .replace(/\bQuick Ball\b/g, 'Velox Ball')
            .replace(/\bPark Ball\b/g, 'Parco Ball')
            .replace(/\bCherish Ball\b/g, 'Pregio Ball')
            .replace(/\bDream Ball\b/g, 'Dream Ball')

        // Messaggi - Gen II
            .replace(/\bFlower Mail\b/g, 'Messaggio Fiore')
            .replace(/\bSurf Mail\b/g, 'Mess. Surf')
            .replace(/\bLitebluemail\b/g, 'Mess. Azzurro')
            .replace(/\bPortraitmail\b/g, 'Mess. Ritratto')
            .replace(/\bLovely Mail\b/g, 'Mess. Dolce')
            .replace(/\bEon Mail\b/g, 'Mess. Eon')
            .replace(/\bMorph Mail\b/g, 'Mess. Morph')
            .replace(/\bBluesky Mail\b/g, 'Mess. Cielo')
            .replace(/\bMusic Mail\b/g, 'Mess. Musica')
            .replace(/\bMirage Mail\b/g, 'Mess. Visione')

        // Messaggi - Gen III
            .replace(/\bOrange Mail\b/g, 'Mess. Agrume')
            .replace(/\bHarbor Mail\b/g, 'Mess. Porto')
            .replace(/\bGlitter Mail\b/g, 'Mess. Luci')
            .replace(/\bMech Mail\b/g, 'Mess. Tecno')
            .replace(/\bWood Mail\b/g, 'Mess. Bosco')
            .replace(/\bWave Mail\b/g, 'Mess. Onda')
            .replace(/\bBead Mail\b/g, 'Mess. Perle')
            .replace(/\bShadow Mail\b/g, 'Mess. Ombra')
            .replace(/\bTropic Mail\b/g, 'Mess. Tropic')
            .replace(/\bDream Mail\b/g, 'Mess. Sogno')
            .replace(/\bFab Mail\b/g, 'Mess. Fab')
            .replace(/\bRetro Mail\b/g, 'Mess. Retro')

        // Messaggi - Gen IV
            .replace(/\bGrass Mail\b/g, 'Mess. Erba')
            .replace(/\bFlame Mail\b/g, 'Mess. Fiamma')
            .replace(/\bBubble Mail\b/g, 'Mess. Bolla')
            .replace(/\bBloom Mail\b/g, 'Mess. Petalo')
            .replace(/\bTunnel Mail\b/g, 'Mess. Tunnel')
            .replace(/\bSteel Mail\b/g, 'Mess. Lega')
            .replace(/\bHeart Mail\b/g, 'Mess. Cuore')
            .replace(/\bSnow Mail\b/g, 'Mess. Neve')
            .replace(/\bSpace Mail\b/g, 'Mess. Spazio')
            .replace(/\bAir Mail\b/g, 'Mess.  Aereo')
            .replace(/\bMosaic Mail\b/g, 'Mess.  Iride')
            .replace(/\bBrick Mail\b/g, 'Mess. Muro')

        // Messaggi - Gen V
            .replace(/\bGreet Mail\b/g, 'Mess. Inizio')
            .replace(/\bFavored Mail\b/g, 'Mess. TVB')
            .replace(/\bRSVP Mail\b/g, 'Mess. Invito')
            .replace(/\bThanks Mail\b/g, 'Mess. Grazie')
            .replace(/\bInquiry Mail\b/g, 'Mess. Chiedi')
            .replace(/\bLike Mail\b/g, 'Mess. Sugg.')
            .replace(/\bReply Mail\b/g, 'Mess. Risp.')
            .replace(/\bBridgeMail S\b/g, 'Mess. Frec.')
            .replace(/\bBridgeMail D\b/g, 'Mess. Libec.')
            .replace(/\bBridgeMail T\b/g, 'Mess. Prop.')
            .replace(/\bBridgeMail V\b/g, 'Mess. Vill.')
            .replace(/\bBridgeMail M\b/g, 'Mess. Merav.')

        // Strumenti lotta
            .replace(/\bGuard Spec.\b/g, 'Superguardia')
            .replace(/\bDire Hit\b/g, 'Supercolpo')
            .replace(/\bX Attack\b/g, 'Attacco X')
            .replace(/\bX Defend\b/g, 'Difesa X')
            .replace(/\bX Speed\b/g, 'Velocit&agrave X')
            .replace(/\bX Accuracy\b/g, 'Precisione X')
            .replace(/\bX Special\b/g, 'Special X')
            .replace(/\bX Sp\. Def\b/g, 'Dif. Sp. X')
            .replace(/\bPoké Doll\b/g, 'Pokébambola')
            .replace(/\bFluffy Tail\b/g, 'Coda Skitty')
            .replace(/\bBlue Flute\b/g, 'Flauto Blu')
            .replace(/\bYellow Flute\b/g, 'Flauto Giallo')
            .replace(/\bRed Flute\b/g, 'Flauto Rosso')
            .replace(/\bPoké Toy\b/g, 'Pok&eacutegingillo')
            .replace(/\bAbility Urge\b/g, 'Chiamabilit&agrave')
            .replace(/\bItem Drop\b/g, 'Lascioggetto')
            .replace(/\bItem Urge\b/g, 'Chiamoggetto')
            .replace(/\bReset Urge\b/g, 'Ripristino')

        // Strumenti base - Gen I
            .replace(/\bCoin Case\b/g, 'Salvadanaio')
            .replace(/\bItemfinder\b/g, 'Detector')
            .replace(/\bOld Rod\b/g, 'Amo Vecchio')
            .replace(/\bGood Rod\b/g, 'Amo Buono')
            .replace(/\bSuper Rod\b/g, 'Super Amo')
            .replace(/\bS\.S\. Ticket\b/g, 'Biglietto Nave')
            .replace(/\bOak's Parcel\b/g, 'Pacco Oak')
            .replace(/\bPoké Flute\b/g, 'Pok&eacuteflauto')
            .replace(/\bSecret Key\b/g, 'Chiave Segreta')
            .replace(/\bBike Voucher\b/g, 'Buono Bici')
            .replace(/\bGold Teeth\b/g, 'Denti d’Oro')
            .replace(/\bCard Key\b/g, 'Apriporta')
            .replace(/\bLift Key\b/g, 'Chiave Ascensore')
            .replace(/\bSilph Scope\b/g, 'Spettrosonda')
            .replace(/\bBicycle\b/g, 'Bicicletta')
            .replace(/\bTown Map\b/g, 'Mappa')

        // Strumenti base - Gen II
            .replace(/\bGS Ball\b/g, 'GS Ball')
            .replace(/\bEgg Ticket\b/g, 'Bigl. Uovo')
            .replace(/\bClear Bell\b/g, 'Campana Chiara')
            .replace(/\bBlue Card\b/g, 'Carta Blu')
            .replace(/\bSquirtBottle\b/g, 'Annaffiatoio')
            .replace(/\bRed Scale\b/g, 'Squama Rossa')
            .replace(/\bLost Item\b/g, 'Strumento Perso')
            .replace(/\bPass\b/g, 'Superpass')
            .replace(/\bMachine Part\b/g, 'Pezzo macch.')
            .replace(/\bSilver Wing\b/g, 'Aladargento')
            .replace(/\bRainbow Wing\b/g, "Ala d'Iride")
            .replace(/\bMystery Egg\b/g, 'Uovo Mistero')
            .replace(/\bSecretPotion\b/g, 'Poz. Segreta')

        // Strumenti base - Gen III
            .replace(/\bMach Bike\b/g, 'Bici Corsa')
            .replace(/\bWailmer Pail\b/g, 'Vaso Wailmer')
            .replace(/\bDevon Goods\b/g, 'Merce Devon')
            .replace(/\bSoot Sack\b/g, 'Sacco Cenere')
            .replace(/\bBasement Key\b/g, 'Chiave Sotterraneo')
            .replace(/\bAcro Bike\b/g, 'Bici Cross')
            .replace(/\bPokéblock Case\b/g, 'Porta Pok&eacutemelle')
            .replace(/\bLetter\b/g, 'Lettera')
            .replace(/\bEon Ticket\b/g, 'Biglietto Eone')
            .replace(/\bRed Orb\b/g, 'Sfera Rossa')
            .replace(/\bBlue Orb\b/g, 'Sfera Blu')
            .replace(/\bScanner\b/g, 'Scanner')
            .replace(/\bGo\-Goggles\b/g, 'Occhialoni')
            // .replace(/\bMeteorite\b/g, 'Meteorite')
            .replace(/\bRm\. (\d) Key\b/g, 'Chiave stanza $1')
            .replace(/\bStorage Key\b/g, 'L.')
            .replace(/\bDevon Scope\b/g, 'Devonscopio')
            .replace(/\bVs\. Seeker\b/g, 'Cercasfide')
            .replace(/\bFame Checker\b/g, 'Pok&eacuteVIP')
            .replace(/\bTM Case\b/g, 'Porta MT-MN')
            .replace(/\bBerry Pouch\b/g, 'Porta Bacche')
            .replace(/\bTeachy TV\b/g, 'Pok&eacute TV')
            .replace(/\bRainbow Pass\b/g, 'Sette Pass')
            .replace(/\bTea\b/g, 'T&egrave')
            .replace(/\bMysticTicket\b/g, 'Biglietto Mistero')
            .replace(/\bAuroraTicket\b/g, 'Biglietto Aurora')
            .replace(/\bPowder Jar\b/g, 'Portafarina')
            .replace(/\bRuby\b/g, 'Rubino')
            .replace(/\bSapphire\b/g, 'Zaffiro')
            .replace(/\bMagma Emblem\b/g, 'Stemma Magma')
            .replace(/\bOld Sea Map\b/g, 'Mappa Stinta')

        // Strumenti base - Gen IV
            .replace(/\bExplorer Kit\b/g, 'Esplorokit')
            .replace(/\bPoké Radar\b/g, 'Pok&eacute Radar')
            .replace(/\bPoint Card\b/g, 'Scheda Punti')
            .replace(/\bJournal\b/g, 'Agenda')
            .replace(/\bSeal Case\b/g, 'Portabolli')
            .replace(/\bFashion Case\b/g, 'Scatola Chic')
            .replace(/\bPal Pad\b/g, 'Blocco Amici')
            .replace(/\bWorks Key\b/g, 'Turbinchiave')
            .replace(/\bOld Charm\b/g, 'Arcamuleto')
            .replace(/\bGalactic Key\b/g, 'Galachiave')
            .replace(/\bSprayduck\b/g, 'Sprayduck')
            .replace(/\bPoffin Case\b/g, 'Portapoffin')
            .replace(/\bSuite Key\b/g, 'Chiave Suite')
            .replace(/\bOak's Letter\b/g, 'Lettera di Oak')
            .replace(/\bLunar Wing\b/g, 'Ala Lunare')
            .replace(/\bMember Card\b/g, 'Scheda Soci')
            .replace(/\bParcel\b/g, 'Pacco')
            .replace(/\bVs\. Recorder\b/g, 'Registradati')
            .replace(/\bGracidea\b/g, 'Gracidea')
            .replace(/\bApricorn Box\b/g, 'Ghicobox')
            .replace(/\bUnown Report\b/g, 'UnownBloc')
            .replace(/\bBerry Pots\b/g, 'Piantabacche')
            .replace(/\bDowsing MCHN\b/g, 'Ricerca Strum.')
            .replace(/\bGB Sounds\b/g, 'Lettore GB')
            .replace(/\bTidal Bell\b/g, 'Camp. Onda')
            .replace(/\bData Card\b/g, 'Scheda Dati')
            .replace(/\bJade Orb\b/g, 'Sfera Verde')
            .replace(/\bEnigma Stone\b/g, 'Misticristal')

        // Strumenti base - Gen V
            .replace(/\bLiberty Pass\b/g, 'Liberticket')
            .replace(/\bProp Case\b/g, 'Portagadget')
            .replace(/\bDragon Skull\b/g, 'Teschio')
            .replace(/\bLight Stone\b/g, 'Chiarolite')
            .replace(/\bDark Stone\b/g, 'Scurolite')
            .replace(/\bXtransceiver\b/g, 'Interpok&eacute')
            .replace(/\bGram (\d)\b/g, 'Missiva $1')
            .replace(/\bColress MCHN\b/g, 'Acrocongegno')
            .replace(/\bDNA Splicers\b/g, 'Cuneo DNA')
            .replace(/\bDropped Item\b/g, 'Oggetto Perso')
            .replace(/\bGrubby Hanky\b/g, 'Pezza Sporca')
            .replace(/\bMedal Box\b/g, 'Box Premi')
            .replace(/\bOval Charm\b/g, 'Ovamuleto')
            .replace(/\bPermit\b/g, 'Permesso')
            .replace(/\bPlasma Card\b/g, 'Carta Plasma')
            .replace(/\bReveal Glass\b/g, 'Verispecchio')
            .replace(/\bShiny Charm\b/g, 'Cromamuleto')
            .replace(/\bMagma Stone\b/g, 'Magmapietra')

        // Strumenti base - Gen VI
            .replace(/\bAdventure Rules\b/g, 'Guida Avventura')
            .replace(/\bElevator Key\b/g, 'Chiave ascensore')
            .replace(/\bHolo Caster\b/g, 'Holovox')
            .replace(/\bHonor of Kalos\b/g, 'Emblema di Kalos')
            .replace(/\bIntriguing Stone\b/g, 'Sasso suggestivo')
            .replace(/\bLens Case\b/g, 'Portalenti')
            .replace(/\bLooker Ticket\b/g, 'Carta Bellocchio')
            .replace(/\bMega Ring\b/g, 'Megacerchio')
            .replace(/\bPower Plant Pass\b/g, 'Pass Centrale')
            .replace(/\bProf's Letter\b/g, 'Lettera del Prof')
            .replace(/\bRoller Skates\b/g, 'Pattini')
            .replace(/\bSprinklotad\b/g, 'Irrigalotad')
            .replace(/\bTMV Pass\b/g, 'Pass TMV')

        // Ghicocche
            .replace(/\bRed Apricorn\b/g, 'Ghicocca Rsa')
            .replace(/\bBlu Apricorn\b/g, 'Ghicocca Blu')
            .replace(/\bYlw Apricorn\b/g, 'Ghicocca Gia')
            .replace(/\bGrn Apricorn\b/g, 'Ghicocca Ver')
            .replace(/\bWht Apricorn\b/g, 'Ghicocca Bln')
            .replace(/\bBlk Apricorn\b/g, 'Ghicocca Nra')
            .replace(/\bPnk Apricorn\b/g, 'Ghicocca Ros')

        // Altri strumenti
            .replace(/\bSuper Repel\b/g, 'Superrepellente')
            .replace(/\bMax Repel\b/g, 'Repellente Max')
            .replace(/\bRepel\b/g, 'Repellente')
            .replace(/\bEscape Rope\b/g, 'Fune di Fuga')
            .replace(/\bBlack Flute\b/g, 'Flauto Nero')
            .replace(/\bWhite Flute\b/g, 'Flauto Bianco')
            .replace(/\bShoal Salt\b/g, 'Sale Ondoso')
            .replace(/\bShoal Shell\b/g, 'Gusciondoso')
            .replace(/\bRed Shard\b/g, 'Coccio Rosso')
            .replace(/\bBlue Shard\b/g, 'Coccio Blu')
            .replace(/\bYellow Shard\b/g, 'Coccio Giallo')
            .replace(/\bGreen Shard\b/g, 'Coccio Verde')
            .replace(/\bExp. Share\b/g, 'Condividi Esp.')
            .replace(/\bNormal Box\b/g, 'Scat. Normale')
            .replace(/\bGorgeous Box\b/g, 'Scat. Lusso')
            .replace(/\bSlowpokeTail\b/g, 'CodaSlowpoke')
            .replace(/\bHoney\b/g, 'Miele')
            .replace(/\bGrowth Mulch\b/g, 'Fertilrapido')
            .replace(/\bDamp Mulch\b/g, 'Fertilidro')
            .replace(/\bStable Mulch\b/g, 'Fertilsaldo')
            .replace(/\bGooey Mulch\b/g, 'Fertilcolla')
            .replace(/\bRoot Fossil\b/g, 'Radifossile')
            .replace(/\bClaw Fossil\b/g, 'Fossilunghia')
            .replace(/\bHelix Fossil\b/g, 'Helixfossile')
            .replace(/\bDome Fossil\b/g, 'Domofossile')
            .replace(/\bOld Amber\b/g, 'Ambra Antica')
            .replace(/\bArmor Fossil\b/g, 'Fossilscudo')
            .replace(/\bSkull Fossil\b/g, 'Fossilcranio')
            .replace(/\bOdd Keystone\b/g, 'Roccianima')
            .replace(/\bCover Fossil\b/g, 'Fossiltappo')
            .replace(/\bPlume Fossil\b/g, 'Fossilpiuma')
            .replace(/\bPass Orb\b/g, 'Passabilia')
            .replace(/\bJaw Fossil\b/g, 'Fossilmascella')
            .replace(/\bSail Fossil\b/g, 'Fossilpinna')
            .replace(/\bAmaze Mulch\b/g, 'Fertilprodigio')
            .replace(/\bBoost Mulch\b/g, 'Fertilcopioso')
            .replace(/\bSurprise Mulch\b/g, 'Fertilsorpresa')
            .replace(/\bRich Mulch\b/g, 'Fertilflorido')
            .replace(/\bDiscount Coupon\b/g, 'Buono sconto')
            .replace(/\bStrange Souvenir\b/g, 'Strano ninnolo')
            .replace(/\bAbility Capsule\b/g, 'Capsula Abilit&agrave')
            .replace(/\bJoy Scent\b/g, 'Olio di Pino')
            .replace(/\bExcite Scent\b/g, 'Olio di Rosa')
            .replace(/\bVivid Scent\b/g, 'Olio Sublime')
            .replace(/\bColognes Case\b/g, 'Portaoli')
            .replace(/\bColognes\b/g, 'Oli')

        // Varie ed eventuali
            .replace(/\[\[TM/gi, '[[MT')
            .replace(/\[\[HM/gi, '[[MN')
            .replace(/\{\{DL\|([\w-\s]+)\|([\w\s]+)\}\}/gi, '[[$1#$2|$2]]')
            .replace(/Evolution\-inducing held item/gi, 'Oggetti tenuti che provocano Evoluzione');
    }

    // Strumenti tenuti - Gen II

    return str
        .replace(/\bBright Powder\b/g, 'Luminpolvere')
        .replace(/\bQuick Claw\b/g, 'Rapidartigli')
        .replace(/\bKing's Rock\b/g, 'Roccia di Re')
        .replace(/\bSilver ?Powder\b/g, 'Argenpolvere')
        .replace(/\bAmulet Coin\b/g, 'Monetamuleto')
        .replace(/\bCleanse Tag\b/g, 'Velopuro')
        .replace(/\bSmoke Ball\b/g, 'Palla Fumo')
        .replace(/\bEverstone\b/g, 'Pietrastante')
        .replace(/\bFocus Band\b/g, 'Bandana')
        .replace(/\bFocus Sash\b/g, 'Focalnastro')
        .replace(/\bLucky Egg\b/g, 'Fortunuovo')
        .replace(/\bScope Lens\b/g, 'Mirino')
        .replace(/\bMetal Coat\b/g, 'Metalcoperta')
        .replace(/\bLeftovers\b/g, 'Avanzi')
        .replace(/\bDragon Scale\b/g, 'Squama Drago')
        .replace(/\bLight Ball\b/g, 'Elettropalla')
        .replace(/\bSoft Sand\b/g, 'Sabbia Soffice')
        .replace(/\bHard Stone\b/g, 'Pietradura')
        .replace(/\bMiracle Seed\b/g, 'Miracolseme')
        .replace(/\bBlack ?Glasses\b/g, 'Occhialineri')
        .replace(/\bBlack ?[Bb]elt\b/g, 'Cinturanera')
        .replace(/\bMagnet\b/g, 'Calamita')
        .replace(/\bMystic Water\b/g, 'Acquamagica')
        .replace(/\bSharp Beak\b/g, 'Beccaffilato')
        .replace(/\bPoison Barb\b/g, 'Velenaculeo')
        .replace(/\bNever\-Melt Ice\b/g, 'Gelomai')
        .replace(/\bSpell Tag\b/g, 'Spettrotarga')
        .replace(/\bTwisted Spoon\b/g, 'Cucchiaio Torto')
        .replace(/\bCharcoal\b/g, 'Carbonella')
        .replace(/\bDragon Fang\b/g, 'Dentedidrago')
        .replace(/\bPink Bow\b/g, 'Fiocco Rosa')
        .replace(/\bPolkadot Bow\b/g, 'Fiocco Pois')
        .replace(/\bUp\-Grade\b/g, 'Upgrade')
        .replace(/\bLucky Punch\b/g, 'Fortunpugno')
        .replace(/\bMetal Powder\b/g, 'Metalpolvere')
        .replace(/\bThick Club\b/g, 'Ossospesso')
        .replace(/\bStick\b/g, 'Gambo')
        .replace(/\bBerserk Gene\b/g, 'Gene Furioso')

    // Strumenti tenuti - Gen III
        .replace(/\bWhite Herb\b/g, 'Erbachiara')
        .replace(/\bMacho Brace\b/g, 'Crescicappa')
        .replace(/\bSoothe Bell\b/g, 'Calmanella')
        .replace(/\bMental Herb\b/g, 'Mentalerba')
        .replace(/\bChoice Band\b/g, 'Bendascelta')
        .replace(/\bSoul Dew\b/g, 'Cuorugiada')
        .replace(/\bDeep Sea Tooth\b/g, 'Denteabissi')
        .replace(/\bDeep Sea Scale\b/g, 'Squamabissi')
        .replace(/\bSilk Scarf\b/g, 'Sciarpa Seta')
        .replace(/\bShell Bell\b/g, 'Conchinella')
        .replace(/\bSea Incense\b/g, 'Marearoma')
        .replace(/\bLax Incense\b/g, 'Distraroma')
        .replace(/\bRed Scarf\b/g, 'Fascia Rossa')
        .replace(/\bBlue Scarf\b/g, 'Fascia Blu')
        .replace(/\bPink Scarf\b/g, 'Fascia Rosa')
        .replace(/\bGreen Scarf\b/g, 'Fascia Verde')
        .replace(/\bYellow Scarf\b/g, 'Fascia Gialla')

    // Strumenti tenuti - Gen IV
        .replace(/\bFlame Plate\b/g, 'Lastrarogo')
        .replace(/\bSplash Plate\b/g, 'Lastraidro')
        .replace(/\bZap Plate\b/g, 'Lastrasaetta')
        .replace(/\bMeadow Plate\b/g, 'Lastraprato')
        .replace(/\bIcicle Plate\b/g, 'Lastragelo')
        .replace(/\bFist Plate\b/g, 'Lastrapugno')
        .replace(/\bToxic Plate\b/g, 'Lastrafiele')
        .replace(/\bEarth Plate\b/g, 'Lastrageo')
        .replace(/\bSky Plate\b/g, 'Lastracielo')
        .replace(/\bMind Plate\b/g, 'Lastamente')
        .replace(/\bInsect Plate\b/g, 'Lastrabaco')
        .replace(/\bStone Plate\b/g, 'Lastrapietra')
        .replace(/\bSpooky Plate\b/g, 'Lastratetra')
        .replace(/\bDraco Plate\b/g, 'Lastradrakon')
        .replace(/\bDread Plate\b/g, 'Lastratimore')
        .replace(/\bIron Plate\b/g, 'Lastraferro')
        .replace(/\bOdd Incense\b/g, 'Bizzoaroma')
        .replace(/\bRock Incense\b/g, 'Roccioaroma')
        .replace(/\bFull Incense\b/g, 'Gonfioaroma')
        .replace(/\bWave Incense\b/g, 'Ondaroma')
        .replace(/\bRose Incense\b/g, 'Rosaroma')
        .replace(/\bLuck Incense\b/g, 'Fortunaroma')
        .replace(/\bPure Incense\b/g, 'Puroaroma')
        .replace(/\bProtector\b/g, 'Copertura')
        .replace(/\bElectirizer\b/g, 'Elettritore')
        .replace(/\bMagmarizer\b/g, 'Magmatore')
        .replace(/\bDubious Disc\b/g, 'Dubbiodisco')
        .replace(/\bReaper Cloth\b/g, 'Terrorpanno')
        .replace(/\bRazor Claw\b/g, 'Affilartigli')
        .replace(/\bRazor Fang\b/g, 'Affilodente')
        .replace(/\bAdamant Orb\b/g, 'Adamasfera')
        .replace(/\bLustrous Orb\b/g, 'Splendisfera')
        .replace(/\bGriseous Orb\b/g, 'Grigiosfera')
        .replace(/\bWide Lens\b/g, 'Grandelente')
        .replace(/\bMuscle Band\b/g, 'Muscolbanda')
        .replace(/\bWise Glasses\b/g, 'Saviocchiali')
        .replace(/\bExpert Belt\b/g, 'Abilcintura')
        .replace(/\bLight Clay\b/g, 'Creta Luce')
        .replace(/\bLife Orb\b/g, 'Assorbisfera')
        .replace(/\bPower Herb\b/g, 'Vigorerba')
        .replace(/\bToxic Orb\b/g, 'Tossicsfera')
        .replace(/\bFlame Orb\b/g, 'Fiammosfera')
        .replace(/\bQuick Powder\b/g, 'Velopolvere')
        .replace(/\bZoom Lens\b/g, 'Zoomlente')
        .replace(/\bMetronome\b/g, 'Plessimetro')
        .replace(/\bIron Ball\b/g, 'Ferropalla')
        .replace(/\bLagging Tail\b/g, 'Rallentocoda')
        .replace(/\bDestiny Knot\b/g, 'Destincomune')
        .replace(/\bBlack Sludge\b/g, 'Fangopece')
        .replace(/\bIcy Rock\b/g, 'Rocciafredda')
        .replace(/\bSmooth Rock\b/g, 'Roccialiscia')
        .replace(/\bHeat Rock\b/g, 'Rocciacalda')
        .replace(/\bDamp Rock\b/g, 'Rocciaumida')
        .replace(/\bGrip Claw\b/g, 'Presartigli')
        .replace(/\bChoice Scarf\b/g, 'Stolascelta')
        .replace(/\bSticky Barb\b/g, 'Vischiopunta')
        .replace(/\bPower Bracer\b/g, 'Vigorcerchio')
        .replace(/\bPower Belt\b/g, 'Vigorfascia')
        .replace(/\bPower Lens\b/g, 'Vigorlente')
        .replace(/\bPower Band\b/g, 'Vigorbanda')
        .replace(/\bPower Ankle\b/g, 'Vigorgliera')
        .replace(/\bPower Weight\b/g, 'Vigorpeso')
        .replace(/\bShed Shell\b/g, 'Disfoguscio')
        .replace(/\bBig Root\b/g, 'Granradice')
        .replace(/\bChoice Specs\b/g, 'Lentiscelta')

    // Strumenti tenuti - Gen V
        .replace(/\bDouse Drive\b/g, 'Idromodulo')
        .replace(/\bShock Drive\b/g, 'Voltmodulo')
        .replace(/\bBurn Drive\b/g, 'Piromodulo')
        .replace(/\bChill Drive\b/g, 'Gelomodulo')
        .replace(/\bPrism Scale\b/g, 'Squama Bella')
        .replace(/\bEviolite\b/g, 'Evolcondensa')
        .replace(/\bFloat Stone\b/g, 'Pietralieve')
        .replace(/\bRocky Helmet\b/g, 'Bitorzolelmo')
        .replace(/\bAir Balloon\b/g, 'Palloncino')
        .replace(/\bRed Card\b/g, 'Cartelrosso')
        .replace(/\bRing Target\b/g, 'Facilsaglio')
        .replace(/\bBinding Band\b/g, 'Legafascia')
        .replace(/\bAbsorb Bulb\b/g, 'Bulbo')
        .replace(/\bCell Battery\b/g, 'Ricaripila')
        .replace(/\bEject Button\b/g, 'Pulsantefuga')
        .replace(/\bFire Gem\b/g, 'Bijoufuoco')
        .replace(/\bWater Gem\b/g, 'Bijouacqua')
        .replace(/\bElectric Gem\b/g, 'Bijouelettro')
        .replace(/\bGrass Gem\b/g, 'Bijouerba')
        .replace(/\bIce Gem\b/g, 'Bijoughiac.')
        .replace(/\bFighting Gem\b/g, 'Bijoulotta')
        .replace(/\bPoison Gem\b/g, 'Bijouveleno')
        .replace(/\bGround Gem\b/g, 'Bijouterra')
        .replace(/\bFlying Gem\b/g, 'Bijouvolante')
        .replace(/\bPsychic Gem\b/g, 'Bijoupsico')
        .replace(/\bBug Gem\b/g, 'Bijoucoleot.')
        .replace(/\bRock Gem\b/g, 'Bijouroccia')
        .replace(/\bGhost Gem\b/g, 'Bijouspettro')
        .replace(/\bDragon Gem\b/g, 'Bijoudrago')
        .replace(/\bDark Gem\b/g, 'Bijoubuio')
        .replace(/\bSteel Gem\b/g, 'Bijouacciaio')
        .replace(/\bNormal Gem\b/g, 'Bijounormale')

    // Strumenti tenuti - Gen VI
        .replace(/\bWhipped Dream\b/g, 'Dolcespuma')
        .replace(/\bSachet\b/g, 'Bustina Aromi')
        .replace(/\bPixie Plate\b/g, 'Lastraspiritello')
        .replace(/\bLuminous Moss\b/g, 'Muschioluce')
        .replace(/\bSnowball\b/g, 'Palla di Neve')
        .replace(/\bAssault Vest\b/g, 'Corpetto Assalto')
        .replace(/\bSafety Goggles\b/g, 'Visierantisabbia')
        .replace(/\bWeakness Policy\b/g, 'Vulneropolizza')

    // Bacche - Gen II - no template
        .replace(/\bGold Berry\b/g, 'Bacca Oro')
        .replace(/\bPSNCureBerry\b/g, 'Baccantiveleno')
        .replace(/\bPRZCureBerry\b/g, 'Baccantiparalisi')
        .replace(/\bMint Berry\b/g, 'Bacca Menta')
        .replace(/\bBurnt Berry\b/g, 'Bacca Bruciata')
        .replace(/\bIce Berry\b/g, 'Bacca Ghiaccio')
        .replace(/\bBitter Berry\b/g, 'Bacca Amara')
        .replace(/\bMysteryBerry\b/g, 'Bacca Misteriosa')
        .replace(/\bMiracleBerry\b/g, 'Bacca Miracolosa')

    // Bacche - Gen II - con template
        .replace(/\{\{b\|Berry\}\}/gi, '[[Bacca]]')
        .replace(/\{\{b\|Gold\}\}/gi, '[[Bacca Oro]]')
        .replace(/\{\{b\|Mint\}\}/gi, '[[Bacca Menta]]')
        .replace(/\{\{b\|Burnt\}\}/gi, '[[Bacca Bruciata]]')
        .replace(/\{\{b\|Ice\}\}/gi, '[[Bacca Ghiaccio]]')
        .replace(/\{\{b\|Bitter\}\}/gi, '[[Bacca Amara]]')

    // Bacche - Gen III - no template
        .replace(/\bCheri Berry\b/g, 'Baccaliegia')
        .replace(/\bChesto Berry\b/g, 'Baccastagna')
        .replace(/\bPecha Berry\b/g, 'Baccapesca')
        .replace(/\bRawst Berry\b/g, 'Baccafrago')
        .replace(/\bAspear Berry\b/g, 'Baccaperina')
        .replace(/\bLeppa Berry\b/g, 'Baccamela')
        .replace(/\bOran Berry\b/g, 'Baccarancia')
        .replace(/\bPersim Berry\b/g, 'Baccaki')
        .replace(/\bLum Berry\b/g, 'Baccaprugna')
        .replace(/\bSitrus Berry\b/g, 'Baccacedro')
        .replace(/\bFigy Berry\b/g, 'Baccafico')
        .replace(/\bWiki Berry\b/g, 'Baccaprugna')
        .replace(/\bMago Berry\b/g, 'Baccamango')
        .replace(/\bAguav Berry\b/g, 'Baccaguava')
        .replace(/\bIapapa Berry\b/g, 'Baccapaia')
        .replace(/\bRazz Berry\b/g, 'Baccalampon')
        .replace(/\bBluk Berry\b/g, 'Baccamora')
        .replace(/\bNanab Berry\b/g, 'Baccabana')
        .replace(/\bWepear Berry\b/g, 'Baccapera')
        .replace(/\bPinap Berry\b/g, 'Baccananas')
        .replace(/\bPomeg Berry\b/g, 'Baccagrana')
        .replace(/\bKelpsy Berry\b/g, 'Baccalga')
        .replace(/\bQualot Berry\b/g, 'Baccaloquat')
        .replace(/\bHondew Berry\b/g, 'Baccamelon')
        .replace(/\bGrepa Berry\b/g, 'Baccauva')
        .replace(/\bTamato Berry\b/g, 'Baccamodoro')
        .replace(/\bCornn Berry\b/g, 'Baccavena')
        .replace(/\bMagost Berry\b/g, 'Baccagostan')
        .replace(/\bRabuta Berry\b/g, 'Baccambutan')
        .replace(/\bNomel Berry\b/g, 'Baccalemon')
        .replace(/\bSpelon Berry\b/g, 'Baccamelos')
        .replace(/\bPamtre Berry\b/g, 'Baccapalma')
        .replace(/\bWatmel Berry\b/g, 'Baccacomero')
        .replace(/\bDurin Berry\b/g, 'Baccadurian')
        .replace(/\bBelue Berry\b/g, 'Baccartillo')
        .replace(/\bLiechi Berry\b/g, 'Baccalici')
        .replace(/\bGanlon Berry\b/g, 'Baccalongan')
        .replace(/\bSalac Berry\b/g, 'Baccasalak')
        .replace(/\bPetaya Berry\b/g, 'Baccapitaya')
        .replace(/\bApicot Berry\b/g, 'Baccacocca')
        .replace(/\bLansat Berry\b/g, 'Baccalangsa')
        .replace(/\bStarf Berry\b/g, 'Baccambola')
        .replace(/\bEnigma Berry\b/g, 'Baccaenigma')

    // Bacche - Gen III - con template
        .replace(/\{\{b\|Cheri\}\}/gi, '[[Baccaliegia]]')
        .replace(/\{\{b\|Chesto\}\}/gi, '[[Baccastagna]]')
        .replace(/\{\{b\|Pecha\}\}/gi, '[[Baccapesca]]')
        .replace(/\{\{b\|Rawst\}\}/gi, '[[Baccafrago]]')
        .replace(/\{\{b\|Aspear\}\}/gi, '[[Baccaperina]]')
        .replace(/\{\{b\|Leppa\}\}/gi, '[[Baccamela]]')
        .replace(/\{\{b\|Oran\}\}/gi, '[[Baccarancia]]')
        .replace(/\{\{b\|Persim\}\}/gi, '[[Baccaki]]')
        .replace(/\{\{b\|Lum\}\}/gi, '[[Baccaprugna]]')
        .replace(/\{\{b\|Sitrus\}\}/gi, '[[Baccacedro]]')
        .replace(/\{\{b\|Figy\}\}/gi, '[[Baccafico]]')
        .replace(/\{\{b\|Wiki\}\}/gi, '[[Baccaprugna]]')
        .replace(/\{\{b\|Mago\}\}/gi, '[[Baccamango]]')
        .replace(/\{\{b\|Aguav\}\}/gi, '[[Baccaguava]]')
        .replace(/\{\{b\|Iapapa\}\}/gi, '[[Baccapaia]]')
        .replace(/\{\{b\|Razz\}\}/gi, '[[Baccalampon]]')
        .replace(/\{\{b\|Bluk\}\}/gi, '[[Baccamora]]')
        .replace(/\{\{b\|Nanab\}\}/gi, '[[Baccabana]]')
        .replace(/\{\{b\|Wepear\}\}/gi, '[[Baccapera]]')
        .replace(/\{\{b\|Pinap\}\}/gi, '[[Baccananas]]')
        .replace(/\{\{b\|Pomeg\}\}/gi, '[[Baccagrana]]')
        .replace(/\{\{b\|Kelpsy\}\}/gi, '[[Baccalga]]')
        .replace(/\{\{b\|Qualot\}\}/gi, '[[Baccaloquat]]')
        .replace(/\{\{b\|Hondew\}\}/gi, '[[Baccamelon]]')
        .replace(/\{\{b\|Grepa\}\}/gi, '[[Baccauva]]')
        .replace(/\{\{b\|Tamato\}\}/gi, '[[Baccamodoro]]')
        .replace(/\{\{b\|Cornn\}\}/gi, '[[Baccavena]]')
        .replace(/\{\{b\|Magost\}\}/gi, '[[Baccagostan]]')
        .replace(/\{\{b\|Rabuta\}\}/gi, '[[Baccambutan]]')
        .replace(/\{\{b\|Nomel\}\}/gi, '[[Baccalemon]]')
        .replace(/\{\{b\|Spelon\}\}/gi, '[[Baccamelos]]')
        .replace(/\{\{b\|Pamtre\}\}/gi, '[[Baccapalma]]')
        .replace(/\{\{b\|Watmel\}\}/gi, '[[Baccacomero]]')
        .replace(/\{\{b\|Durin\}\}/gi, '[[Baccadurian]]')
        .replace(/\{\{b\|Belue\}\}/gi, '[[Baccartillo]]')
        .replace(/\{\{b\|Liechi\}\}/gi, '[[Baccalici]]')
        .replace(/\{\{b\|Ganlon\}\}/gi, '[[Baccalongan]]')
        .replace(/\{\{b\|Salac\}\}/gi, '[[Baccasalak]]')
        .replace(/\{\{b\|Petaya\}\}/gi, '[[Baccapitaya]]')
        .replace(/\{\{b\|Apicot\}\}/gi, '[[Baccacocca]]')
        .replace(/\{\{b\|Lansat\}\}/gi, '[[Baccalangsa]]')
        .replace(/\{\{b\|Starf\}\}/gi, '[[Baccambola]]')
        .replace(/\{\{b\|Enigma\}\}/gi, '[[Baccaenigma]]')


    // Bacche - Gen IV - no template
        .replace(/\bOcca Berry\b/g, 'Baccacao')
        .replace(/\bPassho Berry\b/g, 'Baccapasflo')
        .replace(/\bWacan Berry\b/g, 'Baccaparmen')
        .replace(/\bRindo Berry\b/g, 'Baccarindo')
        .replace(/\bYache Berry\b/g, 'Baccamoya')
        .replace(/\bChople Berry\b/g, 'Baccarosmel')
        .replace(/\bKebia Berry\b/g, 'Baccakebia')
        .replace(/\bShuca Berry\b/g, 'Baccanaca')
        .replace(/\bCoba Berry\b/g, 'Baccababa')
        .replace(/\bPayapa Berry\b/g, 'Baccapayapa')
        .replace(/\bTanga Berry\b/g, 'Baccaitan')
        .replace(/\bCharti Berry\b/g, 'Baccaciofo')
        .replace(/\bKasib Berry\b/g, 'Baccacitrus')
        .replace(/\bHaban Berry\b/g, 'Baccahaban')
        .replace(/\bColbur Berry\b/g, 'Baccaxan')
        .replace(/\bBabiri Berry\b/g, 'Baccababiri')
        .replace(/\bChilan Berry\b/g, 'Baccacinlan')
        .replace(/\bMicle Berry\b/g, 'Baccaracolo')
        .replace(/\bCustap Berry\b/g, 'Baccacrela')
        .replace(/\bJaboca Berry\b/g, 'Baccajaba')
        .replace(/\bRowap Berry\b/g, 'Baccaroam')

    // Bacche - Gen IV - con template
        .replace(/\{\{b\|Occa\}\}/gi, '[[Baccacao]]')
        .replace(/\{\{b\|Passho\}\}/gi, '[[Baccapasflo]]')
        .replace(/\{\{b\|Wacan\}\}/gi, '[[Baccaparmen]]')
        .replace(/\{\{b\|Rindo\}\}/gi, '[[Baccarindo]]')
        .replace(/\{\{b\|Yache\}\}/gi, '[[Baccamoya]]')
        .replace(/\{\{b\|Chople\}\}/gi, '[[Baccarosmel]]')
        .replace(/\{\{b\|Kebia\}\}/gi, '[[Baccakebia]]')
        .replace(/\{\{b\|Shuca\}\}/gi, '[[Baccanaca]]')
        .replace(/\{\{b\|Coba\}\}/gi, '[[Baccababa]]')
        .replace(/\{\{b\|Payapa\}\}/gi, '[[Baccapayapa]]')
        .replace(/\{\{b\|Tanga\}\}/gi, '[[Baccaitan]]')
        .replace(/\{\{b\|Charti\}\}/gi, '[[Baccaciofo]]')
        .replace(/\{\{b\|Kasib\}\}/gi, '[[Baccacitrus]]')
        .replace(/\{\{b\|Haban\}\}/gi, '[[Baccahaban]]')
        .replace(/\{\{b\|Colbur\}\}/gi, '[[Baccaxan]]')
        .replace(/\{\{b\|Babiri\}\}/gi, '[[Baccababiri]]')
        .replace(/\{\{b\|Chilan\}\}/gi, '[[Baccacinlan]]')
        .replace(/\{\{b\|Micle\}\}/gi, '[[Baccaracolo]]')
        .replace(/\{\{b\|Custap\}\}/gi, '[[Baccacrela]]')
        .replace(/\{\{b\|Jaboca\}\}/gi, '[[Baccajaba]]')
        .replace(/\{\{b\|Rowap\}\}/gi, '[[Baccaroam]]')

    // Bacche - Gen VI - no template
        .replace(/\bRoseli Berry\b/g, 'Baccarcad&egrave')
        .replace(/\bKee Berry\b/g, 'Baccalighia')
        .replace(/\bMaranga Berry\b/g, 'Baccapane')

    // Bacche - Gen VI - template
        .replace(/\{\{b\|Roseli\}\}/gi, '[[Baccarcad&egrave]]')
        .replace(/\{\{b\|Kee\}\}/gi, '[[Baccalighia]]')
        .replace(/\{\{b\|Maranga\}\}/gi, '[[Baccapane]]')

    // Megapietre
        .replace(/\bAbomasite\b/g, 'Abomasnowite')
        .replace(/\bAlakazite\b/g, 'Alakazamite')
        .replace(/\bBlastoisinite\b/g, 'Blastoisite')
        .replace(/\bHeracronite\b/g, 'Heracrossite')
        .replace(/\bHoundoominite\b/g, 'Houndoomite')
        .replace(/\bLucarionite\b/g, 'Lucarite')
        .replace(/\bManectite\b/g, 'Manectricite')
        .replace(/\bMewtwonite X\b/g, 'Mewtwoite X')
        .replace(/\bMewtwonite Y\b/g, 'Mewtwoite Y')
        .replace(/\bSablenite\b/g, 'Sableyite')
        .replace(/\bAltarianite\b/g, 'Altarite')
        .replace(/\bSharpedonite\b/g, 'Sharpedite')
        .replace(/\bSlowbronite\b/g, 'Slowbroite')
        .replace(/\bGlalitite\b/g, 'Glalite')

  // Cristalli Z
        .replace(/\bBuginium Z\b/g, 'Insectium Z')
        .replace(/\bDarkinium Z\b/g, 'Obscurium Z')
        .replace(/\bDragonium Z\b/g, 'Draconium Z')
        .replace(/\bElectrium Z\b/g, 'Electrium Z')
        .replace(/\bFairium Z\b/g, 'Follectium Z')
        .replace(/\bFightinium Z\b/g, 'Luctium Z')
        .replace(/\bFirium Z\b/g, 'Pirium Z')
        .replace(/\bFlyinium Z\b/g, 'Volantium Z')
        .replace(/\bGhostium Z\b/g, 'Spectrium Z')
        .replace(/\bGrassium Z\b/g, 'Herbium Z')
        .replace(/\bGroundium Z\b/g, 'Terrium Z')
        .replace(/\bIcium Z\b/g, 'Glacium Z')
        .replace(/\bNormalium Z\b/g, 'Normium Z')
        .replace(/\bPoisonium Z\b/g, 'Venenium Z')
        .replace(/\bPsychium Z\b/g, 'Psichium Z')
        .replace(/\bRockium Z\b/g, 'Petrium Z')
        .replace(/\bSteelium Z\b/g, 'Metallium Z')
        .replace(/\bWaterium Z\b/g, 'Idrium Z')
        .replace(/\bPikanium Z\b/g, 'Pikacium Z')
        //.replace(/Pikashunium Z/gi, '')
        .replace(/\bAloraichium Z\b/g, 'Aloraicium Z')
        .replace(/\bEevium Z\b/g, 'Eevium Z')
        .replace(/\bSnorlium Z\b/g, 'Snorlactium Z')
        //.replace(/Mewnium Z/gi, '')
        .replace(/\bDecidium Z\b/g, 'Deciduenium Z')
        .replace(/\bIncinium Z\b/g, 'Incineronium Z')
        .replace(/\bPrimarium Z\b/g, 'Primarinium Z')
        .replace(/\bTapunium Z\b/g, 'Tapium Z')
        //.replace(/Marshadium Z/gi, '')

    // Correzione errori
        .replace(/\bCalamita Pull\b/g, 'Magnetismo');
        // .replace(/Calamitaon/gi, 'Magneton')
        // .replace(/Calamitaismo/gi, 'Magnetismo')
        // .replace(/Gamboy Hold/gi, 'Sticky Hold');
};

macros['strumenti lotta'] = function(str) {
	return macros.strumenti(str, true);
};

if (utils.updateMenu) { utils.updateMenu() } ;
}(utils || { macros: {} }));
